package com.shnupbups.extrapieces;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ModBlocks {

	public static PiecesSet PRISMARINE_PIECES;
	public static PiecesSet PRISMARINE_BRICK_PIECES;
	public static PiecesSet DARK_PRISMARINE_PIECES;
	public static PiecesSet OAK_PIECES;
	public static PiecesSet SPRUCE_PIECES;
	public static PiecesSet BIRCH_PIECES;
	public static PiecesSet JUNGLE_PIECES;
	public static PiecesSet ACACIA_PIECES;
	public static PiecesSet DARK_OAK_PIECES;
	public static PiecesSet STONE_PIECES;
	public static PiecesSet SMOOTH_STONE_PIECES;
	public static PiecesSet SANDSTONE_PIECES;
	public static PiecesSet CUT_SANDSTONE_PIECES;
	public static PiecesSet PETRIFIED_OAK_PIECES;
	public static PiecesSet COBBLESTONE_PIECES;
	public static PiecesSet BRICK_PIECES;
	public static PiecesSet STONE_BRICK_PIECES;
	public static PiecesSet NETHER_BRICK_PIECES;
	public static PiecesSet QUARTZ_PIECES;
	public static PiecesSet RED_SANDSTONE_PIECES;
	public static PiecesSet CUT_RED_SANDSTONE_PIECES;
	public static PiecesSet PURPUR_PIECES;
	public static PiecesSet POLISHED_GRANITE_PIECES;
	public static PiecesSet SMOOTH_RED_SANDSTONE_PIECES;
	public static PiecesSet MOSSY_STONE_BRICK_PIECES;
	public static PiecesSet POLISHED_DIORITE_PIECES;
	public static PiecesSet MOSSY_COBBLESTONE_PIECES;
	public static PiecesSet END_STONE_BRICK_PIECES;
	public static PiecesSet SMOOTH_SANDSTONE_PIECES;
	public static PiecesSet SMOOTH_QUARTZ_PIECES;
	public static PiecesSet GRANITE_PIECES;
	public static PiecesSet ANDESITE_PIECES;
	public static PiecesSet RED_NETHER_BRICK_PIECES;
	public static PiecesSet POLISHED_ANDESITE_PIECES;
	public static PiecesSet DIORITE_PIECES;
	public static PiecesSet NETHERRACK_PIECES;
	public static PiecesSet END_STONE_PIECES;
	public static PiecesSet QUARTZ_PILLAR_PIECES;
	public static PiecesSet CHISELED_QUARTZ_PIECES;
	public static PiecesSet CHISELED_SANDSTONE_PIECES;
	public static PiecesSet CHISELED_RED_SANDSTONE_PIECES;
	public static PiecesSet CRACKED_STONE_BRICK_PIECES;
	public static PiecesSet CHISELED_STONE_BRICK_PIECES;
	public static PiecesSet PURPUR_PILLAR_PIECES;
	public static PiecesSet TERRACOTTA_PIECES;
	public static PiecesSet WHITE_TERRACOTTA_PIECES;
	public static PiecesSet ORANGE_TERRACOTTA_PIECES;
	public static PiecesSet MAGENTA_TERRACOTTA_PIECES;
	public static PiecesSet LIGHT_BLUE_TERRACOTTA_PIECES;
	public static PiecesSet YELLOW_TERRACOTTA_PIECES;
	public static PiecesSet LIME_TERRACOTTA_PIECES;
	public static PiecesSet PINK_TERRACOTTA_PIECES;
	public static PiecesSet GRAY_TERRACOTTA_PIECES;
	public static PiecesSet LIGHT_GRAY_TERRACOTTA_PIECES;
	public static PiecesSet CYAN_TERRACOTTA_PIECES;
	public static PiecesSet PURPLE_TERRACOTTA_PIECES;
	public static PiecesSet BLUE_TERRACOTTA_PIECES;
	public static PiecesSet BROWN_TERRACOTTA_PIECES;
	public static PiecesSet GREEN_TERRACOTTA_PIECES;
	public static PiecesSet RED_TERRACOTTA_PIECES;
	public static PiecesSet BLACK_TERRACOTTA_PIECES;
	public static PiecesSet WHITE_CONCRETE_PIECES;
	public static PiecesSet ORANGE_CONCRETE_PIECES;
	public static PiecesSet MAGENTA_CONCRETE_PIECES;
	public static PiecesSet LIGHT_BLUE_CONCRETE_PIECES;
	public static PiecesSet YELLOW_CONCRETE_PIECES;
	public static PiecesSet LIME_CONCRETE_PIECES;
	public static PiecesSet PINK_CONCRETE_PIECES;
	public static PiecesSet GRAY_CONCRETE_PIECES;
	public static PiecesSet LIGHT_GRAY_CONCRETE_PIECES;
	public static PiecesSet CYAN_CONCRETE_PIECES;
	public static PiecesSet PURPLE_CONCRETE_PIECES;
	public static PiecesSet BLUE_CONCRETE_PIECES;
	public static PiecesSet BROWN_CONCRETE_PIECES;
	public static PiecesSet GREEN_CONCRETE_PIECES;
	public static PiecesSet RED_CONCRETE_PIECES;
	public static PiecesSet BLACK_CONCRETE_PIECES;
	public static PiecesSet GOLD_PIECES;
	public static PiecesSet IRON_PIECES;
	public static PiecesSet DIAMOND_PIECES;
	public static PiecesSet EMERALD_PIECES;
	public static PiecesSet REDSTONE_PIECES;
	public static PiecesSet COAL_PIECES;
	public static PiecesSet LAPIS_LAZULI_PIECES;
	public static PiecesSet PACKED_ICE_PIECES;
	public static PiecesSet WHITE_WOOL_PIECES;
	public static PiecesSet ORANGE_WOOL_PIECES;
	public static PiecesSet MAGENTA_WOOL_PIECES;
	public static PiecesSet LIGHT_BLUE_WOOL_PIECES;
	public static PiecesSet YELLOW_WOOL_PIECES;
	public static PiecesSet LIME_WOOL_PIECES;
	public static PiecesSet PINK_WOOL_PIECES;
	public static PiecesSet GRAY_WOOL_PIECES;
	public static PiecesSet LIGHT_GRAY_WOOL_PIECES;
	public static PiecesSet CYAN_WOOL_PIECES;
	public static PiecesSet PURPLE_WOOL_PIECES;
	public static PiecesSet BLUE_WOOL_PIECES;
	public static PiecesSet BROWN_WOOL_PIECES;
	public static PiecesSet GREEN_WOOL_PIECES;
	public static PiecesSet RED_WOOL_PIECES;
	public static PiecesSet BLACK_WOOL_PIECES;
	public static PiecesSet WHITE_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet ORANGE_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet MAGENTA_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet YELLOW_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet LIME_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet PINK_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet CYAN_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet PURPLE_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet BROWN_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet GREEN_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet RED_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet BLACK_GLAZED_TERRACOTTA_PIECES;
	public static PiecesSet OBSIDIAN_PIECES;
	public static PiecesSet BONE_PIECES;
	public static PiecesSet HAY_PIECES;
	public static PiecesSet PUMPKIN_PIECES;
	public static PiecesSet MELON_PIECES;
	public static PiecesSet SNOW_PIECES;
	public static PiecesSet MAGMA_PIECES;
	public static PiecesSet GLOWSTONE_PIECES;
	public static PiecesSet NETHER_WART_PIECES;
	public static PiecesSet BROWN_MUSHROOM_PIECES;
	public static PiecesSet RED_MUSHROOM_PIECES;
	public static PiecesSet MUSHROOM_STEM_PIECES;
	public static PiecesSet DRIED_KELP_PIECES;
	public static PiecesSet TUBE_CORAL_PIECES;
	public static PiecesSet BRAIN_CORAL_PIECES;
	public static PiecesSet BUBBLE_CORAL_PIECES;
	public static PiecesSet FIRE_CORAL_PIECES;
	public static PiecesSet HORN_CORAL_PIECES;
	public static PiecesSet DEAD_TUBE_CORAL_PIECES;
	public static PiecesSet DEAD_BRAIN_CORAL_PIECES;
	public static PiecesSet DEAD_BUBBLE_CORAL_PIECES;
	public static PiecesSet DEAD_FIRE_CORAL_PIECES;
	public static PiecesSet DEAD_HORN_CORAL_PIECES;
	public static PiecesSet OAK_LOG_PIECES;
	public static PiecesSet SPRUCE_LOG_PIECES;
	public static PiecesSet BIRCH_LOG_PIECES;
	public static PiecesSet JUNGLE_LOG_PIECES;
	public static PiecesSet ACACIA_LOG_PIECES;
	public static PiecesSet DARK_OAK_LOG_PIECES;
	public static PiecesSet STRIPPED_OAK_LOG_PIECES;
	public static PiecesSet STRIPPED_SPRUCE_LOG_PIECES;
	public static PiecesSet STRIPPED_BIRCH_LOG_PIECES;
	public static PiecesSet STRIPPED_JUNGLE_LOG_PIECES;
	public static PiecesSet STRIPPED_ACACIA_LOG_PIECES;
	public static PiecesSet STRIPPED_DARK_OAK_LOG_PIECES;
	public static PiecesSet OAK_WOOD_PIECES;
	public static PiecesSet SPRUCE_WOOD_PIECES;
	public static PiecesSet BIRCH_WOOD_PIECES;
	public static PiecesSet JUNGLE_WOOD_PIECES;
	public static PiecesSet ACACIA_WOOD_PIECES;
	public static PiecesSet DARK_OAK_WOOD_PIECES;
	public static PiecesSet STRIPPED_OAK_WOOD_PIECES;
	public static PiecesSet STRIPPED_SPRUCE_WOOD_PIECES;
	public static PiecesSet STRIPPED_BIRCH_WOOD_PIECES;
	public static PiecesSet STRIPPED_JUNGLE_WOOD_PIECES;
	public static PiecesSet STRIPPED_ACACIA_WOOD_PIECES;
	public static PiecesSet STRIPPED_DARK_OAK_WOOD_PIECES;

	protected static Block register(String string_1, Block block_1) {
		return Registry.register(Registry.BLOCK, new Identifier("extrapieces",string_1), block_1);
	}

	public static void init() {
		PRISMARINE_PIECES = PiecesSet.createSet(Blocks.PRISMARINE, "prismarine", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		PRISMARINE_BRICK_PIECES = PiecesSet.createSet(Blocks.PRISMARINE_BRICKS, "prismarine_brick", PiecesSet.NO_SLAB_OR_STAIRS).register();
		DARK_PRISMARINE_PIECES = PiecesSet.createSet(Blocks.DARK_PRISMARINE, "dark_prismarine", PiecesSet.NO_SLAB_OR_STAIRS).register();
		OAK_PIECES = PiecesSet.createSet(Blocks.OAK_PLANKS, "oak", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		SPRUCE_PIECES = PiecesSet.createSet(Blocks.SPRUCE_PLANKS, "spruce", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		BIRCH_PIECES = PiecesSet.createSet(Blocks.BIRCH_PLANKS, "birch", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		JUNGLE_PIECES = PiecesSet.createSet(Blocks.JUNGLE_PLANKS, "jungle", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		ACACIA_PIECES = PiecesSet.createSet(Blocks.ACACIA_PLANKS, "acacia", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		DARK_OAK_PIECES = PiecesSet.createSet(Blocks.DARK_OAK_PLANKS, "dark_oak", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.WALL).register();
		STONE_PIECES = PiecesSet.createSet(Blocks.STONE, "stone", PiecesSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_STONE_PIECES = PiecesSet.createSet(Blocks.SMOOTH_STONE, "smooth_stone", PiecesSet.NO_SLAB).register();
		SANDSTONE_PIECES = PiecesSet.createSet(Blocks.SANDSTONE, "sandstone", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		CUT_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.CUT_SANDSTONE, "cut_sandstone", PiecesSet.NO_SLAB).register();
		PETRIFIED_OAK_PIECES = PiecesSet.createSet(Blocks.PETRIFIED_OAK_SLAB, "petrified_oak", PiecesSet.BlockPiece.SIDING).register();
		COBBLESTONE_PIECES = PiecesSet.createSet(Blocks.COBBLESTONE, "cobblestone", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		BRICK_PIECES = PiecesSet.createSet(Blocks.BRICKS, "brick", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		STONE_BRICK_PIECES = PiecesSet.createSet(Blocks.STONE_BRICKS, "stone_brick", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		NETHER_BRICK_PIECES = PiecesSet.createSet(Blocks.NETHER_BRICKS, "nether_brick", PiecesSet.BlockPiece.SIDING, PiecesSet.BlockPiece.FENCE_GATE).register();
		QUARTZ_PIECES = PiecesSet.createSet(Blocks.QUARTZ_BLOCK, "quartz", PiecesSet.NO_SLAB_OR_STAIRS).register();
		RED_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.RED_SANDSTONE, "red_sandstone", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		CUT_RED_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.CUT_RED_SANDSTONE, "cut_red_sandstone", PiecesSet.NO_SLAB).register();
		PURPUR_PIECES = PiecesSet.createSet(Blocks.PURPUR_BLOCK, "purpur", PiecesSet.NO_SLAB_OR_STAIRS).register();
		POLISHED_GRANITE_PIECES = PiecesSet.createSet(Blocks.POLISHED_GRANITE, "polished_granite", PiecesSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_RED_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.SMOOTH_RED_SANDSTONE, "smooth_red_sandstone", PiecesSet.NO_SLAB_OR_STAIRS).register();
		MOSSY_STONE_BRICK_PIECES = PiecesSet.createSet(Blocks.MOSSY_STONE_BRICKS, "mossy_stone_brick", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		POLISHED_DIORITE_PIECES = PiecesSet.createSet(Blocks.POLISHED_DIORITE, "polished_diorite", PiecesSet.NO_SLAB_OR_STAIRS).register();
		MOSSY_COBBLESTONE_PIECES = PiecesSet.createSet(Blocks.MOSSY_COBBLESTONE, "mossy_cobblestone", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		END_STONE_BRICK_PIECES = PiecesSet.createSet(Blocks.END_STONE_BRICKS, "end_stone_brick", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		SMOOTH_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.SMOOTH_SANDSTONE, "smooth_sandstone", PiecesSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_QUARTZ_PIECES = PiecesSet.createSet(Blocks.SMOOTH_QUARTZ, "smooth_quartz", PiecesSet.NO_SLAB_OR_STAIRS).register();
		GRANITE_PIECES = PiecesSet.createSet(Blocks.GRANITE, "granite", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		ANDESITE_PIECES = PiecesSet.createSet(Blocks.ANDESITE, "andesite", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		RED_NETHER_BRICK_PIECES = PiecesSet.createSet(Blocks.RED_NETHER_BRICKS, "red_nether_brick", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		POLISHED_ANDESITE_PIECES = PiecesSet.createSet(Blocks.POLISHED_ANDESITE, "polished_andesite", PiecesSet.NO_SLAB_OR_STAIRS).register();
		DIORITE_PIECES = PiecesSet.createSet(Blocks.DIORITE, "diorite", PiecesSet.NO_SLAB_STAIRS_OR_WALL).register();
		NETHERRACK_PIECES = PiecesSet.createSet(Blocks.NETHERRACK, "netherrack").register();
		END_STONE_PIECES = PiecesSet.createSet(Blocks.END_STONE, "end_stone").register();
		QUARTZ_PILLAR_PIECES = PiecesSet.createSet(Blocks.QUARTZ_PILLAR, "quartz_pillar").register();
		CHISELED_QUARTZ_PIECES = PiecesSet.createSet(Blocks.CHISELED_QUARTZ_BLOCK, "chiseled_quartz").register();
		CHISELED_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.CHISELED_SANDSTONE, "chiseled_sandstone").register();
		CHISELED_RED_SANDSTONE_PIECES = PiecesSet.createSet(Blocks.CHISELED_RED_SANDSTONE, "chiseled_red_sandstone").register();
		CRACKED_STONE_BRICK_PIECES = PiecesSet.createSet(Blocks.CRACKED_STONE_BRICKS, "cracked_stone_brick").register();
		CHISELED_STONE_BRICK_PIECES = PiecesSet.createSet(Blocks.CHISELED_STONE_BRICKS, "chiseled_stone_brick").register();
		PURPUR_PILLAR_PIECES = PiecesSet.createSet(Blocks.PURPUR_PILLAR, "purpur_pillar").register();
		TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.TERRACOTTA, "terracotta").register();
		WHITE_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.WHITE_TERRACOTTA, "white_terracotta").register();
		ORANGE_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.ORANGE_TERRACOTTA, "orange_terracotta").register();
		MAGENTA_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.MAGENTA_TERRACOTTA, "magenta_terracotta").register();
		LIGHT_BLUE_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIGHT_BLUE_TERRACOTTA, "light_blue_terracotta").register();
		YELLOW_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.YELLOW_TERRACOTTA, "yellow_terracotta").register();
		LIME_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIME_TERRACOTTA, "lime_terracotta").register();
		PINK_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.PINK_TERRACOTTA, "pink_terracotta").register();
		GRAY_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.GRAY_TERRACOTTA, "gray_terracotta").register();
		LIGHT_GRAY_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIGHT_GRAY_TERRACOTTA, "light_gray_terracotta").register();
		CYAN_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.CYAN_TERRACOTTA, "cyan_terracotta").register();
		PURPLE_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.PURPLE_TERRACOTTA, "purple_terracotta").register();
		BLUE_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BLUE_TERRACOTTA, "blue_terracotta").register();
		BROWN_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BROWN_TERRACOTTA, "brown_terracotta").register();
		GREEN_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.GREEN_TERRACOTTA, "green_terracotta").register();
		RED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.RED_TERRACOTTA, "red_terracotta").register();
		BLACK_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BLACK_TERRACOTTA, "black_terracotta").register();
		WHITE_CONCRETE_PIECES = PiecesSet.createSet(Blocks.WHITE_CONCRETE, "white_concrete").register();
		ORANGE_CONCRETE_PIECES = PiecesSet.createSet(Blocks.ORANGE_CONCRETE, "orange_concrete").register();
		MAGENTA_CONCRETE_PIECES = PiecesSet.createSet(Blocks.MAGENTA_CONCRETE, "magenta_concrete").register();
		LIGHT_BLUE_CONCRETE_PIECES = PiecesSet.createSet(Blocks.LIGHT_BLUE_CONCRETE, "light_blue_concrete").register();
		YELLOW_CONCRETE_PIECES = PiecesSet.createSet(Blocks.YELLOW_CONCRETE, "yellow_concrete").register();
		LIME_CONCRETE_PIECES = PiecesSet.createSet(Blocks.LIME_CONCRETE, "lime_concrete").register();
		PINK_CONCRETE_PIECES = PiecesSet.createSet(Blocks.PINK_CONCRETE, "pink_concrete").register();
		GRAY_CONCRETE_PIECES = PiecesSet.createSet(Blocks.GRAY_CONCRETE, "gray_concrete").register();
		LIGHT_GRAY_CONCRETE_PIECES = PiecesSet.createSet(Blocks.LIGHT_GRAY_CONCRETE, "light_gray_concrete").register();
		CYAN_CONCRETE_PIECES = PiecesSet.createSet(Blocks.CYAN_CONCRETE, "cyan_concrete").register();
		PURPLE_CONCRETE_PIECES = PiecesSet.createSet(Blocks.PURPLE_CONCRETE, "purple_concrete").register();
		BLUE_CONCRETE_PIECES = PiecesSet.createSet(Blocks.BLUE_CONCRETE, "blue_concrete").register();
		BROWN_CONCRETE_PIECES = PiecesSet.createSet(Blocks.BROWN_CONCRETE, "brown_concrete").register();
		GREEN_CONCRETE_PIECES = PiecesSet.createSet(Blocks.GREEN_CONCRETE, "green_concrete").register();
		RED_CONCRETE_PIECES = PiecesSet.createSet(Blocks.RED_CONCRETE, "red_concrete").register();
		BLACK_CONCRETE_PIECES = PiecesSet.createSet(Blocks.BLACK_CONCRETE, "black_concrete").register();
		GOLD_PIECES = PiecesSet.createSet(Blocks.GOLD_BLOCK, "gold").register();
		IRON_PIECES = PiecesSet.createSet(Blocks.IRON_BLOCK, "iron").register();
		DIAMOND_PIECES = PiecesSet.createSet(Blocks.DIAMOND_BLOCK, "diamond").register();
		EMERALD_PIECES = PiecesSet.createSet(Blocks.EMERALD_BLOCK, "emerald").register();
		REDSTONE_PIECES = PiecesSet.createSet(Blocks.REDSTONE_BLOCK, "redstone").register();
		COAL_PIECES = PiecesSet.createSet(Blocks.COAL_BLOCK, "coal").register();
		LAPIS_LAZULI_PIECES = PiecesSet.createSet(Blocks.LAPIS_BLOCK, "lapis_lazuli").register();
		PACKED_ICE_PIECES = PiecesSet.createSet(Blocks.PACKED_ICE, "packed_ice").register();
		WHITE_WOOL_PIECES = PiecesSet.createSet(Blocks.WHITE_WOOL, "white_wool").register();
		ORANGE_WOOL_PIECES = PiecesSet.createSet(Blocks.ORANGE_WOOL, "orange_wool").register();
		MAGENTA_WOOL_PIECES = PiecesSet.createSet(Blocks.MAGENTA_WOOL, "magenta_wool").register();
		LIGHT_BLUE_WOOL_PIECES = PiecesSet.createSet(Blocks.LIGHT_BLUE_WOOL, "light_blue_wool").register();
		YELLOW_WOOL_PIECES = PiecesSet.createSet(Blocks.YELLOW_WOOL, "yellow_wool").register();
		LIME_WOOL_PIECES = PiecesSet.createSet(Blocks.LIME_WOOL, "lime_wool").register();
		PINK_WOOL_PIECES = PiecesSet.createSet(Blocks.PINK_WOOL, "pink_wool").register();
		GRAY_WOOL_PIECES = PiecesSet.createSet(Blocks.GRAY_WOOL, "gray_wool").register();
		LIGHT_GRAY_WOOL_PIECES = PiecesSet.createSet(Blocks.LIGHT_GRAY_WOOL, "light_gray_wool").register();
		CYAN_WOOL_PIECES = PiecesSet.createSet(Blocks.CYAN_WOOL, "cyan_wool").register();
		PURPLE_WOOL_PIECES = PiecesSet.createSet(Blocks.PURPLE_WOOL, "purple_wool").register();
		BLUE_WOOL_PIECES = PiecesSet.createSet(Blocks.BLUE_WOOL, "blue_wool").register();
		BROWN_WOOL_PIECES = PiecesSet.createSet(Blocks.BROWN_WOOL, "brown_wool").register();
		GREEN_WOOL_PIECES = PiecesSet.createSet(Blocks.GREEN_WOOL, "green_wool").register();
		RED_WOOL_PIECES = PiecesSet.createSet(Blocks.RED_WOOL, "red_wool").register();
		BLACK_WOOL_PIECES = PiecesSet.createSet(Blocks.BLACK_WOOL, "black_wool").register();
		WHITE_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.WHITE_GLAZED_TERRACOTTA, "white_glazed_terracotta").register();
		ORANGE_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.ORANGE_GLAZED_TERRACOTTA, "orange_glazed_terracotta").register();
		MAGENTA_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.MAGENTA_GLAZED_TERRACOTTA, "magenta_glazed_terracotta").register();
		LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, "light_blue_glazed_terracotta").register();
		YELLOW_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.YELLOW_GLAZED_TERRACOTTA, "yellow_glazed_terracotta").register();
		LIME_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIME_GLAZED_TERRACOTTA, "lime_glazed_terracotta").register();
		PINK_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.PINK_GLAZED_TERRACOTTA, "pink_glazed_terracotta").register();
		GRAY_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.GRAY_GLAZED_TERRACOTTA, "gray_glazed_terracotta").register();
		LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, "light_gray_glazed_terracotta").register();
		CYAN_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.CYAN_GLAZED_TERRACOTTA, "cyan_glazed_terracotta").register();
		PURPLE_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.PURPLE_GLAZED_TERRACOTTA, "purple_glazed_terracotta").register();
		BLUE_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BLUE_GLAZED_TERRACOTTA, "blue_glazed_terracotta").register();
		BROWN_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BROWN_GLAZED_TERRACOTTA, "brown_glazed_terracotta").register();
		GREEN_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.GREEN_GLAZED_TERRACOTTA, "green_glazed_terracotta").register();
		RED_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.RED_GLAZED_TERRACOTTA, "red_glazed_terracotta").register();
		BLACK_GLAZED_TERRACOTTA_PIECES = PiecesSet.createSet(Blocks.BLACK_GLAZED_TERRACOTTA, "black_glazed_terracotta").register();
		OBSIDIAN_PIECES = PiecesSet.createSet(Blocks.OBSIDIAN, "obsidian").register();
		BONE_PIECES = PiecesSet.createSet(Blocks.BONE_BLOCK, "bone").register();
		HAY_PIECES = PiecesSet.createSet(Blocks.HAY_BLOCK, "hay").register();
		PUMPKIN_PIECES = PiecesSet.createSet(Blocks.PUMPKIN, "pumpkin").register();
		MELON_PIECES = PiecesSet.createSet(Blocks.MELON, "melon").register();
		SNOW_PIECES = PiecesSet.createSet(Blocks.SNOW_BLOCK, "snow").register();
		MAGMA_PIECES = PiecesSet.createSet(Blocks.MAGMA_BLOCK, "magma").register();
		GLOWSTONE_PIECES = PiecesSet.createSet(Blocks.GLOWSTONE, "glowstone").register();
		NETHER_WART_PIECES = PiecesSet.createSet(Blocks.NETHER_WART_BLOCK, "nether_wart").register();
		BROWN_MUSHROOM_PIECES = PiecesSet.createSet(Blocks.BROWN_MUSHROOM_BLOCK, "brown_mushroom").register();
		RED_MUSHROOM_PIECES = PiecesSet.createSet(Blocks.RED_MUSHROOM_BLOCK, "red_mushroom").register();
		MUSHROOM_STEM_PIECES = PiecesSet.createSet(Blocks.MUSHROOM_STEM, "mushroom_stem").register();
		DRIED_KELP_PIECES = PiecesSet.createSet(Blocks.DRIED_KELP_BLOCK, "dried_kelp").register();
		TUBE_CORAL_PIECES = PiecesSet.createSet(Blocks.TUBE_CORAL_BLOCK, "tube_coral").register();
		BRAIN_CORAL_PIECES = PiecesSet.createSet(Blocks.BRAIN_CORAL_BLOCK, "brain_coral").register();
		BUBBLE_CORAL_PIECES = PiecesSet.createSet(Blocks.BUBBLE_CORAL_BLOCK, "bubble_coral").register();
		FIRE_CORAL_PIECES = PiecesSet.createSet(Blocks.FIRE_CORAL_BLOCK, "fire_coral").register();
		HORN_CORAL_PIECES = PiecesSet.createSet(Blocks.HORN_CORAL_BLOCK, "horn_coral").register();
		DEAD_TUBE_CORAL_PIECES = PiecesSet.createSet(Blocks.DEAD_TUBE_CORAL_BLOCK, "dead_tube_coral").register();
		DEAD_BRAIN_CORAL_PIECES = PiecesSet.createSet(Blocks.DEAD_BRAIN_CORAL_BLOCK, "dead_brain_coral").register();
		DEAD_BUBBLE_CORAL_PIECES = PiecesSet.createSet(Blocks.DEAD_BUBBLE_CORAL, "dead_bubble_coral").register();
		DEAD_FIRE_CORAL_PIECES = PiecesSet.createSet(Blocks.DEAD_FIRE_CORAL_BLOCK, "dead_fire_coral").register();
		DEAD_HORN_CORAL_PIECES = PiecesSet.createSet(Blocks.DEAD_HORN_CORAL_BLOCK, "dead_horn_coral").register();
		OAK_LOG_PIECES = PiecesSet.createSet(Blocks.OAK_LOG, "oak_log").register();
		SPRUCE_LOG_PIECES = PiecesSet.createSet(Blocks.SPRUCE_LOG, "spruce_log").register();
		BIRCH_LOG_PIECES = PiecesSet.createSet(Blocks.BIRCH_LOG, "birch_log").register();
		JUNGLE_LOG_PIECES = PiecesSet.createSet(Blocks.JUNGLE_LOG, "jungle_log").register();
		ACACIA_LOG_PIECES = PiecesSet.createSet(Blocks.ACACIA_LOG, "acacia_log").register();
		DARK_OAK_LOG_PIECES = PiecesSet.createSet(Blocks.DARK_OAK_LOG, "dark_oak_log").register();
		STRIPPED_OAK_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_OAK_LOG, "stripped_oak_log").register();
		STRIPPED_SPRUCE_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_SPRUCE_LOG, "stripped_spruce_log").register();
		STRIPPED_BIRCH_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_BIRCH_LOG, "stripped_birch_log").register();
		STRIPPED_JUNGLE_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_JUNGLE_LOG, "stripped_jungle_log").register();
		STRIPPED_ACACIA_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_ACACIA_LOG, "stripped_acacia_log").register();
		STRIPPED_DARK_OAK_LOG_PIECES = PiecesSet.createSet(Blocks.STRIPPED_DARK_OAK_LOG, "stripped_dark_oak_log").register();
		OAK_WOOD_PIECES = PiecesSet.createSet(Blocks.OAK_WOOD, "oak_wood").register();
		SPRUCE_WOOD_PIECES = PiecesSet.createSet(Blocks.SPRUCE_WOOD, "spruce_wood").register();
		BIRCH_WOOD_PIECES = PiecesSet.createSet(Blocks.BIRCH_WOOD, "birch_wood").register();
		JUNGLE_WOOD_PIECES = PiecesSet.createSet(Blocks.JUNGLE_WOOD, "jungle_wood").register();
		ACACIA_WOOD_PIECES = PiecesSet.createSet(Blocks.ACACIA_WOOD, "acacia_wood").register();
		DARK_OAK_WOOD_PIECES = PiecesSet.createSet(Blocks.DARK_OAK_WOOD, "dark_oak_wood").register();
		STRIPPED_OAK_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_OAK_WOOD, "stripped_oak_wood").register();
		STRIPPED_SPRUCE_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_SPRUCE_WOOD, "stripped_spruce_wood").register();
		STRIPPED_BIRCH_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_BIRCH_WOOD, "stripped_birch_wood").register();
		STRIPPED_JUNGLE_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_JUNGLE_WOOD, "stripped_jungle_wood").register();
		STRIPPED_ACACIA_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_ACACIA_WOOD, "stripped_acacia_wood").register();
		STRIPPED_DARK_OAK_WOOD_PIECES = PiecesSet.createSet(Blocks.STRIPPED_DARK_OAK_WOOD, "stripped_dark_oak_wood").register();
/*
		Iterator var0 = Registry.BLOCK.iterator();

		while(var0.hasNext()) {
			Block block_1 = (Block)var0.next();
			UnmodifiableIterator var2 = block_1.getStateFactory().getStates().iterator();

			while(var2.hasNext()) {
				BlockState blockState_1 = (BlockState)var2.next();
				blockState_1.initShapeCache();
				Block.STATE_IDS.add(blockState_1);
			}

			block_1.getDropTableId();
		}*/
	}
}