package com.shnupbups.extrapieces;

import net.minecraft.block.Blocks;

public class ModBlocks {

	public static PieceSet PRISMARINE_PIECES;
	public static PieceSet PRISMARINE_BRICK_PIECES;
	public static PieceSet DARK_PRISMARINE_PIECES;
	public static PieceSet OAK_PIECES;
	public static PieceSet SPRUCE_PIECES;
	public static PieceSet BIRCH_PIECES;
	public static PieceSet JUNGLE_PIECES;
	public static PieceSet ACACIA_PIECES;
	public static PieceSet DARK_OAK_PIECES;
	public static PieceSet STONE_PIECES;
	public static PieceSet SMOOTH_STONE_PIECES;
	public static PieceSet SANDSTONE_PIECES;
	public static PieceSet CUT_SANDSTONE_PIECES;
	public static PieceSet PETRIFIED_OAK_PIECES;
	public static PieceSet COBBLESTONE_PIECES;
	public static PieceSet BRICK_PIECES;
	public static PieceSet STONE_BRICK_PIECES;
	public static PieceSet NETHER_BRICK_PIECES;
	public static PieceSet QUARTZ_PIECES;
	public static PieceSet RED_SANDSTONE_PIECES;
	public static PieceSet CUT_RED_SANDSTONE_PIECES;
	public static PieceSet PURPUR_PIECES;
	public static PieceSet POLISHED_GRANITE_PIECES;
	public static PieceSet SMOOTH_RED_SANDSTONE_PIECES;
	public static PieceSet MOSSY_STONE_BRICK_PIECES;
	public static PieceSet POLISHED_DIORITE_PIECES;
	public static PieceSet MOSSY_COBBLESTONE_PIECES;
	public static PieceSet END_STONE_BRICK_PIECES;
	public static PieceSet SMOOTH_SANDSTONE_PIECES;
	public static PieceSet SMOOTH_QUARTZ_PIECES;
	public static PieceSet GRANITE_PIECES;
	public static PieceSet ANDESITE_PIECES;
	public static PieceSet RED_NETHER_BRICK_PIECES;
	public static PieceSet POLISHED_ANDESITE_PIECES;
	public static PieceSet DIORITE_PIECES;
	public static PieceSet NETHERRACK_PIECES;
	public static PieceSet END_STONE_PIECES;
	public static PieceSet QUARTZ_PILLAR_PIECES;
	public static PieceSet CHISELED_QUARTZ_PIECES;
	public static PieceSet CHISELED_SANDSTONE_PIECES;
	public static PieceSet CHISELED_RED_SANDSTONE_PIECES;
	public static PieceSet CRACKED_STONE_BRICK_PIECES;
	public static PieceSet CHISELED_STONE_BRICK_PIECES;
	public static PieceSet PURPUR_PILLAR_PIECES;
	public static PieceSet TERRACOTTA_PIECES;
	public static PieceSet WHITE_TERRACOTTA_PIECES;
	public static PieceSet ORANGE_TERRACOTTA_PIECES;
	public static PieceSet MAGENTA_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_BLUE_TERRACOTTA_PIECES;
	public static PieceSet YELLOW_TERRACOTTA_PIECES;
	public static PieceSet LIME_TERRACOTTA_PIECES;
	public static PieceSet PINK_TERRACOTTA_PIECES;
	public static PieceSet GRAY_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_GRAY_TERRACOTTA_PIECES;
	public static PieceSet CYAN_TERRACOTTA_PIECES;
	public static PieceSet PURPLE_TERRACOTTA_PIECES;
	public static PieceSet BLUE_TERRACOTTA_PIECES;
	public static PieceSet BROWN_TERRACOTTA_PIECES;
	public static PieceSet GREEN_TERRACOTTA_PIECES;
	public static PieceSet RED_TERRACOTTA_PIECES;
	public static PieceSet BLACK_TERRACOTTA_PIECES;
	public static PieceSet WHITE_CONCRETE_PIECES;
	public static PieceSet ORANGE_CONCRETE_PIECES;
	public static PieceSet MAGENTA_CONCRETE_PIECES;
	public static PieceSet LIGHT_BLUE_CONCRETE_PIECES;
	public static PieceSet YELLOW_CONCRETE_PIECES;
	public static PieceSet LIME_CONCRETE_PIECES;
	public static PieceSet PINK_CONCRETE_PIECES;
	public static PieceSet GRAY_CONCRETE_PIECES;
	public static PieceSet LIGHT_GRAY_CONCRETE_PIECES;
	public static PieceSet CYAN_CONCRETE_PIECES;
	public static PieceSet PURPLE_CONCRETE_PIECES;
	public static PieceSet BLUE_CONCRETE_PIECES;
	public static PieceSet BROWN_CONCRETE_PIECES;
	public static PieceSet GREEN_CONCRETE_PIECES;
	public static PieceSet RED_CONCRETE_PIECES;
	public static PieceSet BLACK_CONCRETE_PIECES;
	public static PieceSet GOLD_PIECES;
	public static PieceSet IRON_PIECES;
	public static PieceSet DIAMOND_PIECES;
	public static PieceSet EMERALD_PIECES;
	public static PieceSet REDSTONE_PIECES;
	public static PieceSet COAL_PIECES;
	public static PieceSet LAPIS_LAZULI_PIECES;
	public static PieceSet PACKED_ICE_PIECES;
	public static PieceSet WHITE_WOOL_PIECES;
	public static PieceSet ORANGE_WOOL_PIECES;
	public static PieceSet MAGENTA_WOOL_PIECES;
	public static PieceSet LIGHT_BLUE_WOOL_PIECES;
	public static PieceSet YELLOW_WOOL_PIECES;
	public static PieceSet LIME_WOOL_PIECES;
	public static PieceSet PINK_WOOL_PIECES;
	public static PieceSet GRAY_WOOL_PIECES;
	public static PieceSet LIGHT_GRAY_WOOL_PIECES;
	public static PieceSet CYAN_WOOL_PIECES;
	public static PieceSet PURPLE_WOOL_PIECES;
	public static PieceSet BLUE_WOOL_PIECES;
	public static PieceSet BROWN_WOOL_PIECES;
	public static PieceSet GREEN_WOOL_PIECES;
	public static PieceSet RED_WOOL_PIECES;
	public static PieceSet BLACK_WOOL_PIECES;
	public static PieceSet WHITE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet ORANGE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet MAGENTA_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet YELLOW_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIME_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet PINK_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet CYAN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet PURPLE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BROWN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet GREEN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet RED_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BLACK_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet OBSIDIAN_PIECES;
	public static PieceSet BONE_PIECES;
	public static PieceSet HAY_PIECES;
	public static PieceSet PUMPKIN_PIECES;
	public static PieceSet MELON_PIECES;
	public static PieceSet SNOW_PIECES;
	public static PieceSet MAGMA_PIECES;
	public static PieceSet GLOWSTONE_PIECES;
	public static PieceSet NETHER_WART_PIECES;
	public static PieceSet BROWN_MUSHROOM_PIECES;
	public static PieceSet RED_MUSHROOM_PIECES;
	public static PieceSet MUSHROOM_STEM_PIECES;
	public static PieceSet DRIED_KELP_PIECES;
	public static PieceSet TUBE_CORAL_PIECES;
	public static PieceSet BRAIN_CORAL_PIECES;
	public static PieceSet BUBBLE_CORAL_PIECES;
	public static PieceSet FIRE_CORAL_PIECES;
	public static PieceSet HORN_CORAL_PIECES;
	public static PieceSet DEAD_TUBE_CORAL_PIECES;
	public static PieceSet DEAD_BRAIN_CORAL_PIECES;
	public static PieceSet DEAD_BUBBLE_CORAL_PIECES;
	public static PieceSet DEAD_FIRE_CORAL_PIECES;
	public static PieceSet DEAD_HORN_CORAL_PIECES;
	public static PieceSet OAK_LOG_PIECES;
	public static PieceSet SPRUCE_LOG_PIECES;
	public static PieceSet BIRCH_LOG_PIECES;
	public static PieceSet JUNGLE_LOG_PIECES;
	public static PieceSet ACACIA_LOG_PIECES;
	public static PieceSet DARK_OAK_LOG_PIECES;
	public static PieceSet STRIPPED_OAK_LOG_PIECES;
	public static PieceSet STRIPPED_SPRUCE_LOG_PIECES;
	public static PieceSet STRIPPED_BIRCH_LOG_PIECES;
	public static PieceSet STRIPPED_JUNGLE_LOG_PIECES;
	public static PieceSet STRIPPED_ACACIA_LOG_PIECES;
	public static PieceSet STRIPPED_DARK_OAK_LOG_PIECES;
	public static PieceSet OAK_WOOD_PIECES;
	public static PieceSet SPRUCE_WOOD_PIECES;
	public static PieceSet BIRCH_WOOD_PIECES;
	public static PieceSet JUNGLE_WOOD_PIECES;
	public static PieceSet ACACIA_WOOD_PIECES;
	public static PieceSet DARK_OAK_WOOD_PIECES;
	public static PieceSet STRIPPED_OAK_WOOD_PIECES;
	public static PieceSet STRIPPED_SPRUCE_WOOD_PIECES;
	public static PieceSet STRIPPED_BIRCH_WOOD_PIECES;
	public static PieceSet STRIPPED_JUNGLE_WOOD_PIECES;
	public static PieceSet STRIPPED_ACACIA_WOOD_PIECES;
	public static PieceSet STRIPPED_DARK_OAK_WOOD_PIECES;

	public static void init() {
		PRISMARINE_PIECES = PieceSet.createSet(Blocks.PRISMARINE, "prismarine", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		PRISMARINE_BRICK_PIECES = PieceSet.createSet(Blocks.PRISMARINE_BRICKS, "prismarine_brick", PieceSet.NO_SLAB_OR_STAIRS).register();
		DARK_PRISMARINE_PIECES = PieceSet.createSet(Blocks.DARK_PRISMARINE, "dark_prismarine", PieceSet.NO_SLAB_OR_STAIRS).register();
		OAK_PIECES = PieceSet.createSet(Blocks.OAK_PLANKS, "oak", PieceSet.JUST_EXTRAS_AND_WALL).register();
		SPRUCE_PIECES = PieceSet.createSet(Blocks.SPRUCE_PLANKS, "spruce", PieceSet.JUST_EXTRAS_AND_WALL).register();
		BIRCH_PIECES = PieceSet.createSet(Blocks.BIRCH_PLANKS, "birch", PieceSet.JUST_EXTRAS_AND_WALL).register();
		JUNGLE_PIECES = PieceSet.createSet(Blocks.JUNGLE_PLANKS, "jungle", PieceSet.JUST_EXTRAS_AND_WALL).register();
		ACACIA_PIECES = PieceSet.createSet(Blocks.ACACIA_PLANKS, "acacia", PieceSet.JUST_EXTRAS_AND_WALL).register();
		DARK_OAK_PIECES = PieceSet.createSet(Blocks.DARK_OAK_PLANKS, "dark_oak", PieceSet.JUST_EXTRAS_AND_WALL).register();
		STONE_PIECES = PieceSet.createSet(Blocks.STONE, "stone", PieceSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_STONE_PIECES = PieceSet.createSet(Blocks.SMOOTH_STONE, "smooth_stone", PieceSet.NO_SLAB).register();
		SANDSTONE_PIECES = PieceSet.createSet(Blocks.SANDSTONE, "sandstone", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		CUT_SANDSTONE_PIECES = PieceSet.createSet(Blocks.CUT_SANDSTONE, "cut_sandstone", PieceSet.NO_SLAB).register();
		PETRIFIED_OAK_PIECES = PieceSet.createSet(Blocks.PETRIFIED_OAK_SLAB, "petrified_oak", PieceType.SIDING).register();
		COBBLESTONE_PIECES = PieceSet.createSet(Blocks.COBBLESTONE, "cobblestone", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		BRICK_PIECES = PieceSet.createSet(Blocks.BRICKS, "brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		STONE_BRICK_PIECES = PieceSet.createSet(Blocks.STONE_BRICKS, "stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		NETHER_BRICK_PIECES = PieceSet.createSet(Blocks.NETHER_BRICKS, "nether_brick", PieceSet.JUST_EXTRAS_AND_FENCE_GATE).register();
		QUARTZ_PIECES = PieceSet.createSet(Blocks.QUARTZ_BLOCK, "quartz", PieceSet.NO_SLAB_OR_STAIRS).register();
		RED_SANDSTONE_PIECES = PieceSet.createSet(Blocks.RED_SANDSTONE, "red_sandstone", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		CUT_RED_SANDSTONE_PIECES = PieceSet.createSet(Blocks.CUT_RED_SANDSTONE, "cut_red_sandstone", PieceSet.NO_SLAB).register();
		PURPUR_PIECES = PieceSet.createSet(Blocks.PURPUR_BLOCK, "purpur", PieceSet.NO_SLAB_OR_STAIRS).register();
		POLISHED_GRANITE_PIECES = PieceSet.createSet(Blocks.POLISHED_GRANITE, "polished_granite", PieceSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_RED_SANDSTONE_PIECES = PieceSet.createSet(Blocks.SMOOTH_RED_SANDSTONE, "smooth_red_sandstone", PieceSet.NO_SLAB_OR_STAIRS).register();
		MOSSY_STONE_BRICK_PIECES = PieceSet.createSet(Blocks.MOSSY_STONE_BRICKS, "mossy_stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		POLISHED_DIORITE_PIECES = PieceSet.createSet(Blocks.POLISHED_DIORITE, "polished_diorite", PieceSet.NO_SLAB_OR_STAIRS).register();
		MOSSY_COBBLESTONE_PIECES = PieceSet.createSet(Blocks.MOSSY_COBBLESTONE, "mossy_cobblestone", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		END_STONE_BRICK_PIECES = PieceSet.createSet(Blocks.END_STONE_BRICKS, "end_stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		SMOOTH_SANDSTONE_PIECES = PieceSet.createSet(Blocks.SMOOTH_SANDSTONE, "smooth_sandstone", PieceSet.NO_SLAB_OR_STAIRS).register();
		SMOOTH_QUARTZ_PIECES = PieceSet.createSet(Blocks.SMOOTH_QUARTZ, "smooth_quartz", PieceSet.NO_SLAB_OR_STAIRS).register();
		GRANITE_PIECES = PieceSet.createSet(Blocks.GRANITE, "granite", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		ANDESITE_PIECES = PieceSet.createSet(Blocks.ANDESITE, "andesite", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		RED_NETHER_BRICK_PIECES = PieceSet.createSet(Blocks.RED_NETHER_BRICKS, "red_nether_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		POLISHED_ANDESITE_PIECES = PieceSet.createSet(Blocks.POLISHED_ANDESITE, "polished_andesite", PieceSet.NO_SLAB_OR_STAIRS).register();
		DIORITE_PIECES = PieceSet.createSet(Blocks.DIORITE, "diorite", PieceSet.NO_SLAB_STAIRS_OR_WALL).register();
		NETHERRACK_PIECES = PieceSet.createSet(Blocks.NETHERRACK, "netherrack").register();
		END_STONE_PIECES = PieceSet.createSet(Blocks.END_STONE, "end_stone").register();
		QUARTZ_PILLAR_PIECES = PieceSet.createSet(Blocks.QUARTZ_PILLAR, "quartz_pillar").register();
		CHISELED_QUARTZ_PIECES = PieceSet.createSet(Blocks.CHISELED_QUARTZ_BLOCK, "chiseled_quartz").register();
		CHISELED_SANDSTONE_PIECES = PieceSet.createSet(Blocks.CHISELED_SANDSTONE, "chiseled_sandstone").register();
		CHISELED_RED_SANDSTONE_PIECES = PieceSet.createSet(Blocks.CHISELED_RED_SANDSTONE, "chiseled_red_sandstone").register();
		CRACKED_STONE_BRICK_PIECES = PieceSet.createSet(Blocks.CRACKED_STONE_BRICKS, "cracked_stone_brick").register();
		CHISELED_STONE_BRICK_PIECES = PieceSet.createSet(Blocks.CHISELED_STONE_BRICKS, "chiseled_stone_brick").register();
		PURPUR_PILLAR_PIECES = PieceSet.createSet(Blocks.PURPUR_PILLAR, "purpur_pillar").register();
		TERRACOTTA_PIECES = PieceSet.createSet(Blocks.TERRACOTTA, "terracotta").register();
		WHITE_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.WHITE_TERRACOTTA, "white_terracotta").register();
		ORANGE_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.ORANGE_TERRACOTTA, "orange_terracotta").register();
		MAGENTA_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.MAGENTA_TERRACOTTA, "magenta_terracotta").register();
		LIGHT_BLUE_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIGHT_BLUE_TERRACOTTA, "light_blue_terracotta").register();
		YELLOW_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.YELLOW_TERRACOTTA, "yellow_terracotta").register();
		LIME_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIME_TERRACOTTA, "lime_terracotta").register();
		PINK_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.PINK_TERRACOTTA, "pink_terracotta").register();
		GRAY_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.GRAY_TERRACOTTA, "gray_terracotta").register();
		LIGHT_GRAY_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIGHT_GRAY_TERRACOTTA, "light_gray_terracotta").register();
		CYAN_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.CYAN_TERRACOTTA, "cyan_terracotta").register();
		PURPLE_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.PURPLE_TERRACOTTA, "purple_terracotta").register();
		BLUE_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BLUE_TERRACOTTA, "blue_terracotta").register();
		BROWN_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BROWN_TERRACOTTA, "brown_terracotta").register();
		GREEN_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.GREEN_TERRACOTTA, "green_terracotta").register();
		RED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.RED_TERRACOTTA, "red_terracotta").register();
		BLACK_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BLACK_TERRACOTTA, "black_terracotta").register();
		WHITE_CONCRETE_PIECES = PieceSet.createSet(Blocks.WHITE_CONCRETE, "white_concrete").register();
		ORANGE_CONCRETE_PIECES = PieceSet.createSet(Blocks.ORANGE_CONCRETE, "orange_concrete").register();
		MAGENTA_CONCRETE_PIECES = PieceSet.createSet(Blocks.MAGENTA_CONCRETE, "magenta_concrete").register();
		LIGHT_BLUE_CONCRETE_PIECES = PieceSet.createSet(Blocks.LIGHT_BLUE_CONCRETE, "light_blue_concrete").register();
		YELLOW_CONCRETE_PIECES = PieceSet.createSet(Blocks.YELLOW_CONCRETE, "yellow_concrete").register();
		LIME_CONCRETE_PIECES = PieceSet.createSet(Blocks.LIME_CONCRETE, "lime_concrete").register();
		PINK_CONCRETE_PIECES = PieceSet.createSet(Blocks.PINK_CONCRETE, "pink_concrete").register();
		GRAY_CONCRETE_PIECES = PieceSet.createSet(Blocks.GRAY_CONCRETE, "gray_concrete").register();
		LIGHT_GRAY_CONCRETE_PIECES = PieceSet.createSet(Blocks.LIGHT_GRAY_CONCRETE, "light_gray_concrete").register();
		CYAN_CONCRETE_PIECES = PieceSet.createSet(Blocks.CYAN_CONCRETE, "cyan_concrete").register();
		PURPLE_CONCRETE_PIECES = PieceSet.createSet(Blocks.PURPLE_CONCRETE, "purple_concrete").register();
		BLUE_CONCRETE_PIECES = PieceSet.createSet(Blocks.BLUE_CONCRETE, "blue_concrete").register();
		BROWN_CONCRETE_PIECES = PieceSet.createSet(Blocks.BROWN_CONCRETE, "brown_concrete").register();
		GREEN_CONCRETE_PIECES = PieceSet.createSet(Blocks.GREEN_CONCRETE, "green_concrete").register();
		RED_CONCRETE_PIECES = PieceSet.createSet(Blocks.RED_CONCRETE, "red_concrete").register();
		BLACK_CONCRETE_PIECES = PieceSet.createSet(Blocks.BLACK_CONCRETE, "black_concrete").register();
		GOLD_PIECES = PieceSet.createSet(Blocks.GOLD_BLOCK, "gold").register();
		IRON_PIECES = PieceSet.createSet(Blocks.IRON_BLOCK, "iron").register();
		DIAMOND_PIECES = PieceSet.createSet(Blocks.DIAMOND_BLOCK, "diamond").register();
		EMERALD_PIECES = PieceSet.createSet(Blocks.EMERALD_BLOCK, "emerald").register();
		REDSTONE_PIECES = PieceSet.createSet(Blocks.REDSTONE_BLOCK, "redstone").register();
		COAL_PIECES = PieceSet.createSet(Blocks.COAL_BLOCK, "coal").register();
		LAPIS_LAZULI_PIECES = PieceSet.createSet(Blocks.LAPIS_BLOCK, "lapis_lazuli").register();
		PACKED_ICE_PIECES = PieceSet.createSet(Blocks.PACKED_ICE, "packed_ice").register();
		WHITE_WOOL_PIECES = PieceSet.createSet(Blocks.WHITE_WOOL, "white_wool").register();
		ORANGE_WOOL_PIECES = PieceSet.createSet(Blocks.ORANGE_WOOL, "orange_wool").register();
		MAGENTA_WOOL_PIECES = PieceSet.createSet(Blocks.MAGENTA_WOOL, "magenta_wool").register();
		LIGHT_BLUE_WOOL_PIECES = PieceSet.createSet(Blocks.LIGHT_BLUE_WOOL, "light_blue_wool").register();
		YELLOW_WOOL_PIECES = PieceSet.createSet(Blocks.YELLOW_WOOL, "yellow_wool").register();
		LIME_WOOL_PIECES = PieceSet.createSet(Blocks.LIME_WOOL, "lime_wool").register();
		PINK_WOOL_PIECES = PieceSet.createSet(Blocks.PINK_WOOL, "pink_wool").register();
		GRAY_WOOL_PIECES = PieceSet.createSet(Blocks.GRAY_WOOL, "gray_wool").register();
		LIGHT_GRAY_WOOL_PIECES = PieceSet.createSet(Blocks.LIGHT_GRAY_WOOL, "light_gray_wool").register();
		CYAN_WOOL_PIECES = PieceSet.createSet(Blocks.CYAN_WOOL, "cyan_wool").register();
		PURPLE_WOOL_PIECES = PieceSet.createSet(Blocks.PURPLE_WOOL, "purple_wool").register();
		BLUE_WOOL_PIECES = PieceSet.createSet(Blocks.BLUE_WOOL, "blue_wool").register();
		BROWN_WOOL_PIECES = PieceSet.createSet(Blocks.BROWN_WOOL, "brown_wool").register();
		GREEN_WOOL_PIECES = PieceSet.createSet(Blocks.GREEN_WOOL, "green_wool").register();
		RED_WOOL_PIECES = PieceSet.createSet(Blocks.RED_WOOL, "red_wool").register();
		BLACK_WOOL_PIECES = PieceSet.createSet(Blocks.BLACK_WOOL, "black_wool").register();
		WHITE_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.WHITE_GLAZED_TERRACOTTA, "white_glazed_terracotta").register();
		ORANGE_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.ORANGE_GLAZED_TERRACOTTA, "orange_glazed_terracotta").register();
		MAGENTA_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.MAGENTA_GLAZED_TERRACOTTA, "magenta_glazed_terracotta").register();
		LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, "light_blue_glazed_terracotta").register();
		YELLOW_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.YELLOW_GLAZED_TERRACOTTA, "yellow_glazed_terracotta").register();
		LIME_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIME_GLAZED_TERRACOTTA, "lime_glazed_terracotta").register();
		PINK_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.PINK_GLAZED_TERRACOTTA, "pink_glazed_terracotta").register();
		GRAY_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.GRAY_GLAZED_TERRACOTTA, "gray_glazed_terracotta").register();
		LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, "light_gray_glazed_terracotta").register();
		CYAN_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.CYAN_GLAZED_TERRACOTTA, "cyan_glazed_terracotta").register();
		PURPLE_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.PURPLE_GLAZED_TERRACOTTA, "purple_glazed_terracotta").register();
		BLUE_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BLUE_GLAZED_TERRACOTTA, "blue_glazed_terracotta").register();
		BROWN_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BROWN_GLAZED_TERRACOTTA, "brown_glazed_terracotta").register();
		GREEN_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.GREEN_GLAZED_TERRACOTTA, "green_glazed_terracotta").register();
		RED_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.RED_GLAZED_TERRACOTTA, "red_glazed_terracotta").register();
		BLACK_GLAZED_TERRACOTTA_PIECES = PieceSet.createSet(Blocks.BLACK_GLAZED_TERRACOTTA, "black_glazed_terracotta").register();
		OBSIDIAN_PIECES = PieceSet.createSet(Blocks.OBSIDIAN, "obsidian").register();
		BONE_PIECES = PieceSet.createSet(Blocks.BONE_BLOCK, "bone").register();
		HAY_PIECES = PieceSet.createSet(Blocks.HAY_BLOCK, "hay").register();
		PUMPKIN_PIECES = PieceSet.createSet(Blocks.PUMPKIN, "pumpkin").register();
		MELON_PIECES = PieceSet.createSet(Blocks.MELON, "melon").register();
		SNOW_PIECES = PieceSet.createSet(Blocks.SNOW_BLOCK, "snow").register();
		MAGMA_PIECES = PieceSet.createSet(Blocks.MAGMA_BLOCK, "magma").register();
		GLOWSTONE_PIECES = PieceSet.createSet(Blocks.GLOWSTONE, "glowstone").register();
		NETHER_WART_PIECES = PieceSet.createSet(Blocks.NETHER_WART_BLOCK, "nether_wart").register();
		BROWN_MUSHROOM_PIECES = PieceSet.createSet(Blocks.BROWN_MUSHROOM_BLOCK, "brown_mushroom").register();
		RED_MUSHROOM_PIECES = PieceSet.createSet(Blocks.RED_MUSHROOM_BLOCK, "red_mushroom").register();
		MUSHROOM_STEM_PIECES = PieceSet.createSet(Blocks.MUSHROOM_STEM, "mushroom_stem").register();
		DRIED_KELP_PIECES = PieceSet.createSet(Blocks.DRIED_KELP_BLOCK, "dried_kelp").register();
		TUBE_CORAL_PIECES = PieceSet.createSet(Blocks.TUBE_CORAL_BLOCK, "tube_coral").register();
		BRAIN_CORAL_PIECES = PieceSet.createSet(Blocks.BRAIN_CORAL_BLOCK, "brain_coral").register();
		BUBBLE_CORAL_PIECES = PieceSet.createSet(Blocks.BUBBLE_CORAL_BLOCK, "bubble_coral").register();
		FIRE_CORAL_PIECES = PieceSet.createSet(Blocks.FIRE_CORAL_BLOCK, "fire_coral").register();
		HORN_CORAL_PIECES = PieceSet.createSet(Blocks.HORN_CORAL_BLOCK, "horn_coral").register();
		DEAD_TUBE_CORAL_PIECES = PieceSet.createSet(Blocks.DEAD_TUBE_CORAL_BLOCK, "dead_tube_coral").register();
		DEAD_BRAIN_CORAL_PIECES = PieceSet.createSet(Blocks.DEAD_BRAIN_CORAL_BLOCK, "dead_brain_coral").register();
		DEAD_BUBBLE_CORAL_PIECES = PieceSet.createSet(Blocks.DEAD_BUBBLE_CORAL, "dead_bubble_coral").register();
		DEAD_FIRE_CORAL_PIECES = PieceSet.createSet(Blocks.DEAD_FIRE_CORAL_BLOCK, "dead_fire_coral").register();
		DEAD_HORN_CORAL_PIECES = PieceSet.createSet(Blocks.DEAD_HORN_CORAL_BLOCK, "dead_horn_coral").register();
		OAK_LOG_PIECES = PieceSet.createSet(Blocks.OAK_LOG, "oak_log").register();
		SPRUCE_LOG_PIECES = PieceSet.createSet(Blocks.SPRUCE_LOG, "spruce_log").register();
		BIRCH_LOG_PIECES = PieceSet.createSet(Blocks.BIRCH_LOG, "birch_log").register();
		JUNGLE_LOG_PIECES = PieceSet.createSet(Blocks.JUNGLE_LOG, "jungle_log").register();
		ACACIA_LOG_PIECES = PieceSet.createSet(Blocks.ACACIA_LOG, "acacia_log").register();
		DARK_OAK_LOG_PIECES = PieceSet.createSet(Blocks.DARK_OAK_LOG, "dark_oak_log").register();
		STRIPPED_OAK_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_OAK_LOG, "stripped_oak_log").register();
		STRIPPED_SPRUCE_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_SPRUCE_LOG, "stripped_spruce_log").register();
		STRIPPED_BIRCH_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_BIRCH_LOG, "stripped_birch_log").register();
		STRIPPED_JUNGLE_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_JUNGLE_LOG, "stripped_jungle_log").register();
		STRIPPED_ACACIA_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_ACACIA_LOG, "stripped_acacia_log").register();
		STRIPPED_DARK_OAK_LOG_PIECES = PieceSet.createSet(Blocks.STRIPPED_DARK_OAK_LOG, "stripped_dark_oak_log").register();
		OAK_WOOD_PIECES = PieceSet.createSet(Blocks.OAK_WOOD, "oak_wood").register();
		SPRUCE_WOOD_PIECES = PieceSet.createSet(Blocks.SPRUCE_WOOD, "spruce_wood").register();
		BIRCH_WOOD_PIECES = PieceSet.createSet(Blocks.BIRCH_WOOD, "birch_wood").register();
		JUNGLE_WOOD_PIECES = PieceSet.createSet(Blocks.JUNGLE_WOOD, "jungle_wood").register();
		ACACIA_WOOD_PIECES = PieceSet.createSet(Blocks.ACACIA_WOOD, "acacia_wood").register();
		DARK_OAK_WOOD_PIECES = PieceSet.createSet(Blocks.DARK_OAK_WOOD, "dark_oak_wood").register();
		STRIPPED_OAK_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_OAK_WOOD, "stripped_oak_wood").register();
		STRIPPED_SPRUCE_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_SPRUCE_WOOD, "stripped_spruce_wood").register();
		STRIPPED_BIRCH_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_BIRCH_WOOD, "stripped_birch_wood").register();
		STRIPPED_JUNGLE_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_JUNGLE_WOOD, "stripped_jungle_wood").register();
		STRIPPED_ACACIA_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_ACACIA_WOOD, "stripped_acacia_wood").register();
		STRIPPED_DARK_OAK_WOOD_PIECES = PieceSet.createSet(Blocks.STRIPPED_DARK_OAK_WOOD, "stripped_dark_oak_wood").register();
	}
}