package com.shnupbups.extrapieces;

import com.google.common.collect.UnmodifiableIterator;
import net.fabricmc.fabric.api.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

import java.util.Iterator;

public class ModBlocks {

	//Sidings for each vanilla slab
	public static Block PRISMARINE_SIDING;
	public static Block PRISMARINE_BRICK_SIDING;
	public static Block DARK_PRISMARINE_SIDING;
	public static Block OAK_SIDING;
	public static Block SPRUCE_SIDING;
	public static Block BIRCH_SIDING;
	public static Block JUNGLE_SIDING;
	public static Block ACACIA_SIDING;
	public static Block DARK_OAK_SIDING;
	public static Block STONE_SIDING;
	public static Block SMOOTH_STONE_SIDING;
	public static Block SANDSTONE_SIDING;
	public static Block CUT_SANDSTONE_SIDING;
	public static Block PETRIFIED_OAK_SIDING;
	public static Block COBBLESTONE_SIDING;
	public static Block BRICK_SIDING;
	public static Block STONE_BRICK_SIDING;
	public static Block NETHER_BRICK_SIDING;
	public static Block QUARTZ_SIDING;
	public static Block RED_SANDSTONE_SIDING;
	public static Block CUT_RED_SANDSTONE_SIDING;
	public static Block PURPUR_SIDING;
	public static Block POLISHED_GRANITE_SIDING;
	public static Block SMOOTH_RED_SANDSTONE_SIDING;
	public static Block MOSSY_STONE_BRICK_SIDING;
	public static Block POLISHED_DIORITE_SIDING;
	public static Block MOSSY_COBBLESTONE_SIDING;
	public static Block END_STONE_BRICK_SIDING;
	public static Block SMOOTH_SANDSTONE_SIDING;
	public static Block SMOOTH_QUARTZ_SIDING;
	public static Block GRANITE_SIDING;
	public static Block ANDESITE_SIDING;
	public static Block RED_NETHER_BRICK_SIDING;
	public static Block POLISHED_ANDESITE_SIDING;
	public static Block DIORITE_SIDING;

	//missing stairs
	public static Block NETHERRACK_STAIRS;
	public static Block END_STONE_STAIRS;
	public static Block QUARTZ_PILLAR_STAIRS;
	public static Block CHISELED_QUARTZ_STAIRS;
	public static Block CHISELED_SANDSTONE_STAIRS;
	public static Block CUT_SANDSTONE_STAIRS;
	public static Block CHISELED_RED_SANDSTONE_STAIRS;
	public static Block CUT_RED_SANDSTONE_STAIRS;
	public static Block CRACKED_STONE_BRICK_STAIRS;
	public static Block CHISELED_STONE_BRICK_STAIRS;
	public static Block PURPUR_PILLAR_STAIRS;
	public static Block SMOOTH_STONE_STAIRS;
	public static Block TERRACOTTA_STAIRS;
	public static Block WHITE_TERRACOTTA_STAIRS;
	public static Block ORANGE_TERRACOTTA_STAIRS;
	public static Block MAGENTA_TERRACOTTA_STAIRS;
	public static Block LIGHT_BLUE_TERRACOTTA_STAIRS;
	public static Block YELLOW_TERRACOTTA_STAIRS;
	public static Block LIME_TERRACOTTA_STAIRS;
	public static Block PINK_TERRACOTTA_STAIRS;
	public static Block GRAY_TERRACOTTA_STAIRS;
	public static Block LIGHT_GRAY_TERRACOTTA_STAIRS;
	public static Block CYAN_TERRACOTTA_STAIRS;
	public static Block PURPLE_TERRACOTTA_STAIRS;
	public static Block BLUE_TERRACOTTA_STAIRS;
	public static Block BROWN_TERRACOTTA_STAIRS;
	public static Block GREEN_TERRACOTTA_STAIRS;
	public static Block RED_TERRACOTTA_STAIRS;
	public static Block BLACK_TERRACOTTA_STAIRS;
	public static Block WHITE_CONCRETE_STAIRS;
	public static Block ORANGE_CONCRETE_STAIRS;
	public static Block MAGENTA_CONCRETE_STAIRS;
	public static Block LIGHT_BLUE_CONCRETE_STAIRS;
	public static Block YELLOW_CONCRETE_STAIRS;
	public static Block LIME_CONCRETE_STAIRS;
	public static Block PINK_CONCRETE_STAIRS;
	public static Block GRAY_CONCRETE_STAIRS;
	public static Block LIGHT_GRAY_CONCRETE_STAIRS;
	public static Block CYAN_CONCRETE_STAIRS;
	public static Block PURPLE_CONCRETE_STAIRS;
	public static Block BLUE_CONCRETE_STAIRS;
	public static Block BROWN_CONCRETE_STAIRS;
	public static Block GREEN_CONCRETE_STAIRS;
	public static Block RED_CONCRETE_STAIRS;
	public static Block BLACK_CONCRETE_STAIRS;
	public static Block GOLD_STAIRS;
	public static Block IRON_STAIRS;
	public static Block DIAMOND_STAIRS;
	public static Block EMERALD_STAIRS;
	public static Block REDSTONE_STAIRS;
	public static Block COAL_STAIRS;
	public static Block LAPIS_LAZULI_STAIRS;
	public static Block PACKED_ICE_STAIRS;
	public static Block WHITE_WOOL_STAIRS;
	public static Block ORANGE_WOOL_STAIRS;
	public static Block MAGENTA_WOOL_STAIRS;
	public static Block LIGHT_BLUE_WOOL_STAIRS;
	public static Block YELLOW_WOOL_STAIRS;
	public static Block LIME_WOOL_STAIRS;
	public static Block PINK_WOOL_STAIRS;
	public static Block GRAY_WOOL_STAIRS;
	public static Block LIGHT_GRAY_WOOL_STAIRS;
	public static Block CYAN_WOOL_STAIRS;
	public static Block PURPLE_WOOL_STAIRS;
	public static Block BLUE_WOOL_STAIRS;
	public static Block BROWN_WOOL_STAIRS;
	public static Block GREEN_WOOL_STAIRS;
	public static Block RED_WOOL_STAIRS;
	public static Block BLACK_WOOL_STAIRS;

	//missing slabs
	public static Block NETHERRACK_SLAB;
	public static Block END_STONE_SLAB;
	public static Block QUARTZ_PILLAR_SLAB;
	public static Block CHISELED_QUARTZ_SLAB;
	public static Block CHISELED_SANDSTONE_SLAB;
	public static Block CHISELED_RED_SANDSTONE_SLAB;
	public static Block CRACKED_STONE_BRICK_SLAB;
	public static Block CHISELED_STONE_BRICK_SLAB;
	public static Block PURPUR_PILLAR_SLAB;
	public static Block TERRACOTTA_SLAB;
	public static Block WHITE_TERRACOTTA_SLAB;
	public static Block ORANGE_TERRACOTTA_SLAB;
	public static Block MAGENTA_TERRACOTTA_SLAB;
	public static Block LIGHT_BLUE_TERRACOTTA_SLAB;
	public static Block YELLOW_TERRACOTTA_SLAB;
	public static Block LIME_TERRACOTTA_SLAB;
	public static Block PINK_TERRACOTTA_SLAB;
	public static Block GRAY_TERRACOTTA_SLAB;
	public static Block LIGHT_GRAY_TERRACOTTA_SLAB;
	public static Block CYAN_TERRACOTTA_SLAB;
	public static Block PURPLE_TERRACOTTA_SLAB;
	public static Block BLUE_TERRACOTTA_SLAB;
	public static Block BROWN_TERRACOTTA_SLAB;
	public static Block GREEN_TERRACOTTA_SLAB;
	public static Block RED_TERRACOTTA_SLAB;
	public static Block BLACK_TERRACOTTA_SLAB;
	public static Block WHITE_CONCRETE_SLAB;
	public static Block ORANGE_CONCRETE_SLAB;
	public static Block MAGENTA_CONCRETE_SLAB;
	public static Block LIGHT_BLUE_CONCRETE_SLAB;
	public static Block YELLOW_CONCRETE_SLAB;
	public static Block LIME_CONCRETE_SLAB;
	public static Block PINK_CONCRETE_SLAB;
	public static Block GRAY_CONCRETE_SLAB;
	public static Block LIGHT_GRAY_CONCRETE_SLAB;
	public static Block CYAN_CONCRETE_SLAB;
	public static Block PURPLE_CONCRETE_SLAB;
	public static Block BLUE_CONCRETE_SLAB;
	public static Block BROWN_CONCRETE_SLAB;
	public static Block GREEN_CONCRETE_SLAB;
	public static Block RED_CONCRETE_SLAB;
	public static Block BLACK_CONCRETE_SLAB;
	public static Block GOLD_SLAB;
	public static Block IRON_SLAB;
	public static Block DIAMOND_SLAB;
	public static Block EMERALD_SLAB;
	public static Block REDSTONE_SLAB;
	public static Block COAL_SLAB;
	public static Block LAPIS_LAZULI_SLAB;
	public static Block PACKED_ICE_SLAB;
	public static Block WHITE_WOOL_SLAB;
	public static Block ORANGE_WOOL_SLAB;
	public static Block MAGENTA_WOOL_SLAB;
	public static Block LIGHT_BLUE_WOOL_SLAB;
	public static Block YELLOW_WOOL_SLAB;
	public static Block LIME_WOOL_SLAB;
	public static Block PINK_WOOL_SLAB;
	public static Block GRAY_WOOL_SLAB;
	public static Block LIGHT_GRAY_WOOL_SLAB;
	public static Block CYAN_WOOL_SLAB;
	public static Block PURPLE_WOOL_SLAB;
	public static Block BLUE_WOOL_SLAB;
	public static Block BROWN_WOOL_SLAB;
	public static Block GREEN_WOOL_SLAB;
	public static Block RED_WOOL_SLAB;
	public static Block BLACK_WOOL_SLAB;

	//missing sidings
	public static Block NETHERRACK_SIDING;
	public static Block END_STONE_SIDING;
	public static Block QUARTZ_PILLAR_SIDING;
	public static Block CHISELED_QUARTZ_SIDING;
	public static Block CHISELED_SANDSTONE_SIDING;
	public static Block CHISELED_RED_SANDSTONE_SIDING;
	public static Block CRACKED_STONE_BRICK_SIDING;
	public static Block CHISELED_STONE_BRICK_SIDING;
	public static Block PURPUR_PILLAR_SIDING;
	public static Block TERRACOTTA_SIDING;
	public static Block WHITE_TERRACOTTA_SIDING;
	public static Block ORANGE_TERRACOTTA_SIDING;
	public static Block MAGENTA_TERRACOTTA_SIDING;
	public static Block LIGHT_BLUE_TERRACOTTA_SIDING;
	public static Block YELLOW_TERRACOTTA_SIDING;
	public static Block LIME_TERRACOTTA_SIDING;
	public static Block PINK_TERRACOTTA_SIDING;
	public static Block GRAY_TERRACOTTA_SIDING;
	public static Block LIGHT_GRAY_TERRACOTTA_SIDING;
	public static Block CYAN_TERRACOTTA_SIDING;
	public static Block PURPLE_TERRACOTTA_SIDING;
	public static Block BLUE_TERRACOTTA_SIDING;
	public static Block BROWN_TERRACOTTA_SIDING;
	public static Block GREEN_TERRACOTTA_SIDING;
	public static Block RED_TERRACOTTA_SIDING;
	public static Block BLACK_TERRACOTTA_SIDING;
	public static Block WHITE_CONCRETE_SIDING;
	public static Block ORANGE_CONCRETE_SIDING;
	public static Block MAGENTA_CONCRETE_SIDING;
	public static Block LIGHT_BLUE_CONCRETE_SIDING;
	public static Block YELLOW_CONCRETE_SIDING;
	public static Block LIME_CONCRETE_SIDING;
	public static Block PINK_CONCRETE_SIDING;
	public static Block GRAY_CONCRETE_SIDING;
	public static Block LIGHT_GRAY_CONCRETE_SIDING;
	public static Block CYAN_CONCRETE_SIDING;
	public static Block PURPLE_CONCRETE_SIDING;
	public static Block BLUE_CONCRETE_SIDING;
	public static Block BROWN_CONCRETE_SIDING;
	public static Block GREEN_CONCRETE_SIDING;
	public static Block RED_CONCRETE_SIDING;
	public static Block BLACK_CONCRETE_SIDING;
	public static Block GOLD_SIDING;
	public static Block IRON_SIDING;
	public static Block DIAMOND_SIDING;
	public static Block EMERALD_SIDING;
	public static Block REDSTONE_SIDING;
	public static Block COAL_SIDING;
	public static Block LAPIS_LAZULI_SIDING;
	public static Block PACKED_ICE_SIDING;
	public static Block WHITE_WOOL_SIDING;
	public static Block ORANGE_WOOL_SIDING;
	public static Block MAGENTA_WOOL_SIDING;
	public static Block LIGHT_BLUE_WOOL_SIDING;
	public static Block YELLOW_WOOL_SIDING;
	public static Block LIME_WOOL_SIDING;
	public static Block PINK_WOOL_SIDING;
	public static Block GRAY_WOOL_SIDING;
	public static Block LIGHT_GRAY_WOOL_SIDING;
	public static Block CYAN_WOOL_SIDING;
	public static Block PURPLE_WOOL_SIDING;
	public static Block BLUE_WOOL_SIDING;
	public static Block BROWN_WOOL_SIDING;
	public static Block GREEN_WOOL_SIDING;
	public static Block RED_WOOL_SIDING;
	public static Block BLACK_WOOL_SIDING;

	//missing walls
	public static Block NETHERRACK_WALL;
	public static Block END_STONE_WALL;
	public static Block STONE_WALL;
	public static Block SMOOTH_SANDSTONE_WALL;
	public static Block SMOOTH_RED_SANDSTONE_WALL;
	public static Block POLISHED_GRANITE_WALL;
	public static Block POLISHED_ANDESITE_WALL;
	public static Block POLISHED_DIORITE_WALL;
	public static Block QUARTZ_WALL;
	public static Block SMOOTH_QUARTZ_WALL;
	public static Block PURPUR_WALL;
	public static Block PRISMARINE_BRICK_WALL;
	public static Block DARK_PRISMARINE_WALL;
	public static Block QUARTZ_PILLAR_WALL;
	public static Block CHISELED_QUARTZ_WALL;
	public static Block CHISELED_SANDSTONE_WALL;
	public static Block CUT_SANDSTONE_WALL;
	public static Block CHISELED_RED_SANDSTONE_WALL;
	public static Block CUT_RED_SANDSTONE_WALL;
	public static Block CRACKED_STONE_BRICK_WALL;
	public static Block CHISELED_STONE_BRICK_WALL;
	public static Block PURPUR_PILLAR_WALL;
	public static Block SMOOTH_STONE_WALL;
	public static Block TERRACOTTA_WALL;
	public static Block WHITE_TERRACOTTA_WALL;
	public static Block ORANGE_TERRACOTTA_WALL;
	public static Block MAGENTA_TERRACOTTA_WALL;
	public static Block LIGHT_BLUE_TERRACOTTA_WALL;
	public static Block YELLOW_TERRACOTTA_WALL;
	public static Block LIME_TERRACOTTA_WALL;
	public static Block PINK_TERRACOTTA_WALL;
	public static Block GRAY_TERRACOTTA_WALL;
	public static Block LIGHT_GRAY_TERRACOTTA_WALL;
	public static Block CYAN_TERRACOTTA_WALL;
	public static Block PURPLE_TERRACOTTA_WALL;
	public static Block BLUE_TERRACOTTA_WALL;
	public static Block BROWN_TERRACOTTA_WALL;
	public static Block GREEN_TERRACOTTA_WALL;
	public static Block RED_TERRACOTTA_WALL;
	public static Block BLACK_TERRACOTTA_WALL;
	public static Block WHITE_CONCRETE_WALL;
	public static Block ORANGE_CONCRETE_WALL;
	public static Block MAGENTA_CONCRETE_WALL;
	public static Block LIGHT_BLUE_CONCRETE_WALL;
	public static Block YELLOW_CONCRETE_WALL;
	public static Block LIME_CONCRETE_WALL;
	public static Block PINK_CONCRETE_WALL;
	public static Block GRAY_CONCRETE_WALL;
	public static Block LIGHT_GRAY_CONCRETE_WALL;
	public static Block CYAN_CONCRETE_WALL;
	public static Block PURPLE_CONCRETE_WALL;
	public static Block BLUE_CONCRETE_WALL;
	public static Block BROWN_CONCRETE_WALL;
	public static Block GREEN_CONCRETE_WALL;
	public static Block RED_CONCRETE_WALL;
	public static Block BLACK_CONCRETE_WALL;
	public static Block GOLD_WALL;
	public static Block IRON_WALL;
	public static Block DIAMOND_WALL;
	public static Block EMERALD_WALL;
	public static Block REDSTONE_WALL;
	public static Block COAL_WALL;
	public static Block LAPIS_LAZULI_WALL;
	public static Block PACKED_ICE_WALL;
	public static Block WHITE_WOOL_WALL;
	public static Block ORANGE_WOOL_WALL;
	public static Block MAGENTA_WOOL_WALL;
	public static Block LIGHT_BLUE_WOOL_WALL;
	public static Block YELLOW_WOOL_WALL;
	public static Block LIME_WOOL_WALL;
	public static Block PINK_WOOL_WALL;
	public static Block GRAY_WOOL_WALL;
	public static Block LIGHT_GRAY_WOOL_WALL;
	public static Block CYAN_WOOL_WALL;
	public static Block PURPLE_WOOL_WALL;
	public static Block BLUE_WOOL_WALL;
	public static Block BROWN_WOOL_WALL;
	public static Block GREEN_WOOL_WALL;
	public static Block RED_WOOL_WALL;
	public static Block BLACK_WOOL_WALL;

	//missing fences
	public static Block RED_NETHER_BRICK_FENCE;

	private static Block register(String string_1, Block block_1) {
		return (Block) Registry.register(Registry.BLOCK, new Identifier("extrapieces",(String)string_1), block_1);
	}

	public static void init() {
		PRISMARINE_SIDING 			= register("prismarine_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.CYAN).strength(1.5F, 6.0F)));
		PRISMARINE_BRICK_SIDING 	= register("prismarine_brick_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.DIAMOND).strength(1.5F, 6.0F)));
		DARK_PRISMARINE_SIDING 		= register("dark_prismarine_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.DIAMOND).strength(1.5F, 6.0F)));
		OAK_SIDING 					= register("oak_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		SPRUCE_SIDING 				= register("spruce_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.SPRUCE).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		BIRCH_SIDING 				= register("birch_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.SAND).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		JUNGLE_SIDING 				= register("jungle_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.DIRT).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		ACACIA_SIDING 				= register("acacia_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.ORANGE).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		DARK_OAK_SIDING 			= register("dark_oak_siding", new SidingBlock(FabricBlockSettings.of(Material.WOOD, MaterialColor.BROWN).strength(2.0F, 3.0F).sounds(BlockSoundGroup.WOOD).build()));
		STONE_SIDING 				= register("stone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 6.0F)));
		SMOOTH_STONE_SIDING 		= register("smooth_stone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 6.0F)));
		SANDSTONE_SIDING 			= register("sandstone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.SAND).strength(2.0F, 6.0F)));
		CUT_SANDSTONE_SIDING 		= register("cut_sandstone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.SAND).strength(2.0F, 6.0F)));
		PETRIFIED_OAK_SIDING 		= register("petrified_oak_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.WOOD).strength(2.0F, 6.0F)));
		COBBLESTONE_SIDING 			= register("cobblestone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 6.0F)));
		BRICK_SIDING 				= register("brick_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.RED).strength(2.0F, 6.0F)));
		STONE_BRICK_SIDING 			= register("stone_brick_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.STONE).strength(2.0F, 6.0F)));
		NETHER_BRICK_SIDING 		= register("nether_brick_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.NETHER).strength(2.0F, 6.0F)));
		QUARTZ_SIDING 				= register("quartz_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.QUARTZ).strength(2.0F, 6.0F)));
		RED_SANDSTONE_SIDING 		= register("red_sandstone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.ORANGE).strength(2.0F, 6.0F)));
		CUT_RED_SANDSTONE_SIDING 	= register("cut_red_sandstone_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.ORANGE).strength(2.0F, 6.0F)));
		PURPUR_SIDING 				= register("purpur_siding", new SidingBlock(Block.Settings.of(Material.STONE, MaterialColor.MAGENTA).strength(2.0F, 6.0F)));
		POLISHED_GRANITE_SIDING 	= register("polished_granite_siding", new SidingBlock(Block.Settings.copy(Blocks.POLISHED_GRANITE)));
		SMOOTH_RED_SANDSTONE_SIDING = register("smooth_red_sandstone_siding", new SidingBlock(Block.Settings.copy(Blocks.SMOOTH_RED_SANDSTONE)));
		MOSSY_STONE_BRICK_SIDING 	= register("mossy_stone_brick_siding", new SidingBlock(Block.Settings.copy(Blocks.MOSSY_STONE_BRICKS)));
		POLISHED_DIORITE_SIDING 	= register("polished_diorite_siding", new SidingBlock(Block.Settings.copy(Blocks.POLISHED_DIORITE)));
		MOSSY_COBBLESTONE_SIDING 	= register("mossy_cobblestone_siding", new SidingBlock(Block.Settings.copy(Blocks.MOSSY_COBBLESTONE)));
		END_STONE_BRICK_SIDING 		= register("end_stone_brick_siding", new SidingBlock(Block.Settings.copy(Blocks.END_STONE_BRICKS)));
		SMOOTH_SANDSTONE_SIDING 	= register("smooth_sandstone_siding", new SidingBlock(Block.Settings.copy(Blocks.SMOOTH_SANDSTONE)));
		SMOOTH_QUARTZ_SIDING 		= register("smooth_quartz_siding", new SidingBlock(Block.Settings.copy(Blocks.SMOOTH_QUARTZ)));
		GRANITE_SIDING 				= register("granite_siding", new SidingBlock(Block.Settings.copy(Blocks.GRANITE)));
		ANDESITE_SIDING 			= register("andesite_siding", new SidingBlock(Block.Settings.copy(Blocks.ANDESITE)));
		RED_NETHER_BRICK_SIDING 	= register("red_nether_brick_siding", new SidingBlock(Block.Settings.copy(Blocks.RED_NETHER_BRICKS)));
		POLISHED_ANDESITE_SIDING 	= register("polished_andesite_siding", new SidingBlock(Block.Settings.copy(Blocks.POLISHED_ANDESITE)));
		DIORITE_SIDING 				= register("diorite_siding", new SidingBlock(Block.Settings.copy(Blocks.DIORITE)));

		NETHERRACK_STAIRS 				= register("netherrack_stairs", new StairsBlock(Blocks.NETHERRACK.getDefaultState(),Block.Settings.copy(Blocks.NETHERRACK)));
		END_STONE_STAIRS 				= register("end_stone_stairs", new StairsBlock(Blocks.END_STONE.getDefaultState(),Block.Settings.copy(Blocks.END_STONE)));
		QUARTZ_PILLAR_STAIRS 			= register("quartz_pillar_stairs", new StairsBlock(Blocks.QUARTZ_PILLAR.getDefaultState(),Block.Settings.copy(Blocks.QUARTZ_PILLAR)));
		CHISELED_QUARTZ_STAIRS 			= register("chiseled_quartz_stairs", new StairsBlock(Blocks.CHISELED_QUARTZ_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.CHISELED_QUARTZ_BLOCK)));
		CHISELED_SANDSTONE_STAIRS 		= register("chiseled_sandstone_stairs", new StairsBlock(Blocks.CHISELED_SANDSTONE.getDefaultState(),Block.Settings.copy(Blocks.CHISELED_SANDSTONE)));
		CUT_SANDSTONE_STAIRS 			= register("cut_sandstone_stairs", new StairsBlock(Blocks.CUT_SANDSTONE.getDefaultState(),Block.Settings.copy(Blocks.CUT_SANDSTONE)));
		CHISELED_RED_SANDSTONE_STAIRS 	= register("chiseled_red_sandstone_stairs", new StairsBlock(Blocks.CHISELED_RED_SANDSTONE.getDefaultState(),Block.Settings.copy(Blocks.CHISELED_RED_SANDSTONE)));
		CUT_RED_SANDSTONE_STAIRS 		= register("cut_red_sandstone_stairs", new StairsBlock(Blocks.CUT_RED_SANDSTONE.getDefaultState(),Block.Settings.copy(Blocks.CUT_RED_SANDSTONE)));
		CRACKED_STONE_BRICK_STAIRS 		= register("cracked_stone_brick_stairs", new StairsBlock(Blocks.CRACKED_STONE_BRICKS.getDefaultState(),Block.Settings.copy(Blocks.CRACKED_STONE_BRICKS)));
		CHISELED_STONE_BRICK_STAIRS 	= register("chiseled_stone_brick_stairs", new StairsBlock(Blocks.CHISELED_STONE_BRICKS.getDefaultState(),Block.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
		PURPUR_PILLAR_STAIRS 			= register("purpur_pillar_stairs", new StairsBlock(Blocks.PURPUR_PILLAR.getDefaultState(),Block.Settings.copy(Blocks.PURPUR_PILLAR)));
		SMOOTH_STONE_STAIRS 			= register("smooth_stone_stairs", new StairsBlock(Blocks.SMOOTH_STONE.getDefaultState(),Block.Settings.copy(Blocks.SMOOTH_STONE)));
		TERRACOTTA_STAIRS 				= register("terracotta_stairs", new StairsBlock(Blocks.TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.TERRACOTTA)));
		WHITE_TERRACOTTA_STAIRS 		= register("white_terracotta_stairs", new StairsBlock(Blocks.WHITE_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.WHITE_TERRACOTTA)));
		ORANGE_TERRACOTTA_STAIRS 		= register("orange_terracotta_stairs", new StairsBlock(Blocks.ORANGE_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.ORANGE_TERRACOTTA)));
		MAGENTA_TERRACOTTA_STAIRS 		= register("magenta_terracotta_stairs", new StairsBlock(Blocks.MAGENTA_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.MAGENTA_TERRACOTTA)));
		LIGHT_BLUE_TERRACOTTA_STAIRS	= register("light_blue_terracotta_stairs", new StairsBlock(Blocks.LIGHT_BLUE_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
		YELLOW_TERRACOTTA_STAIRS 		= register("yellow_terracotta_stairs", new StairsBlock(Blocks.YELLOW_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.YELLOW_TERRACOTTA)));
		LIME_TERRACOTTA_STAIRS 			= register("lime_terracotta_stairs", new StairsBlock(Blocks.LIME_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.LIME_TERRACOTTA)));
		PINK_TERRACOTTA_STAIRS 			= register("pink_terracotta_stairs", new StairsBlock(Blocks.PINK_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.PINK_TERRACOTTA)));
		GRAY_TERRACOTTA_STAIRS 			= register("gray_terracotta_stairs", new StairsBlock(Blocks.GRAY_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.GRAY_TERRACOTTA)));
		LIGHT_GRAY_TERRACOTTA_STAIRS 	= register("light_gray_terracotta_stairs", new StairsBlock(Blocks.LIGHT_GRAY_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
		CYAN_TERRACOTTA_STAIRS 			= register("cyan_terracotta_stairs", new StairsBlock(Blocks.CYAN_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.CYAN_TERRACOTTA)));
		PURPLE_TERRACOTTA_STAIRS 		= register("purple_terracotta_stairs", new StairsBlock(Blocks.PURPLE_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.PURPLE_TERRACOTTA)));
		BLUE_TERRACOTTA_STAIRS 			= register("blue_terracotta_stairs", new StairsBlock(Blocks.BLUE_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.BLUE_TERRACOTTA)));
		BROWN_TERRACOTTA_STAIRS 		= register("brown_terracotta_stairs", new StairsBlock(Blocks.BROWN_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.BROWN_TERRACOTTA)));
		GREEN_TERRACOTTA_STAIRS 		= register("green_terracotta_stairs", new StairsBlock(Blocks.GREEN_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.GREEN_TERRACOTTA)));
		RED_TERRACOTTA_STAIRS 			= register("red_terracotta_stairs", new StairsBlock(Blocks.RED_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.RED_TERRACOTTA)));
		BLACK_TERRACOTTA_STAIRS 		= register("black_terracotta_stairs", new StairsBlock(Blocks.BLACK_TERRACOTTA.getDefaultState(),Block.Settings.copy(Blocks.BLACK_TERRACOTTA)));
		WHITE_CONCRETE_STAIRS 			= register("white_concrete_stairs", new StairsBlock(Blocks.WHITE_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.WHITE_CONCRETE)));
		ORANGE_CONCRETE_STAIRS 			= register("orange_concrete_stairs", new StairsBlock(Blocks.ORANGE_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.ORANGE_CONCRETE)));
		MAGENTA_CONCRETE_STAIRS 		= register("magenta_concrete_stairs", new StairsBlock(Blocks.MAGENTA_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.MAGENTA_CONCRETE)));
		LIGHT_BLUE_CONCRETE_STAIRS 		= register("light_blue_concrete_stairs", new StairsBlock(Blocks.LIGHT_BLUE_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_BLUE_CONCRETE)));
		YELLOW_CONCRETE_STAIRS 			= register("yellow_concrete_stairs", new StairsBlock(Blocks.YELLOW_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.YELLOW_CONCRETE)));
		LIME_CONCRETE_STAIRS 			= register("lime_concrete_stairs", new StairsBlock(Blocks.LIME_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.LIME_CONCRETE)));
		PINK_CONCRETE_STAIRS 			= register("pink_concrete_stairs", new StairsBlock(Blocks.PINK_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.PINK_CONCRETE)));
		GRAY_CONCRETE_STAIRS 			= register("gray_concrete_stairs", new StairsBlock(Blocks.GRAY_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.GRAY_CONCRETE)));
		LIGHT_GRAY_CONCRETE_STAIRS 		= register("light_gray_concrete_stairs", new StairsBlock(Blocks.LIGHT_GRAY_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_GRAY_CONCRETE)));
		CYAN_CONCRETE_STAIRS 			= register("cyan_concrete_stairs", new StairsBlock(Blocks.CYAN_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.CYAN_CONCRETE)));
		PURPLE_CONCRETE_STAIRS 			= register("purple_concrete_stairs", new StairsBlock(Blocks.PURPLE_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.PURPLE_CONCRETE)));
		BLUE_CONCRETE_STAIRS 			= register("blue_concrete_stairs", new StairsBlock(Blocks.BLUE_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.BLUE_CONCRETE)));
		BROWN_CONCRETE_STAIRS 			= register("brown_concrete_stairs", new StairsBlock(Blocks.BROWN_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.BROWN_CONCRETE)));
		GREEN_CONCRETE_STAIRS 			= register("green_concrete_stairs", new StairsBlock(Blocks.GREEN_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.GREEN_CONCRETE)));
		RED_CONCRETE_STAIRS 			= register("red_concrete_stairs", new StairsBlock(Blocks.RED_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.RED_CONCRETE)));
		BLACK_CONCRETE_STAIRS 			= register("black_concrete_stairs", new StairsBlock(Blocks.BLACK_CONCRETE.getDefaultState(),Block.Settings.copy(Blocks.BLACK_CONCRETE)));
		GOLD_STAIRS 					= register("gold_stairs", new StairsBlock(Blocks.GOLD_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.GOLD_BLOCK)));
		IRON_STAIRS 					= register("iron_stairs", new StairsBlock(Blocks.IRON_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.IRON_BLOCK)));
		DIAMOND_STAIRS 					= register("diamond_stairs", new StairsBlock(Blocks.DIAMOND_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.DIAMOND_BLOCK)));
		EMERALD_STAIRS 					= register("emerald_stairs", new StairsBlock(Blocks.EMERALD_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.EMERALD_BLOCK)));
		REDSTONE_STAIRS 				= register("redstone_stairs", new StairsBlock(Blocks.REDSTONE_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.REDSTONE_BLOCK)));
		COAL_STAIRS 					= register("coal_stairs", new StairsBlock(Blocks.COAL_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.COAL_BLOCK)));
		LAPIS_LAZULI_STAIRS 			= register("lapis_lazuli_stairs", new StairsBlock(Blocks.LAPIS_BLOCK.getDefaultState(),Block.Settings.copy(Blocks.LAPIS_BLOCK)));
		PACKED_ICE_STAIRS 				= register("packed_ice_stairs", new StairsBlock(Blocks.PACKED_ICE.getDefaultState(),Block.Settings.copy(Blocks.PACKED_ICE)));
		WHITE_WOOL_STAIRS 				= register("white_wool_stairs", new StairsBlock(Blocks.WHITE_WOOL.getDefaultState(),Block.Settings.copy(Blocks.WHITE_WOOL)));
		ORANGE_WOOL_STAIRS 				= register("orange_wool_stairs", new StairsBlock(Blocks.ORANGE_WOOL.getDefaultState(),Block.Settings.copy(Blocks.ORANGE_WOOL)));
		MAGENTA_WOOL_STAIRS 			= register("magenta_wool_stairs", new StairsBlock(Blocks.MAGENTA_WOOL.getDefaultState(),Block.Settings.copy(Blocks.MAGENTA_WOOL)));
		LIGHT_BLUE_WOOL_STAIRS 			= register("light_blue_wool_stairs", new StairsBlock(Blocks.LIGHT_BLUE_WOOL.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_BLUE_WOOL)));
		YELLOW_WOOL_STAIRS 				= register("yellow_wool_stairs", new StairsBlock(Blocks.YELLOW_WOOL.getDefaultState(),Block.Settings.copy(Blocks.YELLOW_WOOL)));
		LIME_WOOL_STAIRS 				= register("lime_wool_stairs", new StairsBlock(Blocks.LIME_WOOL.getDefaultState(),Block.Settings.copy(Blocks.LIME_WOOL)));
		PINK_WOOL_STAIRS 				= register("pink_wool_stairs", new StairsBlock(Blocks.PINK_WOOL.getDefaultState(),Block.Settings.copy(Blocks.PINK_WOOL)));
		GRAY_WOOL_STAIRS 				= register("gray_wool_stairs", new StairsBlock(Blocks.GRAY_WOOL.getDefaultState(),Block.Settings.copy(Blocks.GRAY_WOOL)));
		LIGHT_GRAY_WOOL_STAIRS 			= register("light_gray_wool_stairs", new StairsBlock(Blocks.LIGHT_GRAY_WOOL.getDefaultState(),Block.Settings.copy(Blocks.LIGHT_GRAY_WOOL)));
		CYAN_WOOL_STAIRS 				= register("cyan_wool_stairs", new StairsBlock(Blocks.CYAN_WOOL.getDefaultState(),Block.Settings.copy(Blocks.CYAN_WOOL)));
		PURPLE_WOOL_STAIRS 				= register("purple_wool_stairs", new StairsBlock(Blocks.PURPLE_WOOL.getDefaultState(),Block.Settings.copy(Blocks.PURPLE_WOOL)));
		BLUE_WOOL_STAIRS 				= register("blue_wool_stairs", new StairsBlock(Blocks.BLUE_WOOL.getDefaultState(),Block.Settings.copy(Blocks.BLUE_WOOL)));
		BROWN_WOOL_STAIRS 				= register("brown_wool_stairs", new StairsBlock(Blocks.BROWN_WOOL.getDefaultState(),Block.Settings.copy(Blocks.BROWN_WOOL)));
		GREEN_WOOL_STAIRS 				= register("green_wool_stairs", new StairsBlock(Blocks.GREEN_WOOL.getDefaultState(),Block.Settings.copy(Blocks.GREEN_WOOL)));
		RED_WOOL_STAIRS 				= register("red_wool_stairs", new StairsBlock(Blocks.RED_WOOL.getDefaultState(),Block.Settings.copy(Blocks.RED_WOOL)));
		BLACK_WOOL_STAIRS 				= register("black_wool_stairs", new StairsBlock(Blocks.BLACK_WOOL.getDefaultState(),Block.Settings.copy(Blocks.BLACK_WOOL)));

		NETHERRACK_SLAB 			= register("netherrack_slab", new SlabBlock(Block.Settings.copy(Blocks.NETHERRACK)));
		END_STONE_SLAB 				= register("end_stone_slab", new SlabBlock(Block.Settings.copy(Blocks.END_STONE)));
		QUARTZ_PILLAR_SLAB 			= register("quartz_pillar_slab", new SlabBlock(Block.Settings.copy(Blocks.QUARTZ_PILLAR)));
		CHISELED_QUARTZ_SLAB 		= register("chiseled_quartz_slab", new SlabBlock(Block.Settings.copy(Blocks.CHISELED_QUARTZ_BLOCK)));
		CHISELED_SANDSTONE_SLAB 	= register("chiseled_sandstone_slab", new SlabBlock(Block.Settings.copy(Blocks.CHISELED_SANDSTONE)));
		CHISELED_RED_SANDSTONE_SLAB = register("chiseled_red_sandstone_slab", new SlabBlock(Block.Settings.copy(Blocks.CHISELED_RED_SANDSTONE)));
		CRACKED_STONE_BRICK_SLAB 	= register("cracked_stone_brick_slab", new SlabBlock(Block.Settings.copy(Blocks.CRACKED_STONE_BRICKS)));
		CHISELED_STONE_BRICK_SLAB 	= register("chiseled_stone_brick_slab", new SlabBlock(Block.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
		PURPUR_PILLAR_SLAB 			= register("purpur_pillar_slab", new SlabBlock(Block.Settings.copy(Blocks.PURPUR_PILLAR)));
		TERRACOTTA_SLAB 			= register("terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.TERRACOTTA)));
		WHITE_TERRACOTTA_SLAB 		= register("white_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.WHITE_TERRACOTTA)));
		ORANGE_TERRACOTTA_SLAB 		= register("orange_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.ORANGE_TERRACOTTA)));
		MAGENTA_TERRACOTTA_SLAB 	= register("magenta_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.MAGENTA_TERRACOTTA)));
		LIGHT_BLUE_TERRACOTTA_SLAB 	= register("light_blue_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
		YELLOW_TERRACOTTA_SLAB 		= register("yellow_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.YELLOW_TERRACOTTA)));
		LIME_TERRACOTTA_SLAB 		= register("lime_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.LIME_TERRACOTTA)));
		PINK_TERRACOTTA_SLAB 		= register("pink_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.PINK_TERRACOTTA)));
		GRAY_TERRACOTTA_SLAB 		= register("gray_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.GRAY_TERRACOTTA)));
		LIGHT_GRAY_TERRACOTTA_SLAB 	= register("light_gray_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
		CYAN_TERRACOTTA_SLAB 		= register("cyan_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.CYAN_TERRACOTTA)));
		PURPLE_TERRACOTTA_SLAB 		= register("purple_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.PURPLE_TERRACOTTA)));
		BLUE_TERRACOTTA_SLAB 		= register("blue_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.BLUE_TERRACOTTA)));
		BROWN_TERRACOTTA_SLAB 		= register("brown_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.BROWN_TERRACOTTA)));
		GREEN_TERRACOTTA_SLAB 		= register("green_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.GREEN_TERRACOTTA)));
		RED_TERRACOTTA_SLAB 		= register("red_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.RED_TERRACOTTA)));
		BLACK_TERRACOTTA_SLAB 		= register("black_terracotta_slab", new SlabBlock(Block.Settings.copy(Blocks.BLACK_TERRACOTTA)));
		WHITE_CONCRETE_SLAB 		= register("white_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.WHITE_CONCRETE)));
		ORANGE_CONCRETE_SLAB 		= register("orange_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.ORANGE_CONCRETE)));
		MAGENTA_CONCRETE_SLAB 		= register("magenta_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.MAGENTA_CONCRETE)));
		LIGHT_BLUE_CONCRETE_SLAB 	= register("light_blue_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_CONCRETE)));
		YELLOW_CONCRETE_SLAB 		= register("yellow_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.YELLOW_CONCRETE)));
		LIME_CONCRETE_SLAB 			= register("lime_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.LIME_CONCRETE)));
		PINK_CONCRETE_SLAB 			= register("pink_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.PINK_CONCRETE)));
		GRAY_CONCRETE_SLAB 			= register("gray_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.GRAY_CONCRETE)));
		LIGHT_GRAY_CONCRETE_SLAB 	= register("light_gray_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_CONCRETE)));
		CYAN_CONCRETE_SLAB 			= register("cyan_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.CYAN_CONCRETE)));
		PURPLE_CONCRETE_SLAB 		= register("purple_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.PURPLE_CONCRETE)));
		BLUE_CONCRETE_SLAB 			= register("blue_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.BLUE_CONCRETE)));
		BROWN_CONCRETE_SLAB 		= register("brown_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.BROWN_CONCRETE)));
		GREEN_CONCRETE_SLAB 		= register("green_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.GREEN_CONCRETE)));
		RED_CONCRETE_SLAB 			= register("red_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.RED_CONCRETE)));
		BLACK_CONCRETE_SLAB 		= register("black_concrete_slab", new SlabBlock(Block.Settings.copy(Blocks.BLACK_CONCRETE)));
		GOLD_SLAB 					= register("gold_slab", new SlabBlock(Block.Settings.copy(Blocks.GOLD_BLOCK)));
		IRON_SLAB 					= register("iron_slab", new SlabBlock(Block.Settings.copy(Blocks.IRON_BLOCK)));
		DIAMOND_SLAB 				= register("diamond_slab", new SlabBlock(Block.Settings.copy(Blocks.DIAMOND_BLOCK)));
		EMERALD_SLAB 				= register("emerald_slab", new SlabBlock(Block.Settings.copy(Blocks.EMERALD_BLOCK)));
		REDSTONE_SLAB 				= register("redstone_slab", new SlabBlock(Block.Settings.copy(Blocks.REDSTONE_BLOCK)));
		COAL_SLAB 					= register("coal_slab", new SlabBlock(Block.Settings.copy(Blocks.COAL_BLOCK)));
		LAPIS_LAZULI_SLAB 			= register("lapis_lazuli_slab", new SlabBlock(Block.Settings.copy(Blocks.LAPIS_BLOCK)));
		PACKED_ICE_SLAB 			= register("packed_ice_slab", new SlabBlock(Block.Settings.copy(Blocks.PACKED_ICE)));
		WHITE_WOOL_SLAB 			= register("white_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.WHITE_WOOL)));
		ORANGE_WOOL_SLAB 			= register("orange_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.ORANGE_WOOL)));
		MAGENTA_WOOL_SLAB 			= register("magenta_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.MAGENTA_WOOL)));
		LIGHT_BLUE_WOOL_SLAB 		= register("light_blue_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_WOOL)));
		YELLOW_WOOL_SLAB 			= register("yellow_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.YELLOW_WOOL)));
		LIME_WOOL_SLAB 				= register("lime_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.LIME_WOOL)));
		PINK_WOOL_SLAB 				= register("pink_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.PINK_WOOL)));
		GRAY_WOOL_SLAB 				= register("gray_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.GRAY_WOOL)));
		LIGHT_GRAY_WOOL_SLAB 		= register("light_gray_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_WOOL)));
		CYAN_WOOL_SLAB 				= register("cyan_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.CYAN_WOOL)));
		PURPLE_WOOL_SLAB 			= register("purple_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.PURPLE_WOOL)));
		BLUE_WOOL_SLAB 				= register("blue_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.BLUE_WOOL)));
		BROWN_WOOL_SLAB 			= register("brown_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.BROWN_WOOL)));
		GREEN_WOOL_SLAB 			= register("green_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.GREEN_WOOL)));
		RED_WOOL_SLAB 				= register("red_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.RED_WOOL)));
		BLACK_WOOL_SLAB 			= register("black_wool_slab", new SlabBlock(Block.Settings.copy(Blocks.BLACK_WOOL)));

		NETHERRACK_SIDING 				= register("netherrack_siding", new SidingBlock(Block.Settings.copy(Blocks.NETHERRACK)));
		END_STONE_SIDING 				= register("end_stone_siding", new SidingBlock(Block.Settings.copy(Blocks.END_STONE)));
		QUARTZ_PILLAR_SIDING 			= register("quartz_pillar_siding", new SidingBlock(Block.Settings.copy(Blocks.QUARTZ_PILLAR)));
		CHISELED_QUARTZ_SIDING 			= register("chiseled_quartz_siding", new SidingBlock(Block.Settings.copy(Blocks.CHISELED_QUARTZ_BLOCK)));
		CHISELED_SANDSTONE_SIDING 		= register("chiseled_sandstone_siding", new SidingBlock(Block.Settings.copy(Blocks.CHISELED_SANDSTONE)));
		CHISELED_RED_SANDSTONE_SIDING 	= register("chiseled_red_sandstone_siding", new SidingBlock(Block.Settings.copy(Blocks.CHISELED_RED_SANDSTONE)));
		CRACKED_STONE_BRICK_SIDING 		= register("cracked_stone_brick_siding", new SidingBlock(Block.Settings.copy(Blocks.CRACKED_STONE_BRICKS)));
		CHISELED_STONE_BRICK_SIDING 	= register("chiseled_stone_brick_siding", new SidingBlock(Block.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
		PURPUR_PILLAR_SIDING 			= register("purpur_pillar_siding", new SidingBlock(Block.Settings.copy(Blocks.PURPUR_PILLAR)));
		TERRACOTTA_SIDING 				= register("terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.TERRACOTTA)));
		WHITE_TERRACOTTA_SIDING 		= register("white_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.WHITE_TERRACOTTA)));
		ORANGE_TERRACOTTA_SIDING 		= register("orange_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.ORANGE_TERRACOTTA)));
		MAGENTA_TERRACOTTA_SIDING 		= register("magenta_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.MAGENTA_TERRACOTTA)));
		LIGHT_BLUE_TERRACOTTA_SIDING 	= register("light_blue_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
		YELLOW_TERRACOTTA_SIDING 		= register("yellow_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.YELLOW_TERRACOTTA)));
		LIME_TERRACOTTA_SIDING 			= register("lime_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.LIME_TERRACOTTA)));
		PINK_TERRACOTTA_SIDING 			= register("pink_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.PINK_TERRACOTTA)));
		GRAY_TERRACOTTA_SIDING 			= register("gray_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.GRAY_TERRACOTTA)));
		LIGHT_GRAY_TERRACOTTA_SIDING 	= register("light_gray_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
		CYAN_TERRACOTTA_SIDING 			= register("cyan_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.CYAN_TERRACOTTA)));
		PURPLE_TERRACOTTA_SIDING 		= register("purple_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.PURPLE_TERRACOTTA)));
		BLUE_TERRACOTTA_SIDING 			= register("blue_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.BLUE_TERRACOTTA)));
		BROWN_TERRACOTTA_SIDING 		= register("brown_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.BROWN_TERRACOTTA)));
		GREEN_TERRACOTTA_SIDING 		= register("green_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.GREEN_TERRACOTTA)));
		RED_TERRACOTTA_SIDING 			= register("red_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.RED_TERRACOTTA)));
		BLACK_TERRACOTTA_SIDING 		= register("black_terracotta_siding", new SidingBlock(Block.Settings.copy(Blocks.BLACK_TERRACOTTA)));
		WHITE_CONCRETE_SIDING 			= register("white_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.WHITE_CONCRETE)));
		ORANGE_CONCRETE_SIDING 			= register("orange_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.ORANGE_CONCRETE)));
		MAGENTA_CONCRETE_SIDING 		= register("magenta_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.MAGENTA_CONCRETE)));
		LIGHT_BLUE_CONCRETE_SIDING 		= register("light_blue_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_CONCRETE)));
		YELLOW_CONCRETE_SIDING 			= register("yellow_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.YELLOW_CONCRETE)));
		LIME_CONCRETE_SIDING 			= register("lime_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.LIME_CONCRETE)));
		PINK_CONCRETE_SIDING 			= register("pink_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.PINK_CONCRETE)));
		GRAY_CONCRETE_SIDING 			= register("gray_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.GRAY_CONCRETE)));
		LIGHT_GRAY_CONCRETE_SIDING 		= register("light_gray_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_CONCRETE)));
		CYAN_CONCRETE_SIDING 			= register("cyan_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.CYAN_CONCRETE)));
		PURPLE_CONCRETE_SIDING 			= register("purple_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.PURPLE_CONCRETE)));
		BLUE_CONCRETE_SIDING 			= register("blue_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.BLUE_CONCRETE)));
		BROWN_CONCRETE_SIDING 			= register("brown_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.BROWN_CONCRETE)));
		GREEN_CONCRETE_SIDING 			= register("green_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.GREEN_CONCRETE)));
		RED_CONCRETE_SIDING 			= register("red_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.RED_CONCRETE)));
		BLACK_CONCRETE_SIDING 			= register("black_concrete_siding", new SidingBlock(Block.Settings.copy(Blocks.BLACK_CONCRETE)));
		GOLD_SIDING 					= register("gold_siding", new SidingBlock(Block.Settings.copy(Blocks.GOLD_BLOCK)));
		IRON_SIDING 					= register("iron_siding", new SidingBlock(Block.Settings.copy(Blocks.IRON_BLOCK)));
		DIAMOND_SIDING 					= register("diamond_siding", new SidingBlock(Block.Settings.copy(Blocks.DIAMOND_BLOCK)));
		EMERALD_SIDING 					= register("emerald_siding", new SidingBlock(Block.Settings.copy(Blocks.EMERALD_BLOCK)));
		REDSTONE_SIDING 				= register("redstone_siding", new SidingBlock(Block.Settings.copy(Blocks.REDSTONE_BLOCK)));
		COAL_SIDING 					= register("coal_siding", new SidingBlock(Block.Settings.copy(Blocks.COAL_BLOCK)));
		LAPIS_LAZULI_SIDING 			= register("lapis_lazuli_siding", new SidingBlock(Block.Settings.copy(Blocks.LAPIS_BLOCK)));
		PACKED_ICE_SIDING 				= register("packed_ice_siding", new SidingBlock(Block.Settings.copy(Blocks.PACKED_ICE)));
		WHITE_WOOL_SIDING 				= register("white_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.WHITE_WOOL)));
		ORANGE_WOOL_SIDING 				= register("orange_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.ORANGE_WOOL)));
		MAGENTA_WOOL_SIDING 			= register("magenta_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.MAGENTA_WOOL)));
		LIGHT_BLUE_WOOL_SIDING 			= register("light_blue_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_WOOL)));
		YELLOW_WOOL_SIDING 				= register("yellow_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.YELLOW_WOOL)));
		LIME_WOOL_SIDING 				= register("lime_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.LIME_WOOL)));
		PINK_WOOL_SIDING 				= register("pink_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.PINK_WOOL)));
		GRAY_WOOL_SIDING 				= register("gray_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.GRAY_WOOL)));
		LIGHT_GRAY_WOOL_SIDING 			= register("light_gray_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_WOOL)));
		CYAN_WOOL_SIDING 				= register("cyan_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.CYAN_WOOL)));
		PURPLE_WOOL_SIDING 				= register("purple_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.PURPLE_WOOL)));
		BLUE_WOOL_SIDING 				= register("blue_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.BLUE_WOOL)));
		BROWN_WOOL_SIDING 				= register("brown_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.BROWN_WOOL)));
		GREEN_WOOL_SIDING 				= register("green_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.GREEN_WOOL)));
		RED_WOOL_SIDING 				= register("red_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.RED_WOOL)));
		BLACK_WOOL_SIDING 				= register("black_wool_siding", new SidingBlock(Block.Settings.copy(Blocks.BLACK_WOOL)));

		NETHERRACK_WALL 			= register("netherrack_wall", new WallBlock(Block.Settings.copy(Blocks.NETHERRACK)));
		END_STONE_WALL 				= register("end_stone_wall", new WallBlock(Block.Settings.copy(Blocks.END_STONE)));
		STONE_WALL 					= register("stone_wall", new WallBlock(Block.Settings.copy(Blocks.STONE)));
		SMOOTH_SANDSTONE_WALL 		= register("smooth_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.SMOOTH_SANDSTONE)));
		SMOOTH_RED_SANDSTONE_WALL 	= register("smooth_red_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.SMOOTH_RED_SANDSTONE)));
		POLISHED_GRANITE_WALL 		= register("polished_granite_wall", new WallBlock(Block.Settings.copy(Blocks.POLISHED_GRANITE)));
		POLISHED_ANDESITE_WALL 		= register("polished_andesite_wall", new WallBlock(Block.Settings.copy(Blocks.POLISHED_ANDESITE)));
		POLISHED_DIORITE_WALL 		= register("polished_diorite_wall", new WallBlock(Block.Settings.copy(Blocks.POLISHED_DIORITE)));
		QUARTZ_WALL 				= register("quartz_wall", new WallBlock(Block.Settings.copy(Blocks.QUARTZ_BLOCK)));
		SMOOTH_QUARTZ_WALL 			= register("smooth_quartz_wall", new WallBlock(Block.Settings.copy(Blocks.SMOOTH_QUARTZ)));
		PURPUR_WALL 				= register("purpur_wall", new WallBlock(Block.Settings.copy(Blocks.PURPUR_BLOCK)));
		PRISMARINE_BRICK_WALL 		= register("prismarine_brick_wall", new WallBlock(Block.Settings.copy(Blocks.PRISMARINE_BRICKS)));
		DARK_PRISMARINE_WALL 		= register("dark_prismarine_wall", new WallBlock(Block.Settings.copy(Blocks.DARK_PRISMARINE)));
		CUT_SANDSTONE_WALL 			= register("cut_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.CUT_SANDSTONE)));
		CUT_RED_SANDSTONE_WALL 		= register("cut_red_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.CUT_RED_SANDSTONE)));
		SMOOTH_STONE_WALL 			= register("smooth_stone_wall", new WallBlock(Block.Settings.copy(Blocks.SMOOTH_STONE)));
		QUARTZ_PILLAR_WALL 			= register("quartz_pillar_wall", new WallBlock(Block.Settings.copy(Blocks.QUARTZ_PILLAR)));
		CHISELED_QUARTZ_WALL 		= register("chiseled_quartz_wall", new WallBlock(Block.Settings.copy(Blocks.CHISELED_QUARTZ_BLOCK)));
		CHISELED_SANDSTONE_WALL 	= register("chiseled_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.CHISELED_SANDSTONE)));
		CHISELED_RED_SANDSTONE_WALL = register("chiseled_red_sandstone_wall", new WallBlock(Block.Settings.copy(Blocks.CHISELED_RED_SANDSTONE)));
		CRACKED_STONE_BRICK_WALL 	= register("cracked_stone_brick_wall", new WallBlock(Block.Settings.copy(Blocks.CRACKED_STONE_BRICKS)));
		CHISELED_STONE_BRICK_WALL 	= register("chiseled_stone_brick_wall", new WallBlock(Block.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
		PURPUR_PILLAR_WALL 			= register("purpur_pillar_wall", new WallBlock(Block.Settings.copy(Blocks.PURPUR_PILLAR)));
		TERRACOTTA_WALL 			= register("terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.TERRACOTTA)));
		WHITE_TERRACOTTA_WALL 		= register("white_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.WHITE_TERRACOTTA)));
		ORANGE_TERRACOTTA_WALL 		= register("orange_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.ORANGE_TERRACOTTA)));
		MAGENTA_TERRACOTTA_WALL 	= register("magenta_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.MAGENTA_TERRACOTTA)));
		LIGHT_BLUE_TERRACOTTA_WALL 	= register("light_blue_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_TERRACOTTA)));
		YELLOW_TERRACOTTA_WALL 		= register("yellow_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.YELLOW_TERRACOTTA)));
		LIME_TERRACOTTA_WALL 		= register("lime_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.LIME_TERRACOTTA)));
		PINK_TERRACOTTA_WALL 		= register("pink_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.PINK_TERRACOTTA)));
		GRAY_TERRACOTTA_WALL 		= register("gray_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.GRAY_TERRACOTTA)));
		LIGHT_GRAY_TERRACOTTA_WALL 	= register("light_gray_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_TERRACOTTA)));
		CYAN_TERRACOTTA_WALL 		= register("cyan_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.CYAN_TERRACOTTA)));
		PURPLE_TERRACOTTA_WALL 		= register("purple_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.PURPLE_TERRACOTTA)));
		BLUE_TERRACOTTA_WALL 		= register("blue_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.BLUE_TERRACOTTA)));
		BROWN_TERRACOTTA_WALL 		= register("brown_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.BROWN_TERRACOTTA)));
		GREEN_TERRACOTTA_WALL 		= register("green_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.GREEN_TERRACOTTA)));
		RED_TERRACOTTA_WALL 		= register("red_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.RED_TERRACOTTA)));
		BLACK_TERRACOTTA_WALL 		= register("black_terracotta_wall", new WallBlock(Block.Settings.copy(Blocks.BLACK_TERRACOTTA)));
		WHITE_CONCRETE_WALL 		= register("white_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.WHITE_CONCRETE)));
		ORANGE_CONCRETE_WALL 		= register("orange_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.ORANGE_CONCRETE)));
		MAGENTA_CONCRETE_WALL 		= register("magenta_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.MAGENTA_CONCRETE)));
		LIGHT_BLUE_CONCRETE_WALL 	= register("light_blue_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_CONCRETE)));
		YELLOW_CONCRETE_WALL 		= register("yellow_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.YELLOW_CONCRETE)));
		LIME_CONCRETE_WALL 			= register("lime_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.LIME_CONCRETE)));
		PINK_CONCRETE_WALL 			= register("pink_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.PINK_CONCRETE)));
		GRAY_CONCRETE_WALL 			= register("gray_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.GRAY_CONCRETE)));
		LIGHT_GRAY_CONCRETE_WALL 	= register("light_gray_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_CONCRETE)));
		CYAN_CONCRETE_WALL 			= register("cyan_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.CYAN_CONCRETE)));
		PURPLE_CONCRETE_WALL 		= register("purple_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.PURPLE_CONCRETE)));
		BLUE_CONCRETE_WALL 			= register("blue_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.BLUE_CONCRETE)));
		BROWN_CONCRETE_WALL 		= register("brown_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.BROWN_CONCRETE)));
		GREEN_CONCRETE_WALL 		= register("green_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.GREEN_CONCRETE)));
		RED_CONCRETE_WALL 			= register("red_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.RED_CONCRETE)));
		BLACK_CONCRETE_WALL 		= register("black_concrete_wall", new WallBlock(Block.Settings.copy(Blocks.BLACK_CONCRETE)));
		GOLD_WALL 					= register("gold_wall", new WallBlock(Block.Settings.copy(Blocks.GOLD_BLOCK)));
		IRON_WALL 					= register("iron_wall", new WallBlock(Block.Settings.copy(Blocks.IRON_BLOCK)));
		DIAMOND_WALL 				= register("diamond_wall", new WallBlock(Block.Settings.copy(Blocks.DIAMOND_BLOCK)));
		EMERALD_WALL 				= register("emerald_wall", new WallBlock(Block.Settings.copy(Blocks.EMERALD_BLOCK)));
		REDSTONE_WALL 				= register("redstone_wall", new WallBlock(Block.Settings.copy(Blocks.REDSTONE_BLOCK)));
		COAL_WALL 					= register("coal_wall", new WallBlock(Block.Settings.copy(Blocks.COAL_BLOCK)));
		LAPIS_LAZULI_WALL 			= register("lapis_lazuli_wall", new WallBlock(Block.Settings.copy(Blocks.LAPIS_BLOCK)));
		PACKED_ICE_WALL 			= register("packed_ice_wall", new WallBlock(Block.Settings.copy(Blocks.PACKED_ICE)));
		WHITE_WOOL_WALL 			= register("white_wool_wall", new WallBlock(Block.Settings.copy(Blocks.WHITE_WOOL)));
		ORANGE_WOOL_WALL 			= register("orange_wool_wall", new WallBlock(Block.Settings.copy(Blocks.ORANGE_WOOL)));
		MAGENTA_WOOL_WALL 			= register("magenta_wool_wall", new WallBlock(Block.Settings.copy(Blocks.MAGENTA_WOOL)));
		LIGHT_BLUE_WOOL_WALL 		= register("light_blue_wool_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_BLUE_WOOL)));
		YELLOW_WOOL_WALL 			= register("yellow_wool_wall", new WallBlock(Block.Settings.copy(Blocks.YELLOW_WOOL)));
		LIME_WOOL_WALL 				= register("lime_wool_wall", new WallBlock(Block.Settings.copy(Blocks.LIME_WOOL)));
		PINK_WOOL_WALL 				= register("pink_wool_wall", new WallBlock(Block.Settings.copy(Blocks.PINK_WOOL)));
		GRAY_WOOL_WALL 				= register("gray_wool_wall", new WallBlock(Block.Settings.copy(Blocks.GRAY_WOOL)));
		LIGHT_GRAY_WOOL_WALL 		= register("light_gray_wool_wall", new WallBlock(Block.Settings.copy(Blocks.LIGHT_GRAY_WOOL)));
		CYAN_WOOL_WALL 				= register("cyan_wool_wall", new WallBlock(Block.Settings.copy(Blocks.CYAN_WOOL)));
		PURPLE_WOOL_WALL 			= register("purple_wool_wall", new WallBlock(Block.Settings.copy(Blocks.PURPLE_WOOL)));
		BLUE_WOOL_WALL 				= register("blue_wool_wall", new WallBlock(Block.Settings.copy(Blocks.BLUE_WOOL)));
		BROWN_WOOL_WALL 			= register("brown_wool_wall", new WallBlock(Block.Settings.copy(Blocks.BROWN_WOOL)));
		GREEN_WOOL_WALL 			= register("green_wool_wall", new WallBlock(Block.Settings.copy(Blocks.GREEN_WOOL)));
		RED_WOOL_WALL 				= register("red_wool_wall", new WallBlock(Block.Settings.copy(Blocks.RED_WOOL)));
		BLACK_WOOL_WALL 			= register("black_wool_wall", new WallBlock(Block.Settings.copy(Blocks.BLACK_WOOL)));

		RED_NETHER_BRICK_FENCE = register("red_nether_brick_fence", new FenceBlock(Block.Settings.copy(Blocks.RED_NETHER_BRICKS)));

		Iterator var0 = Registry.BLOCK.iterator();

		while(var0.hasNext()) {
			Block block_1 = (Block)var0.next();
			UnmodifiableIterator var2 = block_1.getStateFactory().getStates().iterator();

			while(var2.hasNext()) {
				BlockState blockState_1 = (BlockState)var2.next();
				blockState_1.initShapeCache();
				Block.STATE_IDS.add(blockState_1);
			}

			block_1.getDropTableId();
		}
	}
}
