package com.shnupbups.extrapieces;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.block.BlockItem;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ModItems {

	public static Item OAK_SIDING;
	public static Item SPRUCE_SIDING;
	public static Item BIRCH_SIDING;
	public static Item JUNGLE_SIDING;
	public static Item ACACIA_SIDING;
	public static Item DARK_OAK_SIDING;
	public static Item STONE_SIDING;
	public static Item SMOOTH_STONE_SIDING;
	public static Item SANDSTONE_SIDING;
	public static Item CUT_SANDSTONE_SIDING;
	public static Item PETRIFIED_OAK_SIDING;
	public static Item COBBLESTONE_SIDING;
	public static Item BRICK_SIDING;
	public static Item STONE_BRICK_SIDING;
	public static Item NETHER_BRICK_SIDING;
	public static Item QUARTZ_SIDING;
	public static Item RED_SANDSTONE_SIDING;
	public static Item CUT_RED_SANDSTONE_SIDING;
	public static Item PURPUR_SIDING;
	public static Item PRISMARINE_SIDING;
	public static Item PRISMARINE_BRICK_SIDING;
	public static Item DARK_PRISMARINE_SIDING;
	public static Item POLISHED_GRANITE_SIDING;
	public static Item SMOOTH_RED_SANDSTONE_SIDING;
	public static Item MOSSY_STONE_BRICK_SIDING;
	public static Item POLISHED_DIORITE_SIDING;
	public static Item MOSSY_COBBLESTONE_SIDING;
	public static Item END_STONE_BRICK_SIDING;
	public static Item SMOOTH_SANDSTONE_SIDING;
	public static Item SMOOTH_QUARTZ_SIDING;
	public static Item GRANITE_SIDING;
	public static Item ANDESITE_SIDING;
	public static Item RED_NETHER_BRICK_SIDING;
	public static Item POLISHED_ANDESITE_SIDING;
	public static Item DIORITE_SIDING;

	//missing stairs
	public static Item NETHERRACK_STAIRS;
	public static Item END_STONE_STAIRS;
	public static Item QUARTZ_PILLAR_STAIRS;
	public static Item CHISELED_QUARTZ_STAIRS;
	public static Item CHISELED_SANDSTONE_STAIRS;
	public static Item CUT_SANDSTONE_STAIRS;
	public static Item CHISELED_RED_SANDSTONE_STAIRS;
	public static Item CUT_RED_SANDSTONE_STAIRS;
	public static Item CRACKED_STONE_BRICK_STAIRS;
	public static Item CHISELED_STONE_BRICK_STAIRS;
	public static Item PURPUR_PILLAR_STAIRS;
	public static Item SMOOTH_STONE_STAIRS;
	public static Item TERRACOTTA_STAIRS;
	public static Item WHITE_TERRACOTTA_STAIRS;
	public static Item ORANGE_TERRACOTTA_STAIRS;
	public static Item MAGENTA_TERRACOTTA_STAIRS;
	public static Item LIGHT_BLUE_TERRACOTTA_STAIRS;
	public static Item YELLOW_TERRACOTTA_STAIRS;
	public static Item LIME_TERRACOTTA_STAIRS;
	public static Item PINK_TERRACOTTA_STAIRS;
	public static Item GRAY_TERRACOTTA_STAIRS;
	public static Item LIGHT_GRAY_TERRACOTTA_STAIRS;
	public static Item CYAN_TERRACOTTA_STAIRS;
	public static Item PURPLE_TERRACOTTA_STAIRS;
	public static Item BLUE_TERRACOTTA_STAIRS;
	public static Item BROWN_TERRACOTTA_STAIRS;
	public static Item GREEN_TERRACOTTA_STAIRS;
	public static Item RED_TERRACOTTA_STAIRS;
	public static Item BLACK_TERRACOTTA_STAIRS;
	public static Item WHITE_CONCRETE_STAIRS;
	public static Item ORANGE_CONCRETE_STAIRS;
	public static Item MAGENTA_CONCRETE_STAIRS;
	public static Item LIGHT_BLUE_CONCRETE_STAIRS;
	public static Item YELLOW_CONCRETE_STAIRS;
	public static Item LIME_CONCRETE_STAIRS;
	public static Item PINK_CONCRETE_STAIRS;
	public static Item GRAY_CONCRETE_STAIRS;
	public static Item LIGHT_GRAY_CONCRETE_STAIRS;
	public static Item CYAN_CONCRETE_STAIRS;
	public static Item PURPLE_CONCRETE_STAIRS;
	public static Item BLUE_CONCRETE_STAIRS;
	public static Item BROWN_CONCRETE_STAIRS;
	public static Item GREEN_CONCRETE_STAIRS;
	public static Item RED_CONCRETE_STAIRS;
	public static Item BLACK_CONCRETE_STAIRS;
	public static Item GOLD_STAIRS;
	public static Item IRON_STAIRS;
	public static Item DIAMOND_STAIRS;
	public static Item EMERALD_STAIRS;
	public static Item REDSTONE_STAIRS;
	public static Item COAL_STAIRS;
	public static Item LAPIS_LAZULI_STAIRS;
	public static Item PACKED_ICE_STAIRS;
	public static Item WHITE_WOOL_STAIRS;
	public static Item ORANGE_WOOL_STAIRS;
	public static Item MAGENTA_WOOL_STAIRS;
	public static Item LIGHT_BLUE_WOOL_STAIRS;
	public static Item YELLOW_WOOL_STAIRS;
	public static Item LIME_WOOL_STAIRS;
	public static Item PINK_WOOL_STAIRS;
	public static Item GRAY_WOOL_STAIRS;
	public static Item LIGHT_GRAY_WOOL_STAIRS;
	public static Item CYAN_WOOL_STAIRS;
	public static Item PURPLE_WOOL_STAIRS;
	public static Item BLUE_WOOL_STAIRS;
	public static Item BROWN_WOOL_STAIRS;
	public static Item GREEN_WOOL_STAIRS;
	public static Item RED_WOOL_STAIRS;
	public static Item BLACK_WOOL_STAIRS;

	//missing slabs
	public static Item NETHERRACK_SLAB;
	public static Item END_STONE_SLAB;
	public static Item QUARTZ_PILLAR_SLAB;
	public static Item CHISELED_QUARTZ_SLAB;
	public static Item CHISELED_SANDSTONE_SLAB;
	public static Item CHISELED_RED_SANDSTONE_SLAB;
	public static Item CRACKED_STONE_BRICK_SLAB;
	public static Item CHISELED_STONE_BRICK_SLAB;
	public static Item PURPUR_PILLAR_SLAB;
	public static Item TERRACOTTA_SLAB;
	public static Item WHITE_TERRACOTTA_SLAB;
	public static Item ORANGE_TERRACOTTA_SLAB;
	public static Item MAGENTA_TERRACOTTA_SLAB;
	public static Item LIGHT_BLUE_TERRACOTTA_SLAB;
	public static Item YELLOW_TERRACOTTA_SLAB;
	public static Item LIME_TERRACOTTA_SLAB;
	public static Item PINK_TERRACOTTA_SLAB;
	public static Item GRAY_TERRACOTTA_SLAB;
	public static Item LIGHT_GRAY_TERRACOTTA_SLAB;
	public static Item CYAN_TERRACOTTA_SLAB;
	public static Item PURPLE_TERRACOTTA_SLAB;
	public static Item BLUE_TERRACOTTA_SLAB;
	public static Item BROWN_TERRACOTTA_SLAB;
	public static Item GREEN_TERRACOTTA_SLAB;
	public static Item RED_TERRACOTTA_SLAB;
	public static Item BLACK_TERRACOTTA_SLAB;
	public static Item WHITE_CONCRETE_SLAB;
	public static Item ORANGE_CONCRETE_SLAB;
	public static Item MAGENTA_CONCRETE_SLAB;
	public static Item LIGHT_BLUE_CONCRETE_SLAB;
	public static Item YELLOW_CONCRETE_SLAB;
	public static Item LIME_CONCRETE_SLAB;
	public static Item PINK_CONCRETE_SLAB;
	public static Item GRAY_CONCRETE_SLAB;
	public static Item LIGHT_GRAY_CONCRETE_SLAB;
	public static Item CYAN_CONCRETE_SLAB;
	public static Item PURPLE_CONCRETE_SLAB;
	public static Item BLUE_CONCRETE_SLAB;
	public static Item BROWN_CONCRETE_SLAB;
	public static Item GREEN_CONCRETE_SLAB;
	public static Item RED_CONCRETE_SLAB;
	public static Item BLACK_CONCRETE_SLAB;
	public static Item GOLD_SLAB;
	public static Item IRON_SLAB;
	public static Item DIAMOND_SLAB;
	public static Item EMERALD_SLAB;
	public static Item REDSTONE_SLAB;
	public static Item COAL_SLAB;
	public static Item LAPIS_LAZULI_SLAB;
	public static Item PACKED_ICE_SLAB;
	public static Item WHITE_WOOL_SLAB;
	public static Item ORANGE_WOOL_SLAB;
	public static Item MAGENTA_WOOL_SLAB;
	public static Item LIGHT_BLUE_WOOL_SLAB;
	public static Item YELLOW_WOOL_SLAB;
	public static Item LIME_WOOL_SLAB;
	public static Item PINK_WOOL_SLAB;
	public static Item GRAY_WOOL_SLAB;
	public static Item LIGHT_GRAY_WOOL_SLAB;
	public static Item CYAN_WOOL_SLAB;
	public static Item PURPLE_WOOL_SLAB;
	public static Item BLUE_WOOL_SLAB;
	public static Item BROWN_WOOL_SLAB;
	public static Item GREEN_WOOL_SLAB;
	public static Item RED_WOOL_SLAB;
	public static Item BLACK_WOOL_SLAB;

	//missing sidings
	public static Item NETHERRACK_SIDING;
	public static Item END_STONE_SIDING;
	public static Item QUARTZ_PILLAR_SIDING;
	public static Item CHISELED_QUARTZ_SIDING;
	public static Item CHISELED_SANDSTONE_SIDING;
	public static Item CHISELED_RED_SANDSTONE_SIDING;
	public static Item CRACKED_STONE_BRICK_SIDING;
	public static Item CHISELED_STONE_BRICK_SIDING;
	public static Item PURPUR_PILLAR_SIDING;
	public static Item TERRACOTTA_SIDING;
	public static Item WHITE_TERRACOTTA_SIDING;
	public static Item ORANGE_TERRACOTTA_SIDING;
	public static Item MAGENTA_TERRACOTTA_SIDING;
	public static Item LIGHT_BLUE_TERRACOTTA_SIDING;
	public static Item YELLOW_TERRACOTTA_SIDING;
	public static Item LIME_TERRACOTTA_SIDING;
	public static Item PINK_TERRACOTTA_SIDING;
	public static Item GRAY_TERRACOTTA_SIDING;
	public static Item LIGHT_GRAY_TERRACOTTA_SIDING;
	public static Item CYAN_TERRACOTTA_SIDING;
	public static Item PURPLE_TERRACOTTA_SIDING;
	public static Item BLUE_TERRACOTTA_SIDING;
	public static Item BROWN_TERRACOTTA_SIDING;
	public static Item GREEN_TERRACOTTA_SIDING;
	public static Item RED_TERRACOTTA_SIDING;
	public static Item BLACK_TERRACOTTA_SIDING;
	public static Item WHITE_CONCRETE_SIDING;
	public static Item ORANGE_CONCRETE_SIDING;
	public static Item MAGENTA_CONCRETE_SIDING;
	public static Item LIGHT_BLUE_CONCRETE_SIDING;
	public static Item YELLOW_CONCRETE_SIDING;
	public static Item LIME_CONCRETE_SIDING;
	public static Item PINK_CONCRETE_SIDING;
	public static Item GRAY_CONCRETE_SIDING;
	public static Item LIGHT_GRAY_CONCRETE_SIDING;
	public static Item CYAN_CONCRETE_SIDING;
	public static Item PURPLE_CONCRETE_SIDING;
	public static Item BLUE_CONCRETE_SIDING;
	public static Item BROWN_CONCRETE_SIDING;
	public static Item GREEN_CONCRETE_SIDING;
	public static Item RED_CONCRETE_SIDING;
	public static Item BLACK_CONCRETE_SIDING;
	public static Item GOLD_SIDING;
	public static Item IRON_SIDING;
	public static Item DIAMOND_SIDING;
	public static Item EMERALD_SIDING;
	public static Item REDSTONE_SIDING;
	public static Item COAL_SIDING;
	public static Item LAPIS_LAZULI_SIDING;
	public static Item PACKED_ICE_SIDING;
	public static Item WHITE_WOOL_SIDING;
	public static Item ORANGE_WOOL_SIDING;
	public static Item MAGENTA_WOOL_SIDING;
	public static Item LIGHT_BLUE_WOOL_SIDING;
	public static Item YELLOW_WOOL_SIDING;
	public static Item LIME_WOOL_SIDING;
	public static Item PINK_WOOL_SIDING;
	public static Item GRAY_WOOL_SIDING;
	public static Item LIGHT_GRAY_WOOL_SIDING;
	public static Item CYAN_WOOL_SIDING;
	public static Item PURPLE_WOOL_SIDING;
	public static Item BLUE_WOOL_SIDING;
	public static Item BROWN_WOOL_SIDING;
	public static Item GREEN_WOOL_SIDING;
	public static Item RED_WOOL_SIDING;
	public static Item BLACK_WOOL_SIDING;

	//missing walls
	public static Item NETHERRACK_WALL;
	public static Item END_STONE_WALL;
	public static Item STONE_WALL;
	public static Item SMOOTH_SANDSTONE_WALL;
	public static Item SMOOTH_RED_SANDSTONE_WALL;
	public static Item POLISHED_GRANITE_WALL;
	public static Item POLISHED_ANDESITE_WALL;
	public static Item POLISHED_DIORITE_WALL;
	public static Item QUARTZ_WALL;
	public static Item SMOOTH_QUARTZ_WALL;
	public static Item PURPUR_WALL;
	public static Item PRISMARINE_BRICK_WALL;
	public static Item DARK_PRISMARINE_WALL;
	public static Item QUARTZ_PILLAR_WALL;
	public static Item CHISELED_QUARTZ_WALL;
	public static Item CHISELED_SANDSTONE_WALL;
	public static Item CUT_SANDSTONE_WALL;
	public static Item CHISELED_RED_SANDSTONE_WALL;
	public static Item CUT_RED_SANDSTONE_WALL;
	public static Item CRACKED_STONE_BRICK_WALL;
	public static Item CHISELED_STONE_BRICK_WALL;
	public static Item PURPUR_PILLAR_WALL;
	public static Item SMOOTH_STONE_WALL;
	public static Item TERRACOTTA_WALL;
	public static Item WHITE_TERRACOTTA_WALL;
	public static Item ORANGE_TERRACOTTA_WALL;
	public static Item MAGENTA_TERRACOTTA_WALL;
	public static Item LIGHT_BLUE_TERRACOTTA_WALL;
	public static Item YELLOW_TERRACOTTA_WALL;
	public static Item LIME_TERRACOTTA_WALL;
	public static Item PINK_TERRACOTTA_WALL;
	public static Item GRAY_TERRACOTTA_WALL;
	public static Item LIGHT_GRAY_TERRACOTTA_WALL;
	public static Item CYAN_TERRACOTTA_WALL;
	public static Item PURPLE_TERRACOTTA_WALL;
	public static Item BLUE_TERRACOTTA_WALL;
	public static Item BROWN_TERRACOTTA_WALL;
	public static Item GREEN_TERRACOTTA_WALL;
	public static Item RED_TERRACOTTA_WALL;
	public static Item BLACK_TERRACOTTA_WALL;
	public static Item WHITE_CONCRETE_WALL;
	public static Item ORANGE_CONCRETE_WALL;
	public static Item MAGENTA_CONCRETE_WALL;
	public static Item LIGHT_BLUE_CONCRETE_WALL;
	public static Item YELLOW_CONCRETE_WALL;
	public static Item LIME_CONCRETE_WALL;
	public static Item PINK_CONCRETE_WALL;
	public static Item GRAY_CONCRETE_WALL;
	public static Item LIGHT_GRAY_CONCRETE_WALL;
	public static Item CYAN_CONCRETE_WALL;
	public static Item PURPLE_CONCRETE_WALL;
	public static Item BLUE_CONCRETE_WALL;
	public static Item BROWN_CONCRETE_WALL;
	public static Item GREEN_CONCRETE_WALL;
	public static Item RED_CONCRETE_WALL;
	public static Item BLACK_CONCRETE_WALL;
	public static Item GOLD_WALL;
	public static Item IRON_WALL;
	public static Item DIAMOND_WALL;
	public static Item EMERALD_WALL;
	public static Item REDSTONE_WALL;
	public static Item COAL_WALL;
	public static Item LAPIS_LAZULI_WALL;
	public static Item PACKED_ICE_WALL;
	public static Item WHITE_WOOL_WALL;
	public static Item ORANGE_WOOL_WALL;
	public static Item MAGENTA_WOOL_WALL;
	public static Item LIGHT_BLUE_WOOL_WALL;
	public static Item YELLOW_WOOL_WALL;
	public static Item LIME_WOOL_WALL;
	public static Item PINK_WOOL_WALL;
	public static Item GRAY_WOOL_WALL;
	public static Item LIGHT_GRAY_WOOL_WALL;
	public static Item CYAN_WOOL_WALL;
	public static Item PURPLE_WOOL_WALL;
	public static Item BLUE_WOOL_WALL;
	public static Item BROWN_WOOL_WALL;
	public static Item GREEN_WOOL_WALL;
	public static Item RED_WOOL_WALL;
	public static Item BLACK_WOOL_WALL;

	//missing fences
	public static Item RED_NETHER_BRICK_FENCE;

	private static Item registerBlock(Block block_1) {
		return registerBlock(block_1, ExtraPieces.group);
	}

	private static Item registerBlock(Block block_1, ItemGroup itemGroup_1) {
		return register(new BlockItem(block_1, (new Item.Settings()).itemGroup(itemGroup_1)));
	}

	private static Item register(BlockItem blockItem_1) {
		return register((Block)blockItem_1.getBlock(), blockItem_1);
	}

	protected static Item register(Block block_1, Item item_1) {
		return register(Registry.BLOCK.getId(block_1), item_1);
	}

	private static Item register(Identifier identifier_1, Item item_1) {
		if (item_1 instanceof BlockItem) {
			((BlockItem)item_1).registerBlockItemMap(Item.BLOCK_ITEM_MAP, item_1);
		}

		return (Item)Registry.register(Registry.ITEM, (Identifier)identifier_1, item_1);
	}
	
	public static void init() {
		OAK_SIDING = registerBlock(ModBlocks.OAK_SIDING, ExtraPieces.group);
		SPRUCE_SIDING = registerBlock(ModBlocks.SPRUCE_SIDING, ExtraPieces.group);
		BIRCH_SIDING = registerBlock(ModBlocks.BIRCH_SIDING, ExtraPieces.group);
		JUNGLE_SIDING = registerBlock(ModBlocks.JUNGLE_SIDING, ExtraPieces.group);
		ACACIA_SIDING = registerBlock(ModBlocks.ACACIA_SIDING, ExtraPieces.group);
		DARK_OAK_SIDING = registerBlock(ModBlocks.DARK_OAK_SIDING, ExtraPieces.group);
		STONE_SIDING = registerBlock(ModBlocks.STONE_SIDING, ExtraPieces.group);
		SMOOTH_STONE_SIDING = registerBlock(ModBlocks.SMOOTH_STONE_SIDING, ExtraPieces.group);
		SANDSTONE_SIDING = registerBlock(ModBlocks.SANDSTONE_SIDING, ExtraPieces.group);
		CUT_SANDSTONE_SIDING = registerBlock(ModBlocks.CUT_SANDSTONE_SIDING, ExtraPieces.group);
		PETRIFIED_OAK_SIDING = registerBlock(ModBlocks.PETRIFIED_OAK_SIDING, ExtraPieces.group);
		COBBLESTONE_SIDING = registerBlock(ModBlocks.COBBLESTONE_SIDING, ExtraPieces.group);
		BRICK_SIDING = registerBlock(ModBlocks.BRICK_SIDING, ExtraPieces.group);
		STONE_BRICK_SIDING = registerBlock(ModBlocks.STONE_BRICK_SIDING, ExtraPieces.group);
		NETHER_BRICK_SIDING = registerBlock(ModBlocks.NETHER_BRICK_SIDING, ExtraPieces.group);
		QUARTZ_SIDING = registerBlock(ModBlocks.QUARTZ_SIDING, ExtraPieces.group);
		RED_SANDSTONE_SIDING = registerBlock(ModBlocks.RED_SANDSTONE_SIDING, ExtraPieces.group);
		CUT_RED_SANDSTONE_SIDING = registerBlock(ModBlocks.CUT_RED_SANDSTONE_SIDING, ExtraPieces.group);
		PURPUR_SIDING = registerBlock(ModBlocks.PURPUR_SIDING, ExtraPieces.group);
		PRISMARINE_SIDING = registerBlock(ModBlocks.PRISMARINE_SIDING, ExtraPieces.group);
		PRISMARINE_BRICK_SIDING = registerBlock(ModBlocks.PRISMARINE_BRICK_SIDING, ExtraPieces.group);
		DARK_PRISMARINE_SIDING = registerBlock(ModBlocks.DARK_PRISMARINE_SIDING, ExtraPieces.group);
		POLISHED_GRANITE_SIDING = registerBlock(ModBlocks.POLISHED_GRANITE_SIDING, ExtraPieces.group);
		SMOOTH_RED_SANDSTONE_SIDING = registerBlock(ModBlocks.SMOOTH_RED_SANDSTONE_SIDING, ExtraPieces.group);
		MOSSY_STONE_BRICK_SIDING = registerBlock(ModBlocks.MOSSY_STONE_BRICK_SIDING, ExtraPieces.group);
		POLISHED_DIORITE_SIDING = registerBlock(ModBlocks.POLISHED_DIORITE_SIDING, ExtraPieces.group);
		MOSSY_COBBLESTONE_SIDING = registerBlock(ModBlocks.MOSSY_COBBLESTONE_SIDING, ExtraPieces.group);
		END_STONE_BRICK_SIDING = registerBlock(ModBlocks.END_STONE_BRICK_SIDING, ExtraPieces.group);
		SMOOTH_SANDSTONE_SIDING = registerBlock(ModBlocks.SMOOTH_SANDSTONE_SIDING, ExtraPieces.group);
		SMOOTH_QUARTZ_SIDING = registerBlock(ModBlocks.SMOOTH_QUARTZ_SIDING, ExtraPieces.group);
		GRANITE_SIDING = registerBlock(ModBlocks.GRANITE_SIDING, ExtraPieces.group);
		ANDESITE_SIDING = registerBlock(ModBlocks.ANDESITE_SIDING, ExtraPieces.group);
		RED_NETHER_BRICK_SIDING = registerBlock(ModBlocks.RED_NETHER_BRICK_SIDING, ExtraPieces.group);
		POLISHED_ANDESITE_SIDING = registerBlock(ModBlocks.POLISHED_ANDESITE_SIDING, ExtraPieces.group);
		DIORITE_SIDING = registerBlock(ModBlocks.DIORITE_SIDING, ExtraPieces.group);
		
		NETHERRACK_STAIRS = registerBlock(ModBlocks.NETHERRACK_STAIRS,ExtraPieces.group);
		END_STONE_STAIRS = registerBlock(ModBlocks.END_STONE_STAIRS,ExtraPieces.group);
		QUARTZ_PILLAR_STAIRS = registerBlock(ModBlocks.QUARTZ_PILLAR_STAIRS,ExtraPieces.group);
		CHISELED_QUARTZ_STAIRS = registerBlock(ModBlocks.CHISELED_QUARTZ_STAIRS,ExtraPieces.group);
		CHISELED_SANDSTONE_STAIRS = registerBlock(ModBlocks.CHISELED_SANDSTONE_STAIRS,ExtraPieces.group);
		CUT_SANDSTONE_STAIRS = registerBlock(ModBlocks.CUT_SANDSTONE_STAIRS,ExtraPieces.group);
		CHISELED_RED_SANDSTONE_STAIRS = registerBlock(ModBlocks.CHISELED_RED_SANDSTONE_STAIRS,ExtraPieces.group);
		CUT_RED_SANDSTONE_STAIRS = registerBlock(ModBlocks.CUT_RED_SANDSTONE_STAIRS,ExtraPieces.group);
		CRACKED_STONE_BRICK_STAIRS = registerBlock(ModBlocks.CRACKED_STONE_BRICK_STAIRS,ExtraPieces.group);
		CHISELED_STONE_BRICK_STAIRS = registerBlock(ModBlocks.CHISELED_STONE_BRICK_STAIRS,ExtraPieces.group);
		PURPUR_PILLAR_STAIRS = registerBlock(ModBlocks.PURPUR_PILLAR_STAIRS,ExtraPieces.group);
		SMOOTH_STONE_STAIRS = registerBlock(ModBlocks.SMOOTH_STONE_STAIRS,ExtraPieces.group);
		TERRACOTTA_STAIRS = registerBlock(ModBlocks.TERRACOTTA_STAIRS,ExtraPieces.group);
		WHITE_TERRACOTTA_STAIRS = registerBlock(ModBlocks.WHITE_TERRACOTTA_STAIRS,ExtraPieces.group);
		ORANGE_TERRACOTTA_STAIRS = registerBlock(ModBlocks.ORANGE_TERRACOTTA_STAIRS,ExtraPieces.group);
		MAGENTA_TERRACOTTA_STAIRS = registerBlock(ModBlocks.MAGENTA_TERRACOTTA_STAIRS,ExtraPieces.group);
		LIGHT_BLUE_TERRACOTTA_STAIRS = registerBlock(ModBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS,ExtraPieces.group);
		YELLOW_TERRACOTTA_STAIRS = registerBlock(ModBlocks.YELLOW_TERRACOTTA_STAIRS,ExtraPieces.group);
		LIME_TERRACOTTA_STAIRS = registerBlock(ModBlocks.LIME_TERRACOTTA_STAIRS,ExtraPieces.group);
		PINK_TERRACOTTA_STAIRS = registerBlock(ModBlocks.PINK_TERRACOTTA_STAIRS,ExtraPieces.group);
		GRAY_TERRACOTTA_STAIRS = registerBlock(ModBlocks.GRAY_TERRACOTTA_STAIRS,ExtraPieces.group);
		LIGHT_GRAY_TERRACOTTA_STAIRS = registerBlock(ModBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS,ExtraPieces.group);
		CYAN_TERRACOTTA_STAIRS = registerBlock(ModBlocks.CYAN_TERRACOTTA_STAIRS,ExtraPieces.group);
		PURPLE_TERRACOTTA_STAIRS = registerBlock(ModBlocks.PURPLE_TERRACOTTA_STAIRS,ExtraPieces.group);
		BLUE_TERRACOTTA_STAIRS = registerBlock(ModBlocks.BLUE_TERRACOTTA_STAIRS,ExtraPieces.group);
		BROWN_TERRACOTTA_STAIRS = registerBlock(ModBlocks.BROWN_TERRACOTTA_STAIRS,ExtraPieces.group);
		GREEN_TERRACOTTA_STAIRS = registerBlock(ModBlocks.GREEN_TERRACOTTA_STAIRS,ExtraPieces.group);
		RED_TERRACOTTA_STAIRS = registerBlock(ModBlocks.RED_TERRACOTTA_STAIRS,ExtraPieces.group);
		BLACK_TERRACOTTA_STAIRS = registerBlock(ModBlocks.BLACK_TERRACOTTA_STAIRS,ExtraPieces.group);
		WHITE_CONCRETE_STAIRS = registerBlock(ModBlocks.WHITE_CONCRETE_STAIRS,ExtraPieces.group);
		ORANGE_CONCRETE_STAIRS = registerBlock(ModBlocks.ORANGE_CONCRETE_STAIRS,ExtraPieces.group);
		MAGENTA_CONCRETE_STAIRS = registerBlock(ModBlocks.MAGENTA_CONCRETE_STAIRS,ExtraPieces.group);
		LIGHT_BLUE_CONCRETE_STAIRS = registerBlock(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS,ExtraPieces.group);
		YELLOW_CONCRETE_STAIRS = registerBlock(ModBlocks.YELLOW_CONCRETE_STAIRS,ExtraPieces.group);
		LIME_CONCRETE_STAIRS = registerBlock(ModBlocks.LIME_CONCRETE_STAIRS,ExtraPieces.group);
		PINK_CONCRETE_STAIRS = registerBlock(ModBlocks.PINK_CONCRETE_STAIRS,ExtraPieces.group);
		GRAY_CONCRETE_STAIRS = registerBlock(ModBlocks.GRAY_CONCRETE_STAIRS,ExtraPieces.group);
		LIGHT_GRAY_CONCRETE_STAIRS = registerBlock(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS,ExtraPieces.group);
		CYAN_CONCRETE_STAIRS = registerBlock(ModBlocks.CYAN_CONCRETE_STAIRS,ExtraPieces.group);
		PURPLE_CONCRETE_STAIRS = registerBlock(ModBlocks.PURPLE_CONCRETE_STAIRS,ExtraPieces.group);
		BLUE_CONCRETE_STAIRS = registerBlock(ModBlocks.BLUE_CONCRETE_STAIRS,ExtraPieces.group);
		BROWN_CONCRETE_STAIRS = registerBlock(ModBlocks.BROWN_CONCRETE_STAIRS,ExtraPieces.group);
		GREEN_CONCRETE_STAIRS = registerBlock(ModBlocks.GREEN_CONCRETE_STAIRS,ExtraPieces.group);
		RED_CONCRETE_STAIRS = registerBlock(ModBlocks.RED_CONCRETE_STAIRS,ExtraPieces.group);
		BLACK_CONCRETE_STAIRS = registerBlock(ModBlocks.BLACK_CONCRETE_STAIRS,ExtraPieces.group);
		GOLD_STAIRS = registerBlock(ModBlocks.GOLD_STAIRS,ExtraPieces.group);
		IRON_STAIRS = registerBlock(ModBlocks.IRON_STAIRS,ExtraPieces.group);
		DIAMOND_STAIRS = registerBlock(ModBlocks.DIAMOND_STAIRS,ExtraPieces.group);
		EMERALD_STAIRS = registerBlock(ModBlocks.EMERALD_STAIRS,ExtraPieces.group);
		REDSTONE_STAIRS = registerBlock(ModBlocks.REDSTONE_STAIRS,ExtraPieces.group);
		COAL_STAIRS = registerBlock(ModBlocks.COAL_STAIRS,ExtraPieces.group);
		LAPIS_LAZULI_STAIRS = registerBlock(ModBlocks.LAPIS_LAZULI_STAIRS,ExtraPieces.group);
		PACKED_ICE_STAIRS = registerBlock(ModBlocks.PACKED_ICE_STAIRS,ExtraPieces.group);
		WHITE_WOOL_STAIRS = registerBlock(ModBlocks.WHITE_WOOL_STAIRS,ExtraPieces.group);
		ORANGE_WOOL_STAIRS = registerBlock(ModBlocks.ORANGE_WOOL_STAIRS,ExtraPieces.group);
		MAGENTA_WOOL_STAIRS = registerBlock(ModBlocks.MAGENTA_WOOL_STAIRS,ExtraPieces.group);
		LIGHT_BLUE_WOOL_STAIRS = registerBlock(ModBlocks.LIGHT_BLUE_WOOL_STAIRS,ExtraPieces.group);
		YELLOW_WOOL_STAIRS = registerBlock(ModBlocks.YELLOW_WOOL_STAIRS,ExtraPieces.group);
		LIME_WOOL_STAIRS = registerBlock(ModBlocks.LIME_WOOL_STAIRS,ExtraPieces.group);
		PINK_WOOL_STAIRS = registerBlock(ModBlocks.PINK_WOOL_STAIRS,ExtraPieces.group);
		GRAY_WOOL_STAIRS = registerBlock(ModBlocks.GRAY_WOOL_STAIRS,ExtraPieces.group);
		LIGHT_GRAY_WOOL_STAIRS = registerBlock(ModBlocks.LIGHT_GRAY_WOOL_STAIRS,ExtraPieces.group);
		CYAN_WOOL_STAIRS = registerBlock(ModBlocks.CYAN_WOOL_STAIRS,ExtraPieces.group);
		PURPLE_WOOL_STAIRS = registerBlock(ModBlocks.PURPLE_WOOL_STAIRS,ExtraPieces.group);
		BLUE_WOOL_STAIRS = registerBlock(ModBlocks.BLUE_WOOL_STAIRS,ExtraPieces.group);
		BROWN_WOOL_STAIRS = registerBlock(ModBlocks.BROWN_WOOL_STAIRS,ExtraPieces.group);
		GREEN_WOOL_STAIRS = registerBlock(ModBlocks.GREEN_WOOL_STAIRS,ExtraPieces.group);
		RED_WOOL_STAIRS = registerBlock(ModBlocks.RED_WOOL_STAIRS,ExtraPieces.group);
		BLACK_WOOL_STAIRS = registerBlock(ModBlocks.BLACK_WOOL_STAIRS,ExtraPieces.group);
		
		NETHERRACK_SLAB = registerBlock(ModBlocks.NETHERRACK_SLAB,ExtraPieces.group);
		END_STONE_SLAB = registerBlock(ModBlocks.END_STONE_SLAB,ExtraPieces.group);
		QUARTZ_PILLAR_SLAB = registerBlock(ModBlocks.QUARTZ_PILLAR_SLAB,ExtraPieces.group);
		CHISELED_QUARTZ_SLAB = registerBlock(ModBlocks.CHISELED_QUARTZ_SLAB,ExtraPieces.group);
		CHISELED_SANDSTONE_SLAB = registerBlock(ModBlocks.CHISELED_SANDSTONE_SLAB,ExtraPieces.group);
		CHISELED_RED_SANDSTONE_SLAB = registerBlock(ModBlocks.CHISELED_RED_SANDSTONE_SLAB,ExtraPieces.group);
		CRACKED_STONE_BRICK_SLAB = registerBlock(ModBlocks.CRACKED_STONE_BRICK_SLAB,ExtraPieces.group);
		CHISELED_STONE_BRICK_SLAB = registerBlock(ModBlocks.CHISELED_STONE_BRICK_SLAB,ExtraPieces.group);
		PURPUR_PILLAR_SLAB = registerBlock(ModBlocks.PURPUR_PILLAR_SLAB,ExtraPieces.group);
		TERRACOTTA_SLAB = registerBlock(ModBlocks.TERRACOTTA_SLAB,ExtraPieces.group);
		WHITE_TERRACOTTA_SLAB = registerBlock(ModBlocks.WHITE_TERRACOTTA_SLAB,ExtraPieces.group);
		ORANGE_TERRACOTTA_SLAB = registerBlock(ModBlocks.ORANGE_TERRACOTTA_SLAB,ExtraPieces.group);
		MAGENTA_TERRACOTTA_SLAB = registerBlock(ModBlocks.MAGENTA_TERRACOTTA_SLAB,ExtraPieces.group);
		LIGHT_BLUE_TERRACOTTA_SLAB = registerBlock(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB,ExtraPieces.group);
		YELLOW_TERRACOTTA_SLAB = registerBlock(ModBlocks.YELLOW_TERRACOTTA_SLAB,ExtraPieces.group);
		LIME_TERRACOTTA_SLAB = registerBlock(ModBlocks.LIME_TERRACOTTA_SLAB,ExtraPieces.group);
		PINK_TERRACOTTA_SLAB = registerBlock(ModBlocks.PINK_TERRACOTTA_SLAB,ExtraPieces.group);
		GRAY_TERRACOTTA_SLAB = registerBlock(ModBlocks.GRAY_TERRACOTTA_SLAB,ExtraPieces.group);
		LIGHT_GRAY_TERRACOTTA_SLAB = registerBlock(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB,ExtraPieces.group);
		CYAN_TERRACOTTA_SLAB = registerBlock(ModBlocks.CYAN_TERRACOTTA_SLAB,ExtraPieces.group);
		PURPLE_TERRACOTTA_SLAB = registerBlock(ModBlocks.PURPLE_TERRACOTTA_SLAB,ExtraPieces.group);
		BLUE_TERRACOTTA_SLAB = registerBlock(ModBlocks.BLUE_TERRACOTTA_SLAB,ExtraPieces.group);
		BROWN_TERRACOTTA_SLAB = registerBlock(ModBlocks.BROWN_TERRACOTTA_SLAB,ExtraPieces.group);
		GREEN_TERRACOTTA_SLAB = registerBlock(ModBlocks.GREEN_TERRACOTTA_SLAB,ExtraPieces.group);
		RED_TERRACOTTA_SLAB = registerBlock(ModBlocks.RED_TERRACOTTA_SLAB,ExtraPieces.group);
		BLACK_TERRACOTTA_SLAB = registerBlock(ModBlocks.BLACK_TERRACOTTA_SLAB,ExtraPieces.group);
		WHITE_CONCRETE_SLAB = registerBlock(ModBlocks.WHITE_CONCRETE_SLAB,ExtraPieces.group);
		ORANGE_CONCRETE_SLAB = registerBlock(ModBlocks.ORANGE_CONCRETE_SLAB,ExtraPieces.group);
		MAGENTA_CONCRETE_SLAB = registerBlock(ModBlocks.MAGENTA_CONCRETE_SLAB,ExtraPieces.group);
		LIGHT_BLUE_CONCRETE_SLAB = registerBlock(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB,ExtraPieces.group);
		YELLOW_CONCRETE_SLAB = registerBlock(ModBlocks.YELLOW_CONCRETE_SLAB,ExtraPieces.group);
		LIME_CONCRETE_SLAB = registerBlock(ModBlocks.LIME_CONCRETE_SLAB,ExtraPieces.group);
		PINK_CONCRETE_SLAB = registerBlock(ModBlocks.PINK_CONCRETE_SLAB,ExtraPieces.group);
		GRAY_CONCRETE_SLAB = registerBlock(ModBlocks.GRAY_CONCRETE_SLAB,ExtraPieces.group);
		LIGHT_GRAY_CONCRETE_SLAB = registerBlock(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB,ExtraPieces.group);
		CYAN_CONCRETE_SLAB = registerBlock(ModBlocks.CYAN_CONCRETE_SLAB,ExtraPieces.group);
		PURPLE_CONCRETE_SLAB = registerBlock(ModBlocks.PURPLE_CONCRETE_SLAB,ExtraPieces.group);
		BLUE_CONCRETE_SLAB = registerBlock(ModBlocks.BLUE_CONCRETE_SLAB,ExtraPieces.group);
		BROWN_CONCRETE_SLAB = registerBlock(ModBlocks.BROWN_CONCRETE_SLAB,ExtraPieces.group);
		GREEN_CONCRETE_SLAB = registerBlock(ModBlocks.GREEN_CONCRETE_SLAB,ExtraPieces.group);
		RED_CONCRETE_SLAB = registerBlock(ModBlocks.RED_CONCRETE_SLAB,ExtraPieces.group);
		BLACK_CONCRETE_SLAB = registerBlock(ModBlocks.BLACK_CONCRETE_SLAB,ExtraPieces.group);
		GOLD_SLAB = registerBlock(ModBlocks.GOLD_SLAB,ExtraPieces.group);
		IRON_SLAB = registerBlock(ModBlocks.IRON_SLAB,ExtraPieces.group);
		DIAMOND_SLAB = registerBlock(ModBlocks.DIAMOND_SLAB,ExtraPieces.group);
		EMERALD_SLAB = registerBlock(ModBlocks.EMERALD_SLAB,ExtraPieces.group);
		REDSTONE_SLAB = registerBlock(ModBlocks.REDSTONE_SLAB,ExtraPieces.group);
		COAL_SLAB = registerBlock(ModBlocks.COAL_SLAB,ExtraPieces.group);
		LAPIS_LAZULI_SLAB = registerBlock(ModBlocks.LAPIS_LAZULI_SLAB,ExtraPieces.group);
		PACKED_ICE_SLAB = registerBlock(ModBlocks.PACKED_ICE_SLAB,ExtraPieces.group);
		WHITE_WOOL_SLAB = registerBlock(ModBlocks.WHITE_WOOL_SLAB,ExtraPieces.group);
		ORANGE_WOOL_SLAB = registerBlock(ModBlocks.ORANGE_WOOL_SLAB,ExtraPieces.group);
		MAGENTA_WOOL_SLAB = registerBlock(ModBlocks.MAGENTA_WOOL_SLAB,ExtraPieces.group);
		LIGHT_BLUE_WOOL_SLAB = registerBlock(ModBlocks.LIGHT_BLUE_WOOL_SLAB,ExtraPieces.group);
		YELLOW_WOOL_SLAB = registerBlock(ModBlocks.YELLOW_WOOL_SLAB,ExtraPieces.group);
		LIME_WOOL_SLAB = registerBlock(ModBlocks.LIME_WOOL_SLAB,ExtraPieces.group);
		PINK_WOOL_SLAB = registerBlock(ModBlocks.PINK_WOOL_SLAB,ExtraPieces.group);
		GRAY_WOOL_SLAB = registerBlock(ModBlocks.GRAY_WOOL_SLAB,ExtraPieces.group);
		LIGHT_GRAY_WOOL_SLAB = registerBlock(ModBlocks.LIGHT_GRAY_WOOL_SLAB,ExtraPieces.group);
		CYAN_WOOL_SLAB = registerBlock(ModBlocks.CYAN_WOOL_SLAB,ExtraPieces.group);
		PURPLE_WOOL_SLAB = registerBlock(ModBlocks.PURPLE_WOOL_SLAB,ExtraPieces.group);
		BLUE_WOOL_SLAB = registerBlock(ModBlocks.BLUE_WOOL_SLAB,ExtraPieces.group);
		BROWN_WOOL_SLAB = registerBlock(ModBlocks.BROWN_WOOL_SLAB,ExtraPieces.group);
		GREEN_WOOL_SLAB = registerBlock(ModBlocks.GREEN_WOOL_SLAB,ExtraPieces.group);
		RED_WOOL_SLAB = registerBlock(ModBlocks.RED_WOOL_SLAB,ExtraPieces.group);
		BLACK_WOOL_SLAB = registerBlock(ModBlocks.BLACK_WOOL_SLAB,ExtraPieces.group);
		
		NETHERRACK_SIDING = registerBlock(ModBlocks.NETHERRACK_SIDING,ExtraPieces.group);
		END_STONE_SIDING = registerBlock(ModBlocks.END_STONE_SIDING,ExtraPieces.group);
		QUARTZ_PILLAR_SIDING = registerBlock(ModBlocks.QUARTZ_PILLAR_SIDING,ExtraPieces.group);
		CHISELED_QUARTZ_SIDING = registerBlock(ModBlocks.CHISELED_QUARTZ_SIDING,ExtraPieces.group);
		CHISELED_SANDSTONE_SIDING = registerBlock(ModBlocks.CHISELED_SANDSTONE_SIDING,ExtraPieces.group);
		CHISELED_RED_SANDSTONE_SIDING = registerBlock(ModBlocks.CHISELED_RED_SANDSTONE_SIDING,ExtraPieces.group);
		CRACKED_STONE_BRICK_SIDING = registerBlock(ModBlocks.CRACKED_STONE_BRICK_SIDING,ExtraPieces.group);
		CHISELED_STONE_BRICK_SIDING = registerBlock(ModBlocks.CHISELED_STONE_BRICK_SIDING,ExtraPieces.group);
		PURPUR_PILLAR_SIDING = registerBlock(ModBlocks.PURPUR_PILLAR_SIDING,ExtraPieces.group);
		TERRACOTTA_SIDING = registerBlock(ModBlocks.TERRACOTTA_SIDING,ExtraPieces.group);
		WHITE_TERRACOTTA_SIDING = registerBlock(ModBlocks.WHITE_TERRACOTTA_SIDING,ExtraPieces.group);
		ORANGE_TERRACOTTA_SIDING = registerBlock(ModBlocks.ORANGE_TERRACOTTA_SIDING,ExtraPieces.group);
		MAGENTA_TERRACOTTA_SIDING = registerBlock(ModBlocks.MAGENTA_TERRACOTTA_SIDING,ExtraPieces.group);
		LIGHT_BLUE_TERRACOTTA_SIDING = registerBlock(ModBlocks.LIGHT_BLUE_TERRACOTTA_SIDING,ExtraPieces.group);
		YELLOW_TERRACOTTA_SIDING = registerBlock(ModBlocks.YELLOW_TERRACOTTA_SIDING,ExtraPieces.group);
		LIME_TERRACOTTA_SIDING = registerBlock(ModBlocks.LIME_TERRACOTTA_SIDING,ExtraPieces.group);
		PINK_TERRACOTTA_SIDING = registerBlock(ModBlocks.PINK_TERRACOTTA_SIDING,ExtraPieces.group);
		GRAY_TERRACOTTA_SIDING = registerBlock(ModBlocks.GRAY_TERRACOTTA_SIDING,ExtraPieces.group);
		LIGHT_GRAY_TERRACOTTA_SIDING = registerBlock(ModBlocks.LIGHT_GRAY_TERRACOTTA_SIDING,ExtraPieces.group);
		CYAN_TERRACOTTA_SIDING = registerBlock(ModBlocks.CYAN_TERRACOTTA_SIDING,ExtraPieces.group);
		PURPLE_TERRACOTTA_SIDING = registerBlock(ModBlocks.PURPLE_TERRACOTTA_SIDING,ExtraPieces.group);
		BLUE_TERRACOTTA_SIDING = registerBlock(ModBlocks.BLUE_TERRACOTTA_SIDING,ExtraPieces.group);
		BROWN_TERRACOTTA_SIDING = registerBlock(ModBlocks.BROWN_TERRACOTTA_SIDING,ExtraPieces.group);
		GREEN_TERRACOTTA_SIDING = registerBlock(ModBlocks.GREEN_TERRACOTTA_SIDING,ExtraPieces.group);
		RED_TERRACOTTA_SIDING = registerBlock(ModBlocks.RED_TERRACOTTA_SIDING,ExtraPieces.group);
		BLACK_TERRACOTTA_SIDING = registerBlock(ModBlocks.BLACK_TERRACOTTA_SIDING,ExtraPieces.group);
		WHITE_CONCRETE_SIDING = registerBlock(ModBlocks.WHITE_CONCRETE_SIDING,ExtraPieces.group);
		ORANGE_CONCRETE_SIDING = registerBlock(ModBlocks.ORANGE_CONCRETE_SIDING,ExtraPieces.group);
		MAGENTA_CONCRETE_SIDING = registerBlock(ModBlocks.MAGENTA_CONCRETE_SIDING,ExtraPieces.group);
		LIGHT_BLUE_CONCRETE_SIDING = registerBlock(ModBlocks.LIGHT_BLUE_CONCRETE_SIDING,ExtraPieces.group);
		YELLOW_CONCRETE_SIDING = registerBlock(ModBlocks.YELLOW_CONCRETE_SIDING,ExtraPieces.group);
		LIME_CONCRETE_SIDING = registerBlock(ModBlocks.LIME_CONCRETE_SIDING,ExtraPieces.group);
		PINK_CONCRETE_SIDING = registerBlock(ModBlocks.PINK_CONCRETE_SIDING,ExtraPieces.group);
		GRAY_CONCRETE_SIDING = registerBlock(ModBlocks.GRAY_CONCRETE_SIDING,ExtraPieces.group);
		LIGHT_GRAY_CONCRETE_SIDING = registerBlock(ModBlocks.LIGHT_GRAY_CONCRETE_SIDING,ExtraPieces.group);
		CYAN_CONCRETE_SIDING = registerBlock(ModBlocks.CYAN_CONCRETE_SIDING,ExtraPieces.group);
		PURPLE_CONCRETE_SIDING = registerBlock(ModBlocks.PURPLE_CONCRETE_SIDING,ExtraPieces.group);
		BLUE_CONCRETE_SIDING = registerBlock(ModBlocks.BLUE_CONCRETE_SIDING,ExtraPieces.group);
		BROWN_CONCRETE_SIDING = registerBlock(ModBlocks.BROWN_CONCRETE_SIDING,ExtraPieces.group);
		GREEN_CONCRETE_SIDING = registerBlock(ModBlocks.GREEN_CONCRETE_SIDING,ExtraPieces.group);
		RED_CONCRETE_SIDING = registerBlock(ModBlocks.RED_CONCRETE_SIDING,ExtraPieces.group);
		BLACK_CONCRETE_SIDING = registerBlock(ModBlocks.BLACK_CONCRETE_SIDING,ExtraPieces.group);
		GOLD_SIDING = registerBlock(ModBlocks.GOLD_SIDING,ExtraPieces.group);
		IRON_SIDING = registerBlock(ModBlocks.IRON_SIDING,ExtraPieces.group);
		DIAMOND_SIDING = registerBlock(ModBlocks.DIAMOND_SIDING,ExtraPieces.group);
		EMERALD_SIDING = registerBlock(ModBlocks.EMERALD_SIDING,ExtraPieces.group);
		REDSTONE_SIDING = registerBlock(ModBlocks.REDSTONE_SIDING,ExtraPieces.group);
		COAL_SIDING = registerBlock(ModBlocks.COAL_SIDING,ExtraPieces.group);
		LAPIS_LAZULI_SIDING = registerBlock(ModBlocks.LAPIS_LAZULI_SIDING,ExtraPieces.group);
		PACKED_ICE_SIDING = registerBlock(ModBlocks.PACKED_ICE_SIDING,ExtraPieces.group);
		WHITE_WOOL_SIDING = registerBlock(ModBlocks.WHITE_WOOL_SIDING,ExtraPieces.group);
		ORANGE_WOOL_SIDING = registerBlock(ModBlocks.ORANGE_WOOL_SIDING,ExtraPieces.group);
		MAGENTA_WOOL_SIDING = registerBlock(ModBlocks.MAGENTA_WOOL_SIDING,ExtraPieces.group);
		LIGHT_BLUE_WOOL_SIDING = registerBlock(ModBlocks.LIGHT_BLUE_WOOL_SIDING,ExtraPieces.group);
		YELLOW_WOOL_SIDING = registerBlock(ModBlocks.YELLOW_WOOL_SIDING,ExtraPieces.group);
		LIME_WOOL_SIDING = registerBlock(ModBlocks.LIME_WOOL_SIDING,ExtraPieces.group);
		PINK_WOOL_SIDING = registerBlock(ModBlocks.PINK_WOOL_SIDING,ExtraPieces.group);
		GRAY_WOOL_SIDING = registerBlock(ModBlocks.GRAY_WOOL_SIDING,ExtraPieces.group);
		LIGHT_GRAY_WOOL_SIDING = registerBlock(ModBlocks.LIGHT_GRAY_WOOL_SIDING,ExtraPieces.group);
		CYAN_WOOL_SIDING = registerBlock(ModBlocks.CYAN_WOOL_SIDING,ExtraPieces.group);
		PURPLE_WOOL_SIDING = registerBlock(ModBlocks.PURPLE_WOOL_SIDING,ExtraPieces.group);
		BLUE_WOOL_SIDING = registerBlock(ModBlocks.BLUE_WOOL_SIDING,ExtraPieces.group);
		BROWN_WOOL_SIDING = registerBlock(ModBlocks.BROWN_WOOL_SIDING,ExtraPieces.group);
		GREEN_WOOL_SIDING = registerBlock(ModBlocks.GREEN_WOOL_SIDING,ExtraPieces.group);
		RED_WOOL_SIDING = registerBlock(ModBlocks.RED_WOOL_SIDING,ExtraPieces.group);
		BLACK_WOOL_SIDING = registerBlock(ModBlocks.BLACK_WOOL_SIDING,ExtraPieces.group);
		
		NETHERRACK_WALL = registerBlock(ModBlocks.NETHERRACK_WALL,ExtraPieces.group);
		END_STONE_WALL = registerBlock(ModBlocks.END_STONE_WALL,ExtraPieces.group);
		STONE_WALL = registerBlock(ModBlocks.STONE_WALL,ExtraPieces.group);
		SMOOTH_SANDSTONE_WALL = registerBlock(ModBlocks.SMOOTH_SANDSTONE_WALL,ExtraPieces.group);
		SMOOTH_RED_SANDSTONE_WALL = registerBlock(ModBlocks.SMOOTH_RED_SANDSTONE_WALL,ExtraPieces.group);
		POLISHED_GRANITE_WALL = registerBlock(ModBlocks.POLISHED_GRANITE_WALL,ExtraPieces.group);
		POLISHED_ANDESITE_WALL = registerBlock(ModBlocks.POLISHED_ANDESITE_WALL,ExtraPieces.group);
		POLISHED_DIORITE_WALL = registerBlock(ModBlocks.POLISHED_DIORITE_WALL,ExtraPieces.group);
		QUARTZ_WALL = registerBlock(ModBlocks.QUARTZ_WALL,ExtraPieces.group);
		SMOOTH_QUARTZ_WALL = registerBlock(ModBlocks.SMOOTH_QUARTZ_WALL,ExtraPieces.group);
		PURPUR_WALL = registerBlock(ModBlocks.PURPUR_WALL,ExtraPieces.group);
		PRISMARINE_BRICK_WALL = registerBlock(ModBlocks.PRISMARINE_BRICK_WALL,ExtraPieces.group);
		DARK_PRISMARINE_WALL = registerBlock(ModBlocks.DARK_PRISMARINE_WALL,ExtraPieces.group);
		QUARTZ_PILLAR_WALL = registerBlock(ModBlocks.QUARTZ_PILLAR_WALL,ExtraPieces.group);
		CHISELED_QUARTZ_WALL = registerBlock(ModBlocks.CHISELED_QUARTZ_WALL,ExtraPieces.group);
		CHISELED_SANDSTONE_WALL = registerBlock(ModBlocks.CHISELED_SANDSTONE_WALL,ExtraPieces.group);
		CUT_SANDSTONE_WALL = registerBlock(ModBlocks.CUT_SANDSTONE_WALL,ExtraPieces.group);
		CHISELED_RED_SANDSTONE_WALL = registerBlock(ModBlocks.CHISELED_RED_SANDSTONE_WALL,ExtraPieces.group);
		CUT_RED_SANDSTONE_WALL = registerBlock(ModBlocks.CUT_RED_SANDSTONE_WALL,ExtraPieces.group);
		CRACKED_STONE_BRICK_WALL = registerBlock(ModBlocks.CRACKED_STONE_BRICK_WALL,ExtraPieces.group);
		CHISELED_STONE_BRICK_WALL = registerBlock(ModBlocks.CHISELED_STONE_BRICK_WALL,ExtraPieces.group);
		PURPUR_PILLAR_WALL = registerBlock(ModBlocks.PURPUR_PILLAR_WALL,ExtraPieces.group);
		SMOOTH_STONE_WALL = registerBlock(ModBlocks.SMOOTH_STONE_WALL,ExtraPieces.group);
		TERRACOTTA_WALL = registerBlock(ModBlocks.TERRACOTTA_WALL,ExtraPieces.group);
		WHITE_TERRACOTTA_WALL = registerBlock(ModBlocks.WHITE_TERRACOTTA_WALL,ExtraPieces.group);
		ORANGE_TERRACOTTA_WALL = registerBlock(ModBlocks.ORANGE_TERRACOTTA_WALL,ExtraPieces.group);
		MAGENTA_TERRACOTTA_WALL = registerBlock(ModBlocks.MAGENTA_TERRACOTTA_WALL,ExtraPieces.group);
		LIGHT_BLUE_TERRACOTTA_WALL = registerBlock(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL,ExtraPieces.group);
		YELLOW_TERRACOTTA_WALL = registerBlock(ModBlocks.YELLOW_TERRACOTTA_WALL,ExtraPieces.group);
		LIME_TERRACOTTA_WALL = registerBlock(ModBlocks.LIME_TERRACOTTA_WALL,ExtraPieces.group);
		PINK_TERRACOTTA_WALL = registerBlock(ModBlocks.PINK_TERRACOTTA_WALL,ExtraPieces.group);
		GRAY_TERRACOTTA_WALL = registerBlock(ModBlocks.GRAY_TERRACOTTA_WALL,ExtraPieces.group);
		LIGHT_GRAY_TERRACOTTA_WALL = registerBlock(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL,ExtraPieces.group);
		CYAN_TERRACOTTA_WALL = registerBlock(ModBlocks.CYAN_TERRACOTTA_WALL,ExtraPieces.group);
		PURPLE_TERRACOTTA_WALL = registerBlock(ModBlocks.PURPLE_TERRACOTTA_WALL,ExtraPieces.group);
		BLUE_TERRACOTTA_WALL = registerBlock(ModBlocks.BLUE_TERRACOTTA_WALL,ExtraPieces.group);
		BROWN_TERRACOTTA_WALL = registerBlock(ModBlocks.BROWN_TERRACOTTA_WALL,ExtraPieces.group);
		GREEN_TERRACOTTA_WALL = registerBlock(ModBlocks.GREEN_TERRACOTTA_WALL,ExtraPieces.group);
		RED_TERRACOTTA_WALL = registerBlock(ModBlocks.RED_TERRACOTTA_WALL,ExtraPieces.group);
		BLACK_TERRACOTTA_WALL = registerBlock(ModBlocks.BLACK_TERRACOTTA_WALL,ExtraPieces.group);
		WHITE_CONCRETE_WALL = registerBlock(ModBlocks.WHITE_CONCRETE_WALL,ExtraPieces.group);
		ORANGE_CONCRETE_WALL = registerBlock(ModBlocks.ORANGE_CONCRETE_WALL,ExtraPieces.group);
		MAGENTA_CONCRETE_WALL = registerBlock(ModBlocks.MAGENTA_CONCRETE_WALL,ExtraPieces.group);
		LIGHT_BLUE_CONCRETE_WALL = registerBlock(ModBlocks.LIGHT_BLUE_CONCRETE_WALL,ExtraPieces.group);
		YELLOW_CONCRETE_WALL = registerBlock(ModBlocks.YELLOW_CONCRETE_WALL,ExtraPieces.group);
		LIME_CONCRETE_WALL = registerBlock(ModBlocks.LIME_CONCRETE_WALL,ExtraPieces.group);
		PINK_CONCRETE_WALL = registerBlock(ModBlocks.PINK_CONCRETE_WALL,ExtraPieces.group);
		GRAY_CONCRETE_WALL = registerBlock(ModBlocks.GRAY_CONCRETE_WALL,ExtraPieces.group);
		LIGHT_GRAY_CONCRETE_WALL = registerBlock(ModBlocks.LIGHT_GRAY_CONCRETE_WALL,ExtraPieces.group);
		CYAN_CONCRETE_WALL = registerBlock(ModBlocks.CYAN_CONCRETE_WALL,ExtraPieces.group);
		PURPLE_CONCRETE_WALL = registerBlock(ModBlocks.PURPLE_CONCRETE_WALL,ExtraPieces.group);
		BLUE_CONCRETE_WALL = registerBlock(ModBlocks.BLUE_CONCRETE_WALL,ExtraPieces.group);
		BROWN_CONCRETE_WALL = registerBlock(ModBlocks.BROWN_CONCRETE_WALL,ExtraPieces.group);
		GREEN_CONCRETE_WALL = registerBlock(ModBlocks.GREEN_CONCRETE_WALL,ExtraPieces.group);
		RED_CONCRETE_WALL = registerBlock(ModBlocks.RED_CONCRETE_WALL,ExtraPieces.group);
		BLACK_CONCRETE_WALL = registerBlock(ModBlocks.BLACK_CONCRETE_WALL,ExtraPieces.group);
		GOLD_WALL = registerBlock(ModBlocks.GOLD_WALL,ExtraPieces.group);
		IRON_WALL = registerBlock(ModBlocks.IRON_WALL,ExtraPieces.group);
		DIAMOND_WALL = registerBlock(ModBlocks.DIAMOND_WALL,ExtraPieces.group);
		EMERALD_WALL = registerBlock(ModBlocks.EMERALD_WALL,ExtraPieces.group);
		REDSTONE_WALL = registerBlock(ModBlocks.REDSTONE_WALL,ExtraPieces.group);
		COAL_WALL = registerBlock(ModBlocks.COAL_WALL,ExtraPieces.group);
		LAPIS_LAZULI_WALL = registerBlock(ModBlocks.LAPIS_LAZULI_WALL,ExtraPieces.group);
		PACKED_ICE_WALL = registerBlock(ModBlocks.PACKED_ICE_WALL,ExtraPieces.group);
		WHITE_WOOL_WALL = registerBlock(ModBlocks.WHITE_WOOL_WALL,ExtraPieces.group);
		ORANGE_WOOL_WALL = registerBlock(ModBlocks.ORANGE_WOOL_WALL,ExtraPieces.group);
		MAGENTA_WOOL_WALL = registerBlock(ModBlocks.MAGENTA_WOOL_WALL,ExtraPieces.group);
		LIGHT_BLUE_WOOL_WALL = registerBlock(ModBlocks.LIGHT_BLUE_WOOL_WALL,ExtraPieces.group);
		YELLOW_WOOL_WALL = registerBlock(ModBlocks.YELLOW_WOOL_WALL,ExtraPieces.group);
		LIME_WOOL_WALL = registerBlock(ModBlocks.LIME_WOOL_WALL,ExtraPieces.group);
		PINK_WOOL_WALL = registerBlock(ModBlocks.PINK_WOOL_WALL,ExtraPieces.group);
		GRAY_WOOL_WALL = registerBlock(ModBlocks.GRAY_WOOL_WALL,ExtraPieces.group);
		LIGHT_GRAY_WOOL_WALL = registerBlock(ModBlocks.LIGHT_GRAY_WOOL_WALL,ExtraPieces.group);
		CYAN_WOOL_WALL = registerBlock(ModBlocks.CYAN_WOOL_WALL,ExtraPieces.group);
		PURPLE_WOOL_WALL = registerBlock(ModBlocks.PURPLE_WOOL_WALL,ExtraPieces.group);
		BLUE_WOOL_WALL = registerBlock(ModBlocks.BLUE_WOOL_WALL,ExtraPieces.group);
		BROWN_WOOL_WALL = registerBlock(ModBlocks.BROWN_WOOL_WALL,ExtraPieces.group);
		GREEN_WOOL_WALL = registerBlock(ModBlocks.GREEN_WOOL_WALL,ExtraPieces.group);
		RED_WOOL_WALL = registerBlock(ModBlocks.RED_WOOL_WALL,ExtraPieces.group);
		BLACK_WOOL_WALL = registerBlock(ModBlocks.BLACK_WOOL_WALL,ExtraPieces.group);
		
		RED_NETHER_BRICK_FENCE = registerBlock(ModBlocks.RED_NETHER_BRICK_FENCE,ExtraPieces.group);
	}
}
