package com.shnupbups.extrapieces.register;

import com.shnupbups.extrapieces.core.PieceSet;
import com.shnupbups.extrapieces.core.PieceSets;
import com.shnupbups.extrapieces.core.PieceType;
import net.minecraft.block.Blocks;

public class ModBlocks {

	public static PieceSet DUMMY_PIECES;

	public static PieceSet PRISMARINE_PIECES;
	public static PieceSet PRISMARINE_BRICK_PIECES;
	public static PieceSet DARK_PRISMARINE_PIECES;
	public static PieceSet OAK_PIECES;
	public static PieceSet SPRUCE_PIECES;
	public static PieceSet BIRCH_PIECES;
	public static PieceSet JUNGLE_PIECES;
	public static PieceSet ACACIA_PIECES;
	public static PieceSet DARK_OAK_PIECES;
	public static PieceSet STONE_PIECES;
	public static PieceSet SMOOTH_STONE_PIECES;
	public static PieceSet SANDSTONE_PIECES;
	public static PieceSet CUT_SANDSTONE_PIECES;
	public static PieceSet PETRIFIED_OAK_PIECES;
	public static PieceSet COBBLESTONE_PIECES;
	public static PieceSet BRICK_PIECES;
	public static PieceSet STONE_BRICK_PIECES;
	public static PieceSet NETHER_BRICK_PIECES;
	public static PieceSet QUARTZ_PIECES;
	public static PieceSet RED_SANDSTONE_PIECES;
	public static PieceSet CUT_RED_SANDSTONE_PIECES;
	public static PieceSet PURPUR_PIECES;
	public static PieceSet POLISHED_GRANITE_PIECES;
	public static PieceSet SMOOTH_RED_SANDSTONE_PIECES;
	public static PieceSet MOSSY_STONE_BRICK_PIECES;
	public static PieceSet POLISHED_DIORITE_PIECES;
	public static PieceSet MOSSY_COBBLESTONE_PIECES;
	public static PieceSet END_STONE_BRICK_PIECES;
	public static PieceSet SMOOTH_SANDSTONE_PIECES;
	public static PieceSet SMOOTH_QUARTZ_PIECES;
	public static PieceSet GRANITE_PIECES;
	public static PieceSet ANDESITE_PIECES;
	public static PieceSet RED_NETHER_BRICK_PIECES;
	public static PieceSet POLISHED_ANDESITE_PIECES;
	public static PieceSet DIORITE_PIECES;
	public static PieceSet NETHERRACK_PIECES;
	public static PieceSet END_STONE_PIECES;
	public static PieceSet QUARTZ_PILLAR_PIECES;
	public static PieceSet CHISELED_QUARTZ_PIECES;
	public static PieceSet CHISELED_SANDSTONE_PIECES;
	public static PieceSet CHISELED_RED_SANDSTONE_PIECES;
	public static PieceSet CRACKED_STONE_BRICK_PIECES;
	public static PieceSet CHISELED_STONE_BRICK_PIECES;
	public static PieceSet PURPUR_PILLAR_PIECES;
	public static PieceSet TERRACOTTA_PIECES;
	public static PieceSet WHITE_TERRACOTTA_PIECES;
	public static PieceSet ORANGE_TERRACOTTA_PIECES;
	public static PieceSet MAGENTA_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_BLUE_TERRACOTTA_PIECES;
	public static PieceSet YELLOW_TERRACOTTA_PIECES;
	public static PieceSet LIME_TERRACOTTA_PIECES;
	public static PieceSet PINK_TERRACOTTA_PIECES;
	public static PieceSet GRAY_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_GRAY_TERRACOTTA_PIECES;
	public static PieceSet CYAN_TERRACOTTA_PIECES;
	public static PieceSet PURPLE_TERRACOTTA_PIECES;
	public static PieceSet BLUE_TERRACOTTA_PIECES;
	public static PieceSet BROWN_TERRACOTTA_PIECES;
	public static PieceSet GREEN_TERRACOTTA_PIECES;
	public static PieceSet RED_TERRACOTTA_PIECES;
	public static PieceSet BLACK_TERRACOTTA_PIECES;
	public static PieceSet WHITE_CONCRETE_PIECES;
	public static PieceSet ORANGE_CONCRETE_PIECES;
	public static PieceSet MAGENTA_CONCRETE_PIECES;
	public static PieceSet LIGHT_BLUE_CONCRETE_PIECES;
	public static PieceSet YELLOW_CONCRETE_PIECES;
	public static PieceSet LIME_CONCRETE_PIECES;
	public static PieceSet PINK_CONCRETE_PIECES;
	public static PieceSet GRAY_CONCRETE_PIECES;
	public static PieceSet LIGHT_GRAY_CONCRETE_PIECES;
	public static PieceSet CYAN_CONCRETE_PIECES;
	public static PieceSet PURPLE_CONCRETE_PIECES;
	public static PieceSet BLUE_CONCRETE_PIECES;
	public static PieceSet BROWN_CONCRETE_PIECES;
	public static PieceSet GREEN_CONCRETE_PIECES;
	public static PieceSet RED_CONCRETE_PIECES;
	public static PieceSet BLACK_CONCRETE_PIECES;
	public static PieceSet GOLD_PIECES;
	public static PieceSet IRON_PIECES;
	public static PieceSet DIAMOND_PIECES;
	public static PieceSet EMERALD_PIECES;
	public static PieceSet REDSTONE_PIECES;
	public static PieceSet COAL_PIECES;
	public static PieceSet LAPIS_LAZULI_PIECES;
	public static PieceSet PACKED_ICE_PIECES;
	public static PieceSet WHITE_WOOL_PIECES;
	public static PieceSet ORANGE_WOOL_PIECES;
	public static PieceSet MAGENTA_WOOL_PIECES;
	public static PieceSet LIGHT_BLUE_WOOL_PIECES;
	public static PieceSet YELLOW_WOOL_PIECES;
	public static PieceSet LIME_WOOL_PIECES;
	public static PieceSet PINK_WOOL_PIECES;
	public static PieceSet GRAY_WOOL_PIECES;
	public static PieceSet LIGHT_GRAY_WOOL_PIECES;
	public static PieceSet CYAN_WOOL_PIECES;
	public static PieceSet PURPLE_WOOL_PIECES;
	public static PieceSet BLUE_WOOL_PIECES;
	public static PieceSet BROWN_WOOL_PIECES;
	public static PieceSet GREEN_WOOL_PIECES;
	public static PieceSet RED_WOOL_PIECES;
	public static PieceSet BLACK_WOOL_PIECES;
	public static PieceSet WHITE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet ORANGE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet MAGENTA_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet YELLOW_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIME_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet PINK_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet CYAN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet PURPLE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BLUE_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BROWN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet GREEN_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet RED_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet BLACK_GLAZED_TERRACOTTA_PIECES;
	public static PieceSet OBSIDIAN_PIECES;
	public static PieceSet BONE_PIECES;
	public static PieceSet HAY_PIECES;
	public static PieceSet PUMPKIN_PIECES;
	public static PieceSet MELON_PIECES;
	public static PieceSet SNOW_PIECES;
	public static PieceSet MAGMA_PIECES;
	public static PieceSet GLOWSTONE_PIECES;
	public static PieceSet NETHER_WART_PIECES;
	public static PieceSet BROWN_MUSHROOM_PIECES;
	public static PieceSet RED_MUSHROOM_PIECES;
	public static PieceSet MUSHROOM_STEM_PIECES;
	public static PieceSet DRIED_KELP_PIECES;
	public static PieceSet TUBE_CORAL_PIECES;
	public static PieceSet BRAIN_CORAL_PIECES;
	public static PieceSet BUBBLE_CORAL_PIECES;
	public static PieceSet FIRE_CORAL_PIECES;
	public static PieceSet HORN_CORAL_PIECES;
	public static PieceSet DEAD_TUBE_CORAL_PIECES;
	public static PieceSet DEAD_BRAIN_CORAL_PIECES;
	public static PieceSet DEAD_BUBBLE_CORAL_PIECES;
	public static PieceSet DEAD_FIRE_CORAL_PIECES;
	public static PieceSet DEAD_HORN_CORAL_PIECES;
	public static PieceSet OAK_LOG_PIECES;
	public static PieceSet SPRUCE_LOG_PIECES;
	public static PieceSet BIRCH_LOG_PIECES;
	public static PieceSet JUNGLE_LOG_PIECES;
	public static PieceSet ACACIA_LOG_PIECES;
	public static PieceSet DARK_OAK_LOG_PIECES;
	public static PieceSet STRIPPED_OAK_LOG_PIECES;
	public static PieceSet STRIPPED_SPRUCE_LOG_PIECES;
	public static PieceSet STRIPPED_BIRCH_LOG_PIECES;
	public static PieceSet STRIPPED_JUNGLE_LOG_PIECES;
	public static PieceSet STRIPPED_ACACIA_LOG_PIECES;
	public static PieceSet STRIPPED_DARK_OAK_LOG_PIECES;
	public static PieceSet OAK_WOOD_PIECES;
	public static PieceSet SPRUCE_WOOD_PIECES;
	public static PieceSet BIRCH_WOOD_PIECES;
	public static PieceSet JUNGLE_WOOD_PIECES;
	public static PieceSet ACACIA_WOOD_PIECES;
	public static PieceSet DARK_OAK_WOOD_PIECES;
	public static PieceSet STRIPPED_OAK_WOOD_PIECES;
	public static PieceSet STRIPPED_SPRUCE_WOOD_PIECES;
	public static PieceSet STRIPPED_BIRCH_WOOD_PIECES;
	public static PieceSet STRIPPED_JUNGLE_WOOD_PIECES;
	public static PieceSet STRIPPED_ACACIA_WOOD_PIECES;
	public static PieceSet STRIPPED_DARK_OAK_WOOD_PIECES;

	public static void init() {
		DUMMY_PIECES = PieceSets.createSet(Blocks.AIR, "dummy").setHasCustomTranslation().register();
	}

	public static void generateDefaultSets() {
		PRISMARINE_PIECES = PieceSets.createSet(Blocks.PRISMARINE, "prismarine", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.PRISMARINE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.PRISMARINE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.PRISMARINE_WALL).register();
		PRISMARINE_BRICK_PIECES = PieceSets.createSet(Blocks.PRISMARINE_BRICKS, "prismarine_brick", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.PRISMARINE_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.PRISMARINE_BRICK_STAIRS).setHasCustomTranslation().register();
		DARK_PRISMARINE_PIECES = PieceSets.createSet(Blocks.DARK_PRISMARINE, "dark_prismarine", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.DARK_PRISMARINE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.DARK_PRISMARINE_STAIRS).register();
		OAK_PIECES = PieceSets.createSet(Blocks.OAK_PLANKS, "oak", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.OAK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.OAK_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.OAK_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.OAK_FENCE_GATE).setHasCustomTranslation().register();
		SPRUCE_PIECES = PieceSets.createSet(Blocks.SPRUCE_PLANKS, "spruce", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.SPRUCE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.SPRUCE_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.SPRUCE_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.SPRUCE_FENCE_GATE).setHasCustomTranslation().register();
		BIRCH_PIECES = PieceSets.createSet(Blocks.BIRCH_PLANKS, "birch", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.BIRCH_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.BIRCH_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.BIRCH_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.BIRCH_FENCE_GATE).setHasCustomTranslation().register();
		JUNGLE_PIECES = PieceSets.createSet(Blocks.JUNGLE_PLANKS, "jungle", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.JUNGLE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.JUNGLE_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.JUNGLE_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.JUNGLE_FENCE_GATE).setHasCustomTranslation().register();
		ACACIA_PIECES = PieceSets.createSet(Blocks.ACACIA_PLANKS, "acacia", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.ACACIA_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.ACACIA_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.ACACIA_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.ACACIA_FENCE_GATE).setHasCustomTranslation().register();
		DARK_OAK_PIECES = PieceSets.createSet(Blocks.DARK_OAK_PLANKS, "dark_oak", PieceSet.JUST_EXTRAS_AND_WALL).setUncraftable(PieceType.WALL).addVanillaPiece(PieceType.SLAB, Blocks.DARK_OAK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.DARK_OAK_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.DARK_OAK_FENCE).addVanillaPiece(PieceType.FENCE_GATE, Blocks.DARK_OAK_FENCE_GATE).setHasCustomTranslation().register();
		STONE_PIECES = PieceSets.createSet(Blocks.STONE, "stone", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.STONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.STONE_STAIRS).register();
		SMOOTH_STONE_PIECES = PieceSets.createSet(Blocks.SMOOTH_STONE, "smooth_stone", PieceSet.NO_SLAB).addVanillaPiece(PieceType.SLAB, Blocks.SMOOTH_STONE_SLAB).register();
		SANDSTONE_PIECES = PieceSets.createSet(Blocks.SANDSTONE, "sandstone", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.SANDSTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.SANDSTONE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.SANDSTONE_WALL).setTopTexture("sandstone_top").register();
		CUT_SANDSTONE_PIECES = PieceSets.createSet(Blocks.CUT_SANDSTONE, "cut_sandstone", PieceSet.NO_SLAB).addVanillaPiece(PieceType.SLAB, Blocks.CUT_SANDSTONE_SLAB).setTopTexture("sandstone_top").register();
		PETRIFIED_OAK_PIECES = PieceSets.createSet(Blocks.PETRIFIED_OAK_SLAB, "petrified_oak", PieceType.SIDING).addVanillaPiece(PieceType.SLAB, Blocks.PETRIFIED_OAK_SLAB).setTexture("oak_planks").setHasCustomTranslation().register();
		COBBLESTONE_PIECES = PieceSets.createSet(Blocks.COBBLESTONE, "cobblestone", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.COBBLESTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.COBBLESTONE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.COBBLESTONE_WALL).register();
		BRICK_PIECES = PieceSets.createSet(Blocks.BRICKS, "brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.BRICK_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.BRICK_WALL).setHasCustomTranslation().register();
		STONE_BRICK_PIECES = PieceSets.createSet(Blocks.STONE_BRICKS, "stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.STONE_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.STONE_BRICK_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.STONE_BRICK_WALL).setHasCustomTranslation().register();
		NETHER_BRICK_PIECES = PieceSets.createSet(Blocks.NETHER_BRICKS, "nether_brick", PieceSet.JUST_EXTRAS_AND_FENCE_GATE).addVanillaPiece(PieceType.SLAB, Blocks.NETHER_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.NETHER_BRICK_STAIRS).addVanillaPiece(PieceType.FENCE, Blocks.NETHER_BRICK_FENCE).addVanillaPiece(PieceType.WALL, Blocks.NETHER_BRICK_WALL).setHasCustomTranslation().register();
		QUARTZ_PIECES = PieceSets.createSet(Blocks.QUARTZ_BLOCK, "quartz", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.QUARTZ_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.QUARTZ_STAIRS).setTexture("quartz_block_side").setTopTexture("quartz_block_top").setHasCustomTranslation().register();
		RED_SANDSTONE_PIECES = PieceSets.createSet(Blocks.RED_SANDSTONE, "red_sandstone", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.RED_SANDSTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.RED_SANDSTONE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.RED_SANDSTONE_WALL).setTopTexture("red_sandstone_top").register();
		CUT_RED_SANDSTONE_PIECES = PieceSets.createSet(Blocks.CUT_RED_SANDSTONE, "cut_red_sandstone", PieceSet.NO_SLAB).addVanillaPiece(PieceType.SLAB, Blocks.CUT_RED_SANDSTONE_SLAB).setTopTexture("red_sandstone_top").register();
		PURPUR_PIECES = PieceSets.createSet(Blocks.PURPUR_BLOCK, "purpur", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.PURPUR_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.PURPUR_STAIRS).setHasCustomTranslation().register();
		POLISHED_GRANITE_PIECES = PieceSets.createSet(Blocks.POLISHED_GRANITE, "polished_granite", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.POLISHED_GRANITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.POLISHED_GRANITE_STAIRS).register();
		SMOOTH_RED_SANDSTONE_PIECES = PieceSets.createSet(Blocks.SMOOTH_RED_SANDSTONE, "smooth_red_sandstone", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.SMOOTH_RED_SANDSTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.SMOOTH_RED_SANDSTONE_STAIRS).setTexture("red_sandstone_top").register();
		MOSSY_STONE_BRICK_PIECES = PieceSets.createSet(Blocks.MOSSY_STONE_BRICKS, "mossy_stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.MOSSY_STONE_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.MOSSY_STONE_BRICK_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.MOSSY_STONE_BRICK_WALL).setHasCustomTranslation().register();
		POLISHED_DIORITE_PIECES = PieceSets.createSet(Blocks.POLISHED_DIORITE, "polished_diorite", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.POLISHED_DIORITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.POLISHED_DIORITE_STAIRS).register();
		MOSSY_COBBLESTONE_PIECES = PieceSets.createSet(Blocks.MOSSY_COBBLESTONE, "mossy_cobblestone", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.MOSSY_COBBLESTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.MOSSY_COBBLESTONE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.MOSSY_COBBLESTONE_WALL).register();
		END_STONE_BRICK_PIECES = PieceSets.createSet(Blocks.END_STONE_BRICKS, "end_stone_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.END_STONE_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.END_STONE_BRICK_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.END_STONE_BRICK_WALL).setHasCustomTranslation().register();
		SMOOTH_SANDSTONE_PIECES = PieceSets.createSet(Blocks.SMOOTH_SANDSTONE, "smooth_sandstone", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.SMOOTH_SANDSTONE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.SMOOTH_SANDSTONE_STAIRS).setTexture("sandstone_top").register();
		SMOOTH_QUARTZ_PIECES = PieceSets.createSet(Blocks.SMOOTH_QUARTZ, "smooth_quartz", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.SMOOTH_QUARTZ_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.SMOOTH_QUARTZ_STAIRS).setTexture("quartz_block_bottom").register();
		GRANITE_PIECES = PieceSets.createSet(Blocks.GRANITE, "granite", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.GRANITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.GRANITE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.GRANITE_WALL).register();
		ANDESITE_PIECES = PieceSets.createSet(Blocks.ANDESITE, "andesite", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.ANDESITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.ANDESITE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.ANDESITE_WALL).register();
		RED_NETHER_BRICK_PIECES = PieceSets.createSet(Blocks.RED_NETHER_BRICKS, "red_nether_brick", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.RED_NETHER_BRICK_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.RED_NETHER_BRICK_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.RED_NETHER_BRICK_WALL).setHasCustomTranslation().register();
		POLISHED_ANDESITE_PIECES = PieceSets.createSet(Blocks.POLISHED_ANDESITE, "polished_andesite", PieceSet.NO_SLAB_OR_STAIRS).addVanillaPiece(PieceType.SLAB, Blocks.POLISHED_ANDESITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.POLISHED_ANDESITE_STAIRS).register();
		DIORITE_PIECES = PieceSets.createSet(Blocks.DIORITE, "diorite", PieceSet.NO_SLAB_STAIRS_OR_WALL).addVanillaPiece(PieceType.SLAB, Blocks.DIORITE_SLAB).addVanillaPiece(PieceType.STAIRS, Blocks.DIORITE_STAIRS).addVanillaPiece(PieceType.WALL, Blocks.DIORITE_WALL).register();
		NETHERRACK_PIECES = PieceSets.createSet(Blocks.NETHERRACK, "netherrack").register();
		END_STONE_PIECES = PieceSets.createSet(Blocks.END_STONE, "end_stone").register();
		QUARTZ_PILLAR_PIECES = PieceSets.createSet(Blocks.QUARTZ_PILLAR, "quartz_pillar").setTopTexture("quartz_pillar_top").register();
		CHISELED_QUARTZ_PIECES = PieceSets.createSet(Blocks.CHISELED_QUARTZ_BLOCK, "chiseled_quartz").setTopTexture("chiseled_quartz_block_top").setHasCustomTranslation().register();
		CHISELED_SANDSTONE_PIECES = PieceSets.createSet(Blocks.CHISELED_SANDSTONE, "chiseled_sandstone").setTopTexture("sandstone_top").register();
		CHISELED_RED_SANDSTONE_PIECES = PieceSets.createSet(Blocks.CHISELED_RED_SANDSTONE, "chiseled_red_sandstone").setTopTexture("red_sandstone_top").register();
		CRACKED_STONE_BRICK_PIECES = PieceSets.createSet(Blocks.CRACKED_STONE_BRICKS, "cracked_stone_brick").setHasCustomTranslation().register();
		CHISELED_STONE_BRICK_PIECES = PieceSets.createSet(Blocks.CHISELED_STONE_BRICKS, "chiseled_stone_brick").setHasCustomTranslation().register();
		PURPUR_PILLAR_PIECES = PieceSets.createSet(Blocks.PURPUR_PILLAR, "purpur_pillar").setTopTexture("purpur_pillar_top").register();
		TERRACOTTA_PIECES = PieceSets.createSet(Blocks.TERRACOTTA, "terracotta").register();
		WHITE_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.WHITE_TERRACOTTA, "white_terracotta").register();
		ORANGE_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.ORANGE_TERRACOTTA, "orange_terracotta").register();
		MAGENTA_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.MAGENTA_TERRACOTTA, "magenta_terracotta").register();
		LIGHT_BLUE_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIGHT_BLUE_TERRACOTTA, "light_blue_terracotta").register();
		YELLOW_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.YELLOW_TERRACOTTA, "yellow_terracotta").register();
		LIME_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIME_TERRACOTTA, "lime_terracotta").register();
		PINK_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.PINK_TERRACOTTA, "pink_terracotta").register();
		GRAY_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.GRAY_TERRACOTTA, "gray_terracotta").register();
		LIGHT_GRAY_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIGHT_GRAY_TERRACOTTA, "light_gray_terracotta").register();
		CYAN_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.CYAN_TERRACOTTA, "cyan_terracotta").register();
		PURPLE_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.PURPLE_TERRACOTTA, "purple_terracotta").register();
		BLUE_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BLUE_TERRACOTTA, "blue_terracotta").register();
		BROWN_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BROWN_TERRACOTTA, "brown_terracotta").register();
		GREEN_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.GREEN_TERRACOTTA, "green_terracotta").register();
		RED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.RED_TERRACOTTA, "red_terracotta").register();
		BLACK_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BLACK_TERRACOTTA, "black_terracotta").register();
		WHITE_CONCRETE_PIECES = PieceSets.createSet(Blocks.WHITE_CONCRETE, "white_concrete").register();
		ORANGE_CONCRETE_PIECES = PieceSets.createSet(Blocks.ORANGE_CONCRETE, "orange_concrete").register();
		MAGENTA_CONCRETE_PIECES = PieceSets.createSet(Blocks.MAGENTA_CONCRETE, "magenta_concrete").register();
		LIGHT_BLUE_CONCRETE_PIECES = PieceSets.createSet(Blocks.LIGHT_BLUE_CONCRETE, "light_blue_concrete").register();
		YELLOW_CONCRETE_PIECES = PieceSets.createSet(Blocks.YELLOW_CONCRETE, "yellow_concrete").register();
		LIME_CONCRETE_PIECES = PieceSets.createSet(Blocks.LIME_CONCRETE, "lime_concrete").register();
		PINK_CONCRETE_PIECES = PieceSets.createSet(Blocks.PINK_CONCRETE, "pink_concrete").register();
		GRAY_CONCRETE_PIECES = PieceSets.createSet(Blocks.GRAY_CONCRETE, "gray_concrete").register();
		LIGHT_GRAY_CONCRETE_PIECES = PieceSets.createSet(Blocks.LIGHT_GRAY_CONCRETE, "light_gray_concrete").register();
		CYAN_CONCRETE_PIECES = PieceSets.createSet(Blocks.CYAN_CONCRETE, "cyan_concrete").register();
		PURPLE_CONCRETE_PIECES = PieceSets.createSet(Blocks.PURPLE_CONCRETE, "purple_concrete").register();
		BLUE_CONCRETE_PIECES = PieceSets.createSet(Blocks.BLUE_CONCRETE, "blue_concrete").register();
		BROWN_CONCRETE_PIECES = PieceSets.createSet(Blocks.BROWN_CONCRETE, "brown_concrete").register();
		GREEN_CONCRETE_PIECES = PieceSets.createSet(Blocks.GREEN_CONCRETE, "green_concrete").register();
		RED_CONCRETE_PIECES = PieceSets.createSet(Blocks.RED_CONCRETE, "red_concrete").register();
		BLACK_CONCRETE_PIECES = PieceSets.createSet(Blocks.BLACK_CONCRETE, "black_concrete").register();
		GOLD_PIECES = PieceSets.createSet(Blocks.GOLD_BLOCK, "gold").setHasCustomTranslation().register();
		IRON_PIECES = PieceSets.createSet(Blocks.IRON_BLOCK, "iron").setHasCustomTranslation().register();
		DIAMOND_PIECES = PieceSets.createSet(Blocks.DIAMOND_BLOCK, "diamond").setHasCustomTranslation().register();
		EMERALD_PIECES = PieceSets.createSet(Blocks.EMERALD_BLOCK, "emerald").setHasCustomTranslation().register();
		REDSTONE_PIECES = PieceSets.createSet(Blocks.REDSTONE_BLOCK, "redstone").setHasCustomTranslation().register();
		COAL_PIECES = PieceSets.createSet(Blocks.COAL_BLOCK, "coal").setHasCustomTranslation().register();
		LAPIS_LAZULI_PIECES = PieceSets.createSet(Blocks.LAPIS_BLOCK, "lapis_lazuli").setHasCustomTranslation().register();
		PACKED_ICE_PIECES = PieceSets.createSet(Blocks.PACKED_ICE, "packed_ice").register();
		WHITE_WOOL_PIECES = PieceSets.createSet(Blocks.WHITE_WOOL, "white_wool").register();
		ORANGE_WOOL_PIECES = PieceSets.createSet(Blocks.ORANGE_WOOL, "orange_wool").register();
		MAGENTA_WOOL_PIECES = PieceSets.createSet(Blocks.MAGENTA_WOOL, "magenta_wool").register();
		LIGHT_BLUE_WOOL_PIECES = PieceSets.createSet(Blocks.LIGHT_BLUE_WOOL, "light_blue_wool").register();
		YELLOW_WOOL_PIECES = PieceSets.createSet(Blocks.YELLOW_WOOL, "yellow_wool").register();
		LIME_WOOL_PIECES = PieceSets.createSet(Blocks.LIME_WOOL, "lime_wool").register();
		PINK_WOOL_PIECES = PieceSets.createSet(Blocks.PINK_WOOL, "pink_wool").register();
		GRAY_WOOL_PIECES = PieceSets.createSet(Blocks.GRAY_WOOL, "gray_wool").register();
		LIGHT_GRAY_WOOL_PIECES = PieceSets.createSet(Blocks.LIGHT_GRAY_WOOL, "light_gray_wool").register();
		CYAN_WOOL_PIECES = PieceSets.createSet(Blocks.CYAN_WOOL, "cyan_wool").register();
		PURPLE_WOOL_PIECES = PieceSets.createSet(Blocks.PURPLE_WOOL, "purple_wool").register();
		BLUE_WOOL_PIECES = PieceSets.createSet(Blocks.BLUE_WOOL, "blue_wool").register();
		BROWN_WOOL_PIECES = PieceSets.createSet(Blocks.BROWN_WOOL, "brown_wool").register();
		GREEN_WOOL_PIECES = PieceSets.createSet(Blocks.GREEN_WOOL, "green_wool").register();
		RED_WOOL_PIECES = PieceSets.createSet(Blocks.RED_WOOL, "red_wool").register();
		BLACK_WOOL_PIECES = PieceSets.createSet(Blocks.BLACK_WOOL, "black_wool").register();
		WHITE_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.WHITE_GLAZED_TERRACOTTA, "white_glazed_terracotta").register();
		ORANGE_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.ORANGE_GLAZED_TERRACOTTA, "orange_glazed_terracotta").register();
		MAGENTA_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.MAGENTA_GLAZED_TERRACOTTA, "magenta_glazed_terracotta").register();
		LIGHT_BLUE_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA, "light_blue_glazed_terracotta").register();
		YELLOW_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.YELLOW_GLAZED_TERRACOTTA, "yellow_glazed_terracotta").register();
		LIME_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIME_GLAZED_TERRACOTTA, "lime_glazed_terracotta").register();
		PINK_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.PINK_GLAZED_TERRACOTTA, "pink_glazed_terracotta").register();
		GRAY_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.GRAY_GLAZED_TERRACOTTA, "gray_glazed_terracotta").register();
		LIGHT_GRAY_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA, "light_gray_glazed_terracotta").register();
		CYAN_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.CYAN_GLAZED_TERRACOTTA, "cyan_glazed_terracotta").register();
		PURPLE_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.PURPLE_GLAZED_TERRACOTTA, "purple_glazed_terracotta").register();
		BLUE_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BLUE_GLAZED_TERRACOTTA, "blue_glazed_terracotta").register();
		BROWN_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BROWN_GLAZED_TERRACOTTA, "brown_glazed_terracotta").register();
		GREEN_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.GREEN_GLAZED_TERRACOTTA, "green_glazed_terracotta").register();
		RED_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.RED_GLAZED_TERRACOTTA, "red_glazed_terracotta").register();
		BLACK_GLAZED_TERRACOTTA_PIECES = PieceSets.createSet(Blocks.BLACK_GLAZED_TERRACOTTA, "black_glazed_terracotta").register();
		OBSIDIAN_PIECES = PieceSets.createSet(Blocks.OBSIDIAN, "obsidian").register();
		BONE_PIECES = PieceSets.createSet(Blocks.BONE_BLOCK, "bone").setTexture("bone_block_side").setTopTexture("bone_block_top").setHasCustomTranslation().register();
		HAY_PIECES = PieceSets.createSet(Blocks.HAY_BLOCK, "hay").setTexture("hay_block_side").setTopTexture("hay_block_top").setHasCustomTranslation().register();
		PUMPKIN_PIECES = PieceSets.createSet(Blocks.PUMPKIN, "pumpkin").setTexture("pumpkin_side").setTopTexture("pumpkin_top").register();
		MELON_PIECES = PieceSets.createSet(Blocks.MELON, "melon").setTexture("melon_side").setTopTexture("melon_top").register();
		SNOW_PIECES = PieceSets.createSet(Blocks.SNOW_BLOCK, "snow").setTexture("snow").setHasCustomTranslation().register();
		MAGMA_PIECES = PieceSets.createSet(Blocks.MAGMA_BLOCK, "magma").setTexture("magma").setHasCustomTranslation().register();
		GLOWSTONE_PIECES = PieceSets.createSet(Blocks.GLOWSTONE, "glowstone").register();
		NETHER_WART_PIECES = PieceSets.createSet(Blocks.NETHER_WART_BLOCK, "nether_wart").setHasCustomTranslation().register();
		BROWN_MUSHROOM_PIECES = PieceSets.createSet(Blocks.BROWN_MUSHROOM_BLOCK, "brown_mushroom").setHasCustomTranslation().register();
		RED_MUSHROOM_PIECES = PieceSets.createSet(Blocks.RED_MUSHROOM_BLOCK, "red_mushroom").setHasCustomTranslation().register();
		MUSHROOM_STEM_PIECES = PieceSets.createSet(Blocks.MUSHROOM_STEM, "mushroom_stem").register();
		DRIED_KELP_PIECES = PieceSets.createSet(Blocks.DRIED_KELP_BLOCK, "dried_kelp").setTexture("dried_kelp_side").setTopTexture("dried_kelp_top").setBottomTexture("dried_kelp_bottom").setHasCustomTranslation().register();
		TUBE_CORAL_PIECES = PieceSets.createSet(Blocks.TUBE_CORAL_BLOCK, "tube_coral").setHasCustomTranslation().register();
		BRAIN_CORAL_PIECES = PieceSets.createSet(Blocks.BRAIN_CORAL_BLOCK, "brain_coral").setHasCustomTranslation().register();
		BUBBLE_CORAL_PIECES = PieceSets.createSet(Blocks.BUBBLE_CORAL_BLOCK, "bubble_coral").setHasCustomTranslation().register();
		FIRE_CORAL_PIECES = PieceSets.createSet(Blocks.FIRE_CORAL_BLOCK, "fire_coral").setHasCustomTranslation().register();
		HORN_CORAL_PIECES = PieceSets.createSet(Blocks.HORN_CORAL_BLOCK, "horn_coral").setHasCustomTranslation().register();
		DEAD_TUBE_CORAL_PIECES = PieceSets.createSet(Blocks.DEAD_TUBE_CORAL_BLOCK, "dead_tube_coral").setHasCustomTranslation().register();
		DEAD_BRAIN_CORAL_PIECES = PieceSets.createSet(Blocks.DEAD_BRAIN_CORAL_BLOCK, "dead_brain_coral").setHasCustomTranslation().register();
		DEAD_BUBBLE_CORAL_PIECES = PieceSets.createSet(Blocks.DEAD_BUBBLE_CORAL_BLOCK, "dead_bubble_coral").setHasCustomTranslation().register();
		DEAD_FIRE_CORAL_PIECES = PieceSets.createSet(Blocks.DEAD_FIRE_CORAL_BLOCK, "dead_fire_coral").setHasCustomTranslation().register();
		DEAD_HORN_CORAL_PIECES = PieceSets.createSet(Blocks.DEAD_HORN_CORAL_BLOCK, "dead_horn_coral").setHasCustomTranslation().register();
		OAK_LOG_PIECES = PieceSets.createSet(Blocks.OAK_LOG, "oak_log").setTopTexture("oak_log_top").register();
		SPRUCE_LOG_PIECES = PieceSets.createSet(Blocks.SPRUCE_LOG, "spruce_log").setTopTexture("spruce_log_top").register();
		BIRCH_LOG_PIECES = PieceSets.createSet(Blocks.BIRCH_LOG, "birch_log").setTopTexture("birch_log_top").register();
		JUNGLE_LOG_PIECES = PieceSets.createSet(Blocks.JUNGLE_LOG, "jungle_log").setTopTexture("jungle_log_top").register();
		ACACIA_LOG_PIECES = PieceSets.createSet(Blocks.ACACIA_LOG, "acacia_log").setTopTexture("acacia_log_top").register();
		DARK_OAK_LOG_PIECES = PieceSets.createSet(Blocks.DARK_OAK_LOG, "dark_oak_log").setTopTexture("dark_oak_log_top").register();
		STRIPPED_OAK_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_OAK_LOG, "stripped_oak_log").setTopTexture("stripped_oak_log_top").register();
		STRIPPED_SPRUCE_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_SPRUCE_LOG, "stripped_spruce_log").setTopTexture("stripped_spruce_log_top").register();
		STRIPPED_BIRCH_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_BIRCH_LOG, "stripped_birch_log").setTopTexture("stripped_birch_log_top").register();
		STRIPPED_JUNGLE_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_JUNGLE_LOG, "stripped_jungle_log").setTopTexture("stripped_jungle_log_top").register();
		STRIPPED_ACACIA_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_ACACIA_LOG, "stripped_acacia_log").setTopTexture("stripped_acacia_log_top").register();
		STRIPPED_DARK_OAK_LOG_PIECES = PieceSets.createSet(Blocks.STRIPPED_DARK_OAK_LOG, "stripped_dark_oak_log").setTopTexture("stripped_dark_oak_log_top").register();
		OAK_WOOD_PIECES = PieceSets.createSet(Blocks.OAK_WOOD, "oak_wood").setTexture("oak_log").register();
		SPRUCE_WOOD_PIECES = PieceSets.createSet(Blocks.SPRUCE_WOOD, "spruce_wood").setTexture("spruce_log").register();
		BIRCH_WOOD_PIECES = PieceSets.createSet(Blocks.BIRCH_WOOD, "birch_wood").setTexture("birch_log").register();
		JUNGLE_WOOD_PIECES = PieceSets.createSet(Blocks.JUNGLE_WOOD, "jungle_wood").setTexture("jungle_log").register();
		ACACIA_WOOD_PIECES = PieceSets.createSet(Blocks.ACACIA_WOOD, "acacia_wood").setTexture("acacia_log").register();
		DARK_OAK_WOOD_PIECES = PieceSets.createSet(Blocks.DARK_OAK_WOOD, "dark_oak_wood").setTexture("dark_oak_log").register();
		STRIPPED_OAK_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_OAK_WOOD, "stripped_oak_wood").setTexture("stripped_oak_log").register();
		STRIPPED_SPRUCE_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_SPRUCE_WOOD, "stripped_spruce_wood").setTexture("stripped_spruce_log").register();
		STRIPPED_BIRCH_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_BIRCH_WOOD, "stripped_birch_wood").setTexture("stripped_birch_log").register();
		STRIPPED_JUNGLE_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_JUNGLE_WOOD, "stripped_jungle_wood").setTexture("stripped_jungle_log").register();
		STRIPPED_ACACIA_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_ACACIA_WOOD, "stripped_acacia_wood").setTexture("stripped_acacia_log").register();
		STRIPPED_DARK_OAK_WOOD_PIECES = PieceSets.createSet(Blocks.STRIPPED_DARK_OAK_WOOD, "stripped_dark_oak_wood").setTexture("stripped_dark_oak_log").register();
	}
}